### ISSUE TITLE
Get.offAllNamed() accidentally remove destination's controller

### ISSUE THREAD

**Issue by rockerhieu** [jonataslaw/getx#287] opened 2020-06-25 23:04 UTC
**Describe the bug**
`Get.offAllNamed(destination)` clean up `destination` immediately.

i.e currently at `/home` and call `Get.offAllNamed('/other')` will initialize `OtherBloc`, remove `/home` and then also delete `OtherBloc`. `OtherBloc` should not be deleted if `/home` is removed.

```
I/flutter ( 6632): [GOING TO ROUTE] /home
I/flutter ( 6632): [GET] OtherBloc has been initialized
I/flutter ( 6632): [GOING TO ROUTE] /other
I/flutter ( 6632): [REMOVING ROUTE] /home
I/flutter ( 6632): [GET] onClose of OtherBloc called
I/flutter ( 6632): [GET] OtherBloc deleted from memory
```

**To Reproduce**
1. Go to 'Go to Other page'
2. See error
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building OtherPage:
The getter '_updaters' was called on null.
Receiver: null
Tried calling: _updaters
```

**Flutter Version:**
17.3.1

**Get Version:**
2.14.1

**Describe on which device you found the bug:**
Pixel 4XL

**Minimal reproduce code**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      initialRoute: '/home',
      getPages: _getPages(),
    );
  }

  List<GetPage> _getPages() {
    return [
      GetPage(
        name: '/home',
        page: () => HomePage(),
      ),
      GetPage(
        name: '/other',
        page: () => OtherPage(),
        binding: OtherBindings(),
      ),
    ];
  }
}

class HomePage extends StatelessWidget {
  const HomePage({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Home'),
            RaisedButton(
              onPressed: () => Get.offAllNamed('/other'),
              child: Text('Go to Other page'),
            )
          ],
        ),
      ),
    );
  }
}

class OtherPage extends StatelessWidget {
  const OtherPage({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetBuilder<OtherBloc>(
      builder: (bloc) => Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              StreamBuilder<int>(
                initialData: bloc.count.value,
                stream: bloc.count.stream,
                builder: (context, snapshot) {
                  return Text('Counter: ${bloc.count.value}');
                }
              ),
              RaisedButton(
                onPressed: () => bloc.count.value++,
                child: Text('+'),
              ),
              RaisedButton(
                onPressed: () => Get.offAllNamed('/home'),
                child: Text('Go Back'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class OtherBindings implements Bindings {
  @override
  void dependencies() {
    Get.put(OtherBloc());
  }
}

class OtherBloc extends BaseBloc {
  var count = 0.obs;
}

class BaseBloc extends GetController {}
```

**Comment by rockerhieu** [comment] 2020-06-25 23:13
Same issue with `offNamed`

**Comment by rockerhieu** [comment] 2020-06-25 23:27
As suggested by Katekko, I have changed to RxController and GetX (instead of GetBuilder) but the problem still got the same issue:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      initialRoute: '/home',
      getPages: _getPages(),
    );
  }

  List<GetPage> _getPages() {
    return [
      GetPage(
        name: '/home',
        page: () => HomePage(),
      ),
      GetPage(
        name: '/other',
        page: () => OtherPage(),
        binding: OtherBindings(),
      ),
    ];
  }
}

class HomePage extends StatelessWidget {
  const HomePage({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Home'),
            RaisedButton(
              onPressed: () {
                Get.offAllNamed('/other');
              },
              child: Text('Go to Other page'),
            )
          ],
        ),
      ),
    );
  }
}

class OtherPage extends StatelessWidget {
  const OtherPage({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetX<OtherBloc>(
      builder: (bloc) => Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Counter: ${bloc.count.value}'),
              RaisedButton(
                onPressed: () => bloc.count.value++,
                child: Text('+'),
              ),
              RaisedButton(
                onPressed: () => Get.offAllNamed('/home'),
                child: Text('Go Back'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class OtherBindings implements Bindings {
  @override
  void dependencies() {
    Get.put(OtherBloc());
  }
}

class OtherBloc extends BaseBloc {
  var count = 0.obs;
}

class BaseBloc extends RxController {}
```

**Comment by jonataslaw** [comment] 2020-06-25 23:33
This seems to me like a bug introduced in the last update, in which the Bindings call was anticipated.
This may be causing it to enter the previous route stack, I will investigate this. Thank you for providing a reproduction of the problem.

**Comment by rockerhieu** [comment] 2020-06-26 00:36
@jonataslaw I don't think it's a new issue. I've tried all versions all the way back to v2.0.0 and still got the same issue.

**Comment by jonataslaw** [comment] 2020-06-26 16:51
> @jonataslaw I don't think it's a new issue. I've tried all versions all the way back to v2.0.0 and still got the same issue.

It is probably the local cache that is sending the latest version to you. I checked the problem, and I was able to confirm that it only happened in the last update (which is now a penultimate). The problem has been fixed since yesterday, so I'm closing this issue.

**Closed by jonataslaw** 2020-06-26 16:51 UTC
