### ISSUE TITLE
GetX page routing breaks and returns "null check operator used on a null value" in updated version of Flutter

### ISSUE THREAD

**Issue by RobynKing88** [jonataslaw/getx#1740] opened 2021-08-08 14:17 UTC
I am trying to do a very simple page routing with GetX using the latest version of Flutter which includes null safety. It keeps returning the error "Null check operator used on a null value" even when I am passing no arguments or referencing any variables.

Here is my very simple code:

``
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
      getPages: [GetPage(name: PageTwo.id, page: () => PageTwo())],
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _newPage() {
    Get.toNamed(PageTwo.id);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _newPage,
        tooltip: 'newPage',
        child: Icon(Icons.add),
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  static String id = 'page2';
  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      child: Text('hi'),
    );
  }
}
``
As you can see, no reason to pick up any null values.

I am using the following packages in my pubspec.yaml file:
``
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.4
``
I was testing on an iPhone 12 simulator

**Comment by jonataslaw** [comment] 2021-08-08 16:36
Duplicate of https://github.com/jonataslaw/getx/issues/1691

**Closed by jonataslaw** 2021-08-08 16:36 UTC

**Comment by RobynKing88** [comment] 2021-08-08 17:42
Hi there, there are a host of different issues raised in #1691; not sure which one this is a duplication of? It has always worked before with just getPages defined; is there a requirement that we now use routes?

**Comment by jonataslaw** [comment] 2021-08-08 17:44
slash, you routeName hasn't slash.

**Comment by RobynKing88** [comment] 2021-08-08 17:46
Thanks! Sorry I just updated Flutter and Get so wasn't aware this was a requirement now. I didn't add a slash but I did add an initial route and routes and it now works.
