### ISSUE TITLE
Controllers are improperly handled in dialogs

### ISSUE THREAD

**Issue by psrcek** [jonataslaw/getx#705] opened 2020-10-13 07:22 UTC
**Describe the bug**
I need to be able to create a controller for each one of my dialogs.
GetX controllers never get cleaned up if they are created inside a dialog after it is closed, therefore after one dialog is created all subsequent dialogs reuse the created controller.

**Reproduction code**

example:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() => runApp(GetMaterialApp(home: Home()));

class ExampleDialogController extends GetxController {
  final int count;

  ExampleDialogController(this.count);
}

class ExampleDialog extends StatelessWidget {
  final ExampleDialogController c;

  ExampleDialog(int count) : c = Get.put(ExampleDialogController(count));

  @override
  Widget build(context) {
    return Text('${c.count}');
  }
}

class Home extends StatelessWidget {
  final count = 0.obs;

  @override
  Widget build(context) {
    return Scaffold(
      appBar: AppBar(title: Text("GetX dialog bug")),
      body: Center(
        child: Obx(() => Text("$count")),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          count.value++;

          Get.dialog(
            SimpleDialog(
              title: Text('Test dialog'),
              children: [
                ExampleDialog(count.value),
              ],
            ),
          );
        },
      ),
    );
  }
}
```

**To Reproduce**
1. Click the fab a couple of times
2. The value in the dialog is not incremented because the controller is only initialized once.

**Expected behavior**
The controller to be reinitialized every time the dialog is reopened.

**Flutter Version:**
1.22.0

**Getx Version:**
3.13.2

**Describe on which device you found the bug:**
not important as it happens everywhere, but: Samsung galaxy a51

**Comment by eduardoflorence** [comment] 2020-10-13 21:43
`Get.create(()=>Controller())` is a way to create a new controller every time you run `Get.find()`

Use `Get.create()` instead of `Get.Put()`. Change your code like this:
```dart
class ExampleDialog extends StatelessWidget {
  ExampleDialog(int count) {
    Get.create(() => ExampleDialogController(count));
  }

  @override
  Widget build(context) {
    return Text('${Get.find<ExampleDialogController>().count}');
  }
}
```

**Comment by jonataslaw** [comment] 2020-10-26 17:06
You are calling Get.put in the initializer list from constructor.
The initializer list is called up before any route transition, still on the previous route.
You also don't need Put for dialogs, they are ephemeral.
Well, I don't think this is a bug, because the behavior described is exactly the expected behavior.

**Comment by jonataslaw** [comment] 2020-10-26 17:09
The way:

GetBuilder on root from dialog:
```dart
GetBuilder(
init: ExampleDialogController(), 
builder:(c)
```
Get.put() inside build method.

Well, as there is nothing wrong here, I am closing this issue

**Closed by jonataslaw** 2020-10-26 17:09 UTC
Labels: expected behavior
