### ISSUE TITLE
Dialog does not inherit the theme of material app

### ISSUE THREAD

**Issue by nothinggift** [jonataslaw/getx#608] opened 2020-09-13 19:45 UTC
main.dart
```dart
GetMaterialApp(
  title: 'app',
  themeMode: ThemeMode.dark,
  darkTheme: ThemeData(
    platform: TargetPlatform.iOS,
    fontFamily: 'PTSans',
    brightness: Brightness.dark,
    primaryColor: Hexcolor('#ED7829'),
    scaffoldBackgroundColor: Hexcolor('#082030'),
    textTheme: TextTheme(
      headline1: AppTheme.header1,
      bodyText1: AppTheme.body,
    ).apply(bodyColor: AppTheme.fontColor, fontSizeFactor: 18),
  ),
)
```

theme has no effect when using Get.dialog，I know that getx will use the context of the current route in the dialog. Why doesn't it work?
Both flutter and getx are the latest versions.

**Comment by manojeeva** [comment] 2020-09-14 03:44
Yes, I noticed too. 
Now I'm Wrapping Material Widget on Top.

**Comment by jonataslaw** [comment] 2020-10-01 20:21
You may be confused about using the dialogs api, but Get.dialog is the same as showDialog, but without the need for context.
It inherits the MaterialApp theme normally, as you can see in the reproduction code where the dialog has a blue background:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(
    translations: MyTranslations(),
    themeMode: ThemeMode.dark,
    darkTheme: ThemeData(
      platform: TargetPlatform.iOS,
      fontFamily: 'PTSans',
      brightness: Brightness.dark,
      primaryColor: Colors.red,
      dialogBackgroundColor: Colors.blue,
      scaffoldBackgroundColor: Colors.lightGreen,
      textTheme:
          TextTheme().apply(bodyColor: Colors.yellow, fontSizeFactor: 18),
    ),
    transitionDuration: Duration(milliseconds: 5000),
    locale: Locale('pt', 'BR'),
    home: const First(),
  ));
}

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'title': 'Hello World %s',
        },
        'en_US': {
          'title': 'Hello World from US',
        },
        'pt': {
          'title': 'Olá de Portugal',
        },
        'pt_BR': {
          'title': 'Olá do Brasil',
        },
      };
}

class First extends StatelessWidget {
  const First({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    print('first was build');
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(Icons.add),
          onPressed: () {
            // Get.snackbar("Hi", "I'm modern snackbar");
            Get.dialog(AlertDialog(
              content: Text("djisjdsi"),
            ));
          },
        ),
        title: Text("title".trArgs(['John'])),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            RaisedButton(
              child: Text('Next Route'),
              onPressed: () {
                Get.to(
                  Scaffold(
                    backgroundColor: Colors.red,
                  ),
                );
              },
            ),
            // RaisedButton(
            //   child: Text('Change locale to English'),
            //   // onPressed: () {
            //   //   Get.locale = Locale('en', 'UK');
            //   //   Get.changeTheme(ThemeData.dark());
            //   //   // Get.updateLocale(Locale('en', 'UK'));
            //   },
            // ),
          ],
        ),
      ),
    );
  }
}
```
Since this is not a issue, I am closing this.
If you believe you have a problem, open an issue with a reproduction code, the code provided in this example is not self-executing.

**Closed by jonataslaw** 2020-10-01 20:21 UTC
Labels: invalid
