### ISSUE TITLE
Dependency Not Found On Hot Reload Flutter Web

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/getx#662] opened 2020-09-28 17:22 UTC
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
On Flutter web, when I inject a dependency through bindings, `offAllNamed` to a new page, hot reloading causes

```sh
"AuthService" not found. You need to call "Get.put(AuthService())" or "Get.lazyPut(()=>AuthService())"

The relevant error-causing widget was
    SecondTestPage 
lib/main.dart:25
When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49                throw_
packages/get_instance/src/get_instance.dart 265:9                                           find
packages/get_instance/src/extension_instance.dart 64:44                                     Inst.find
packages/get_error_test/features/test%20copy/presentation/second_test_controller.dart 6:40  new
packages/get_error_test/features/test%20copy/presentation/second_test_page.dart 10:13       build
...
════════════════════════════════════════════════════════════════════════════════
```

**To Reproduce**
1. Run the minimal reproduce code.

**Expected behavior**
On reload, injected dependency remains in memory.

**Flutter Version:**
`Flutter Channel beta, 1.21.0-9.2.pre`

**Getx Version:**
`get: ^3.11.1`

**Describe on which device you found the bug:**
Chrome(web-javascript).

**Screenshot:**
![Peek 2020-09-28 18-20](https://user-images.githubusercontent.com/48252841/94465193-6d571a80-01b7-11eb-86fd-22dd619a8d33.gif)

**Minimal reproduce code**
```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      getPages: [
        GetPage(
          name: '/',
          page: () => TestPage(),
          binding: TestBinding(),
        ),
        GetPage(
          name: '/second',
          page: () => SecondTestPage(),
        )
      ],
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<TestController>(
      init: TestController(),
      builder: (_) {
        return Scaffold(
          appBar: AppBar(title: Text('TestPage')),
          body: Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(_.name),
                SizedBox(height: 40),
                FlatButton(onPressed: () => _.toTest(), child: Text('Move'))
              ],
            ),
          ),
        );
      },
    );
  }
}

class TestController extends GetxController {
  final AuthService _authService = Get.find();
  String get name => _authService.name;

  void toTest() {
    Get.offAllNamed('/second');
  }
}

class TestBinding implements Bindings {
  @override
  void dependencies() {
    Get.put<AuthService>(AuthService(), permanent: true);
  }
}

class SecondTestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<SecondTestController>(
      init: SecondTestController(),
      builder: (_) {
        return Scaffold(
          appBar: AppBar(title: Text('SecondTestPage')),
          body: Center(
            child: Text(_.name),
          ),
        );
      },
    );
  }
}

class SecondTestController extends GetxController {
  final AuthService _authService = Get.find();
  String get name => _authService.name;
}

class AuthService {
  String get name => 'Hello';
}

```

**Comment by jonataslaw** [comment] 2020-09-28 18:02
Looking at your code, I think everything is correct.
You start Binding on the first route, go to the second. Right after you directly access the second link (see, hot restart on the web behaves differently from mobile / desktop, you notice that the URL remains "/ second", because it tries to go directly to the route). As the second route does not have the preloading of the first Binding, it will not inject the controller.
Try to reproduce the problem with Android / iOS, or desktop. And you will see that this is not a problem, but if you want the solution, start your services in the InitialBinding. If you made this change, there would be no errors:

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      initialBinding: TestBinding(),
      getPages: [
        GetPage(
          name: '/',
          page: () => TestPage(),
        ),
        GetPage(
          name: '/second',
          page: () => SecondTestPage(),
        )
      ],
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<TestController>(
      init: TestController(),
      builder: (_) {
        return Scaffold(
          appBar: AppBar(title: Text('TestPage')),
          body: Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(_.name),
                SizedBox(height: 40),
                FlatButton(onPressed: () => _.toTest(), child: Text('Move'))
              ],
            ),
          ),
        );
      },
    );
  }
}

class TestController extends GetxController {
  final AuthService _authService = Get.find();
  String get name => _authService.name;

  void toTest() {
    Get.offAllNamed('/second');
  }
}

class TestBinding implements Bindings {
  @override
  void dependencies() {
    Get.put<AuthService>(AuthService(), permanent: true);
  }
}

class SecondTestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<SecondTestController>(
      init: SecondTestController(),
      builder: (_) {
        return Scaffold(
          appBar: AppBar(title: Text('SecondTestPage')),
          body: Center(
            child: Text(_.name),
          ),
        );
      },
    );
  }
}

class SecondTestController extends GetxController {
  final AuthService _authService = Get.find();
  String get name => _authService.name;
}

class AuthService {
  String get name => 'Hello';
}

```

**Comment by Prn-Ice** [comment] 2020-09-28 18:15
Thanks, the issue is not present on mobile. I plan to deploy the code for both mobile and web from one codebase, does this mean I have to duplicate dependency injections.

**Comment by jonataslaw** [comment] 2020-09-29 19:05
You can use Get.isRegistered<Controller>() in the binding of the second route as well, to initialize the dependency if it has not been initialized.
initialBinding is a option too.
As this is not a problem, but expected behavior, I am closing this.

**Closed by jonataslaw** 2020-09-29 19:05 UTC
Labels: expected behavior
