### ISSUE TITLE
Controller not remove and onClose not fired in v4.1.4

### ISSUE THREAD

**Issue by niypoo** [jonataslaw/getx#1426] opened 2021-05-12 20:11 UTC
After update to 4.1.4 , I have noticed a some controllers not fired onClose and event this controller not remove from memory !!

binding.dart
```
import 'package:Project/modules/itemAdd/itemAdd.controller.dart';
import 'package:get/get.dart';

class ItemAddBinding extends Bindings{
  @override
  void dependencies() {
    Get.lazyPut<ItemAddController>(() => ItemAddController());
  }
}

```

GetPage
```
 GetPage(
      name: '/item-add',
      page: () => ItemAddView(),
      binding: ItemAddBinding(),
    ),

```

controller.dart
```

class ItemAddController extends GetxController {
  // controller
  static ItemAddController get to => Get.find();

  @override
  void onInit() {
    getActiveOrDefualtBasket();
    super.onInit();
  }

}

```

View.dart

```
class ItemAddView extends GetView<ItemAddController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold( .... View Code ......);
}
}

```

console log

```

[GETX] GOING TO ROUTE /item-add
[GETX] Instance "ItemAddController" has been created
[GETX] Instance "ItemAddController" has been initialized
[GETX] CLOSE TO ROUTE /item-add
< ! ----- missing close controller --- !>
[GETX] GOING TO ROUTE /item-add
< ! ----- missing init controller due to not closed --- !>
[GETX] CLOSE TO ROUTE /item-add
```

**Comment by yasinarik** [comment] 2021-05-16 14:26
Yes, I can confirm that this happens. It didn't happen before as far as I can remember.

Some controllers just are not deleted from the memory after navigating back using `Get.back()`.

**Comment by BHALUU** [comment] 2021-05-16 15:55
I have the same issue too. The controller is not deleted from the memory. When i logout of my app and try to create a new user. The controller will contain previous values.

**Comment by niypoo** [comment] 2021-05-16 19:20
After more investigation  I downgrade to `3.25.0` and test found that 

the controller not fired onClose first time but in the 2nd time onClose fired 

```

[GETX] GOING TO ROUTE /item-add
[GETX] "ItemAddController" has been initialized
[GETX] CLOSE TO ROUTE /item-add
<!------ Missing onClose fired ----- !>
[GETX] GOING TO ROUTE /item-add
<!------ Missing OnInit fired due to not closed ----- !>
[GETX] CLOSE TO ROUTE /item-add
[GETX] "ItemAddController" onDelete() called
[GETX] "ItemAddController" deleted from memory


```

**Comment by niypoo** [comment] 2021-05-17 00:51
after downgrade to `get: 3.24.0 `
the issue has been gone 
so what I missing  ?

```
[GETX] GOING TO ROUTE /item-add
[GETX] "ItemAddController" has been initialized
[GETX] CLOSE TO ROUTE /item-add
[GETX] "ItemAddController" onClose() called
[GETX] "ItemAddController" deleted from memory

```

**Comment by niypoo** [comment] 2021-05-17 01:27
I have reduced the code and found something weird for me 

```
// focus on title text field
    Future.delayed(Duration(milliseconds: 300))
        .then((value) => titleFocus.requestFocus());

```
I'm calling this code in `onReady` after disabled the life circle work as sharm !! I will investigation more in next time.

for any one facing this issue make a  all  life circle  empty and try.

**Comment by niypoo** [comment] 2021-05-17 01:33
so after add `autofocus:true,` to textField I have facing this issue again ,
so I have found the issue and please let me know if this is normal behavior or not.

if soft keyboard is opening and close the stack 'view' the `onClose` never fired but if I closed keyboard before close the view the controller fired the `onClose` as normal !!!

**Comment by xiaozhizhong** [comment] 2021-05-20 01:58
Same with #1193

**Comment by stjfk** [comment] 2021-05-20 07:10
works on first use then doesn't work

**Comment by aboda1986** [comment] 2021-05-20 17:44
Any update about this issue?

**Comment by niypoo** [comment] 2021-05-21 01:07
> Any update about this issue?

For quick fix I have to unFoucs before 'get.back()' and wait 300ms and wait any update to fix this issue

**Comment by hatemragab** [comment] 2021-05-22 18:56
same problem

**Comment by jonataslaw** [comment] 2021-05-22 22:48
Can anyone make the reproduction code for this issue? If there is a reproducible code, I guarantee that we will fix it in the next update, but without the code we cannot analyze it

**Comment by yasinarik** [comment] 2021-05-23 05:46
> > Any update about this issue?
> 
> For a quick fix I have to unFoucs before 'get.back()' and wait 300ms and wait any update to fix this issue
> 

I believe the issue is not related to a text field. 

Because I faced this issue when I go to an empty scaffold as a route and then navigate back. 

Is everyone that face this issue sure that they are using 

`Get.put(()=>NewScreen())`

instead of using
`Get.put(NewScreen())` ?

Also it may help to know if you are using nested navigators or not.

**Comment by niypoo** [comment] 2021-05-23 11:19
> > > Any update about this issue?
> > 
> > For a quick fix I have to unFoucs before 'get.back()' and wait 300ms and wait any update to fix this issue
> > 
> 
> I believe the issue is not related to a text field. 
> 
> Because I faced this issue when I go to an empty scaffold as a route and then navigate back. 
> 
> Is everyone that face this issue sure that they are using 
> 
> `Get.put(()=>NewScreen())`
> 
> instead of using
> `Get.put(NewScreen())` ?
> 
> Also it may help to know if you are using nested navigators or not.
> 
> 
> 
> 
> 

In my case It's happening with named route with lazyput

**Comment by hatemragab** [comment] 2021-05-23 12:26
in my case if unhandled exception throw the controller not fire onClose

**Comment by hatemragab** [comment] 2021-05-23 12:35
```  @override
  void onClose() {
    emitTypingChange(0);
    textController.dispose();
    _log.info("onClose");
    return super.onClose();
  }
```
this this my problem not getx 
becouse
emitTypingChange(0);
stop  the controller from close 
becouse if no internet this function not end unit there connection availbe 
emitTypingChange

**Comment by hatemragab** [comment] 2021-05-23 12:43
and if emitTypingChange(0); 
throw exception 
the controller also not delete

**Comment by hatemragab** [comment] 2021-05-23 12:58
```
  @override
  void onClose() {
    try {
      if (isEmitTyping) {
        emitTypingChange(0);
      }
      textController.dispose();
      _log.info("onClose");
    } catch (err) {
      _log.error(err);
    } finally {
      return super.onClose();
    }
  }
```
this 100% fix my case

**Comment by lgGuo** [comment] 2021-05-25 06:17
i got the same problem in my project.the controller did not delete from memory when i close page. I used Get.to(()->PageA())

**Comment by lgGuo** [comment] 2021-05-25 07:44
> > > > Any update about this issue?
> > > 
> > > 
> > > For a quick fix I have to unFoucs before 'get.back()' and wait 300ms and wait any update to fix this issue
> > 
> > 
> > I believe the issue is not related to a text field.
> > Because I faced this issue when I go to an empty scaffold as a route and then navigate back.
> > Is everyone that face this issue sure that they are using
> > `Get.put(()=>NewScreen())`
> > instead of using
> > `Get.put(NewScreen())` ?
> > Also it may help to know if you are using nested navigators or not.
> 
> In my case It's happening with named route with lazyput

do you add GetMaterialApp in main.dart?

**Comment by lgGuo** [comment] 2021-05-25 07:45
> After update to 4.1.4 , I have noticed a some controllers not fired onClose and event this controller not remove from memory !!
> 
> binding.dart
> 
> ```
> import 'package:Project/modules/itemAdd/itemAdd.controller.dart';
> import 'package:get/get.dart';
> 
> class ItemAddBinding extends Bindings{
>   @override
>   void dependencies() {
>     Get.lazyPut<ItemAddController>(() => ItemAddController());
>   }
> }
> ```
> 
> GetPage
> 
> ```
>  GetPage(
>       name: '/item-add',
>       page: () => ItemAddView(),
>       binding: ItemAddBinding(),
>     ),
> ```
> 
> controller.dart
> 
> ```
> 
> class ItemAddController extends GetxController {
>   // controller
>   static ItemAddController get to => Get.find();
> 
>   @override
>   void onInit() {
>     getActiveOrDefualtBasket();
>     super.onInit();
>   }
> 
> }
> ```
> 
> View.dart
> 
> ```
> class ItemAddView extends GetView<ItemAddController> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold( .... View Code ......);
> }
> }
> ```
> 
> console log
> 
> ```
> 
> [GETX] GOING TO ROUTE /item-add
> [GETX] Instance "ItemAddController" has been created
> [GETX] Instance "ItemAddController" has been initialized
> [GETX] CLOSE TO ROUTE /item-add
> < ! ----- missing close controller --- !>
> [GETX] GOING TO ROUTE /item-add
> < ! ----- missing init controller due to not closed --- !>
> [GETX] CLOSE TO ROUTE /item-add
> ```

Do you add GetMaterialApp in main.dart?

**Comment by lgGuo** [comment] 2021-05-25 08:15
> Can anyone make the reproduction code for this issue? If there is a reproducible code, I guarantee that we will fix it in the next update, but without the code we cannot analyze it

Dose GetMaterialApp is seriously in main.dart?when i did not replace MaterialApp with GetMaterialApp ,it happened

**Comment by lgGuo** [comment] 2021-05-25 08:31
> After update to 4.1.4 , I have noticed a some controllers not fired onClose and event this controller not remove from memory !!
> 
> binding.dart
> 
> ```
> import 'package:Project/modules/itemAdd/itemAdd.controller.dart';
> import 'package:get/get.dart';
> 
> class ItemAddBinding extends Bindings{
>   @override
>   void dependencies() {
>     Get.lazyPut<ItemAddController>(() => ItemAddController());
>   }
> }
> ```
> 
> GetPage
> 
> ```
>  GetPage(
>       name: '/item-add',
>       page: () => ItemAddView(),
>       binding: ItemAddBinding(),
>     ),
> ```
> 
> controller.dart
> 
> ```
> 
> class ItemAddController extends GetxController {
>   // controller
>   static ItemAddController get to => Get.find();
> 
>   @override
>   void onInit() {
>     getActiveOrDefualtBasket();
>     super.onInit();
>   }
> 
> }
> ```
> 
> View.dart
> 
> ```
> class ItemAddView extends GetView<ItemAddController> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold( .... View Code ......);
> }
> }
> ```
> 
> console log
> 
> ```
> 
> [GETX] GOING TO ROUTE /item-add
> [GETX] Instance "ItemAddController" has been created
> [GETX] Instance "ItemAddController" has been initialized
> [GETX] CLOSE TO ROUTE /item-add
> < ! ----- missing close controller --- !>
> [GETX] GOING TO ROUTE /item-add
> < ! ----- missing init controller due to not closed --- !>
> [GETX] CLOSE TO ROUTE /item-add
> ```

show your main.dart and how do you navigate to next page

**Comment by lgGuo** [comment] 2021-05-25 08:32
show your main.dart and how do you navigate to this page

**Comment by lgGuo** [comment] 2021-05-25 08:35
> I have the same issue too. The controller is not deleted from the memory. When i logout of my app and try to create a new user. The controller will contain previous values.
did you replace MaterialApp with GetMaterialApp in main.dart?and how did you navigate to this page?

**Comment by alex-lechner** [comment] 2021-05-26 19:44
I have the same problem: I'm navigating to a route with `Get.toNamed('/my-route')`. After closing the page, the `onClose` method is not called.

**Comment by moosers** [comment] 2021-05-30 06:17
> Can anyone make the reproduction code for this issue? If there is a reproducible code, I guarantee that we will fix it in the next update, but without the code we cannot analyze it

in a page with TextField and  a lazyPut GetxController , open keyboard at textField , then press back button on appbar, when you open page again , you can see controller isn't disposed.

**Comment by matszafraniec** [comment] 2021-05-31 14:46
Same issue on my side. I can see that if focus is set for any textField (on page A), and I'm navigating to new page (page B). My workaround was to unfocus before performing navigation.

**Comment by nickwri** [comment] 2021-06-03 19:45
I am experiencing the same issue when a nested controller inside my main page controller calls showDatePicker. 
The nested controller is instantiated in the binding, and injected into the main page controller. The nested controller is used by a view showing some text fields and a date picker. 

All works great when editing the text fields, but once I open the datepicker, onClose is never called again for the main page controller (it is for the nested controller). When going back to the page, the nested controller holds old values.

**Comment by jonataslaw** [comment] 2021-06-08 23:38
Okay, there are a lot of complaints about the same problem.
In my projects this doesn't happen, so in order for me to reach a conclusion or solution of the problem, I need a reproduction code.
Could any of you please create a minimal reproduction code?

**Comment by MattheusOliveira** [comment] 2021-06-09 03:00
Olá @jonataslaw, criei um projeto de estudo e o mesmo não está chamando OnClose quando executo Get.toNamed('/my-route') conforme comentado por @alex-lechner. Segue o link do projeto mínimo para reprodução como solicitado. O problema ocorre ao ir da segunda_page.dart para terceira_page.dart. Obrigado. [https://github.com/MattheusOliveira/get_x](url)

**Comment by LoAlex** [comment] 2021-06-10 15:51
> Okay, there are a lot of complaints about the same problem.
> In my projects this doesn't happen, so in order for me to reach a conclusion or solution of the problem, I need a reproduction code.
> Could any of you please create a minimal reproduction code?

According to @niypoo replies, maybe you can compare to **3.25.0** and **3.24.0** changes, to analyze and identify what is the problem?

**Comment by MuhammadDicky** [comment] 2021-06-26 00:00
I have facing the same issue. I think the problem is when `screen_a` have access to **BuildContext** like when use Get.theme or Theme.of(Get.context!) and then move to `screen_b` and show keyboard by focus on textfield or some widget that may trigger keyboard to show up and then go back to previous screen without close that keyboard from `screen_b`, this will make controller from `screen_b` not deleted. Is not metter use **Get.put()** or binding controller on `screen_b`, the result is still the same.

I manage to reproduce the issue with this code

Main app
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
      getPages: [
        GetPage(
          name: SecondScreen.id,
          page: () => SecondScreen(),
          binding: SecondScreenControllerBinding(),
        ),
      ],
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  final String title;

  void _goToPage2() {
    Get.toNamed(
      SecondScreen.id,
    );
  }

  @override
  Widget build(BuildContext context) {
    // Try to use context before go to second screen, use MediaQuery.of(Get.context!) has the same result
    Get.mediaQuery;

    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Click button to go to second screen',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _goToPage2,
        tooltip: 'Go to second screen',
        child: Icon(Icons.arrow_forward_rounded),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```


Second screen with controller
```
class SecondScreen extends StatelessWidget {
  static const String id = 'second_screen';

  final SecondScreenController _screenController = Get.find();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second Screen'),
      ),
      body: Center(
        child: Obx(
          () => TextFormField(
            initialValue: _screenController.test.value,
            decoration: InputDecoration(
              labelText: 'Text Input',
            ),
            onChanged: _screenController.inputOnChange,
          ),
        ),
      ),
    );
  }
}

class SecondScreenControllerBinding extends Bindings {
  @override
  void dependencies() {
    Get.put<SecondScreenController>(
      SecondScreenController(),
    );
  }
}

class SecondScreenController extends GetxController {
  final Rxn<String?> test = Rxn(null);

  void inputOnChange(String? str) {
    test.value = str;
  }
}
```

To reproduce issue:
1. In **Main Screen**, click button to go to second screen
2. Click/focus on textfield to open keyboard
3. Go back to previous screen without closing the keyboard from the second screen

**Comment by tmtit** [comment] 2021-07-01 03:09
@jonataslaw I tested on virtual machine and it didn't happen but it did on real device.

**Comment by MuhammadDicky** [comment] 2021-07-01 03:11
@jonataslaw Im also test this on physical device but not tested on virtual device

**Comment by CoderXiaoming** [comment] 2021-07-15 02:37
@jonataslaw I have the same problem

**Comment by slorop41314** [comment] 2021-07-22 10:40
@jonataslaw is it fixed on newer version?

**Comment by CoderXiaoming** [comment] 2021-07-30 03:56
Interim solution, delete the following from the project:
Get.context
Get.width
Get.height
Get.size
...

**Comment by gustavo-perini** [comment] 2021-07-30 15:09
@jonataslaw same issue here. v4.3.0

**Comment by cungtrang0978** [comment] 2021-08-02 11:44
@MuhammadDicky @niypoo @gustavo-perini @jonataslaw 
I deleted Get.mediaQuery in FirstScreen, then navigate to SecondScreen, show the keyboard, then call Get.back() => Controller has been closed. This works for me.

**Comment by jonataslaw** [comment] 2021-08-02 18:49
This bug has already been fixed, just update to the latest version.

**Closed by jonataslaw** 2021-08-02 18:49 UTC
Labels: Waiting for customer response

**Comment by jonataslaw** [comment] 2021-08-02 18:51
> Olá @jonataslaw, criei um projeto de estudo e o mesmo não está chamando OnClose quando executo Get.toNamed('/my-route') conforme comentado por @alex-lechner. Segue o link do projeto mínimo para reprodução como solicitado. O problema ocorre ao ir da segunda_page.dart para terceira_page.dart. Obrigado. [https://github.com/MattheusOliveira/get_x](url)

Get.toNamed don't remove the controller, Get.offNamed does it

**Comment by UMUTARPT** [comment] 2021-09-25 08:51
> Get.toNamed don't remove the controller, Get.offNamed does it

Hello sir big fan long time getx user. Firstly thank you for this amazing package. My issue is I am developing in Web and user needs to use backbutton a lot because there are a lot of nested pages. With Get.toNamed I can use back button but it doesn't close controllers. Get.offNamed fixes my issue on closing controllers, but I can't use back button. Is there a way to use browser's back and forward buttons with offNamed ? @jonataslaw

**Comment by hatemragab** [comment] 2021-11-24 07:30
It still happening !!

**Comment by SimonHausdorf** [comment] 2022-03-08 11:42
@jonataslaw it seems like this issue still exists?

In our case we have to delay the autofocus of an input otherwise controllers will be initialized where they shouldn't. We are using `Get.offAllNamed()` to go to a new route with autofocus input. Someone the controllers are getting initialized and disposed but the controllers aren't used on the new screen.

**Comment by jonataslaw** [comment] 2022-03-08 11:52
> @jonataslaw it seems like this issue still exists?
> 
> In our case we have to delay the autofocus of an input otherwise controllers will be initialized where they shouldn't. We are using `Get.offAllNamed()` to go to a new route with autofocus input. Someone the controllers are getting initialized and disposed but the controllers aren't used on the new screen.

Which getx version are you using?

**Comment by SimonHausdorf** [comment] 2022-03-08 12:03
4.6.1

**Comment by greyovo** [comment] 2023-05-15 02:57
Some tips for later developers:

It's possible that in `onClose()`, your code will throw an exception that won't get to the end of the execution and will fail to fire the `onDelete()` method, causing GetInsatnce to fail to remove your controller instance from memory.

Solution: try inserting a `try-catch` block into the `onClose` method. If an error is caught in the catch, it proves that the onClose method did not complete the execution. Fix the error so that it can make it to the end of the execution, and you can call the `onDelete` method to delete the instance from memory.

**Comment by LianYangCn** [comment] 2023-08-25 08:05
以下是您提供的文本的翻译：

I have also encountered a similar issue. In a two-level page scenario, the parent page lists many options. When you select one, it takes you to the corresponding child page. However, because the previous child page is not destroyed, it results in navigating to the child page, but it does not display the one you selected; instead, it shows the child page that was selected during the previous visit.
继续翻译：

I haven't used 'onClose'
I only utilized 'onReady', 'Get.toNamed' and 'Get.back'

**Comment by hasibul-hasan-shuvo** [comment] 2023-09-01 09:32
> I have also encountered a similar issue. In a two-level page scenario, the parent page lists many options. When you select one, it takes you to the corresponding child page. However, because the previous child page is not destroyed, it results in navigating to the child page, but it does not display the one you selected; instead, it shows the child page that was selected during the previous visit.
> 
> I haven't used 'onClose' I only utilized 'onReady', 'Get.toNamed' and 'Get.back'

I'm also facing the same issue. any solution on that?

**Comment by rikinpatoliya** [comment] 2023-09-05 06:54
I'm also facing the same issue. controller not delete on back press. I am using the latest version getx 4.6.5

![Screenshot 2023-09-05 122307](https://github.com/jonataslaw/getx/assets/11645604/ec6ccf7d-5a34-4127-bd40-a29507ac0211)

**Comment by dsourav** [comment] 2024-03-31 15:16
use 4.6.6 at least those who are still facing the issue

**Comment by Henriquek47** [comment] 2024-06-18 15:11
I'm still having this problem with version 4.6.6

**Comment by siddheshkatare** [comment] 2024-06-30 15:29
Hey everyone, the issue hasn't been completely resolved yet. I can't find it on mobile (both iOS and Android), but it's present on the web. It doesn't happen every time.
