### ISSUE TITLE
Get.toNamed fullScreenDialog error

### ISSUE THREAD

**Issue by Jethro87** [jonataslaw/getx#335] opened 2020-07-02 18:09 UTC
I was recently using Get 2.14.0, and this problem appeared after upgrading to 3.1.4. It is also present on 3.2.0.

When pushing a fullScreenDialog on top of another fullScreenDialog, this is what happens:

![RPReplay_Final1593712675](https://user-images.githubusercontent.com/6467808/86394485-84877a00-bc53-11ea-9f73-5843d14db226.gif)

It continues to happen if I push more fullScreenDialogs on top of the stack. This does not occur when pushing a fullScreenDialog on top of any other route.

Flutter v1.17.5, stable channel.

Snippet of router file:

```
    GetPage(
      name: Routes.libraryView,
      page: () => LibraryView(),
      fullscreenDialog: true,
    ),
```

Thanks.

**Comment by jonataslaw** [comment] 2020-07-02 18:23
Transitions are now more flexible, before fullScreen did not respect transitions.
Since the default transition on iOS is cupertino, it is being inherited.
You can define the transition you want, such as: Transitions.fadeIn.

But I obviously want the transition experience to be the best possible, so I will make the default transition to fullscreen even on iOS, not be the cupertino animation, because it doesn't look very cool.
But this is not a bug, however it will be improved in the future.

**Comment by Jethro87** [comment] 2020-07-02 19:10
Sorry, you did see the big black squares appear on the Reset Password view, right?

Playing around, I see that the black squares go away when I specify a transition, like:

```
    GetPage(
      name: Routes.libraryView,
      page: () => LibraryView(),
      fullscreenDialog: true,
      transition: Transition.cupertino,
    ),
```

But I simply want the old, fullScreen transition that was working fine on 2.14.0. 

If I have to specify a transition on my fullScreen routes to remove the janky black squares, which one should I select that Get was using previously for fullScreen routes?

**Comment by jonataslaw** [comment] 2020-07-02 19:14
transition: Transition.fade,

Transitions.cupertino is the problem.

**Comment by jonataslaw** [comment] 2020-07-02 19:17
Just to make it clear, in the past dialog was a fade transition, and could not be changed.
You can now change to whatever you want.
The cupertino transition has two steps, and since there is no page behind the first view, it displays this black.
Changing the transition to fade or any other (other than cupertino) should do the trick.

**Comment by Jethro87** [comment] 2020-07-02 22:27
Thanks for your quick responses.

To be honest, this still feels unintuitive. It's not obvious to me that pushing one fullScreenDialog on top of another while using an iOS device will cause such a problem - perhaps this should be documented so others don't come across it?

Also, Transition.fade is not what I'm looking for. I simply want the cupertino-style bottom-to-top transition when pushing a fullScreenDialog / route on my stack. 

It seems to me that I now have to recreate the iOS full screen dialog transition animation myself using properties on GetPage, **only** on fullScreen routes that are themselves above other fullScreen routes.

Am I overcomplicating this somehow?

**Comment by jonataslaw** [comment] 2020-07-02 23:08
> Thanks for your quick responses.
> 
> To be honest, this still feels unintuitive. It's not obvious to me that pushing one fullScreenDialog on top of another while using an iOS device will cause such a problem - perhaps this should be documented so others don't come across it?
> 
> Also, Transition.fade is not what I'm looking for. I simply want the cupertino-style bottom-to-top transition when pushing a fullScreenDialog / route on my stack.
> 
> It seems to me that I now have to recreate the iOS full screen dialog transition animation myself using properties on GetPage, **only** on fullScreen routes that are themselves above other fullScreen routes.
> 
> Am I overcomplicating this somehow?

The point is that we are using the Flutter default now.
It used to be self-employed, and I'm surprised that using Theme.of(context).pageTransitionsTheme.buildTransitions() can do that.
I honestly don't know why Flutter plays a black screen behind the route.
Does setting opaque to true/false change anything for you?

**Comment by Jethro87** [comment] 2020-07-03 00:35
Opaque doesn't change anything.

Ok, thanks for explaining things. I'll have to see about creating the transition I want using GetPage.

**Comment by jonataslaw** [comment] 2020-07-03 15:21
This should no longer happen in version 3.2.1
Closing this

**Closed by jonataslaw** 2020-07-03 15:21 UTC

**Comment by canyonwan** [comment] 2021-11-18 06:11
![image](https://user-images.githubusercontent.com/17877692/142361858-d23c4daa-25ce-4caa-befd-1d9133b57a61.png)
I have the same problem, you can see this snapshot image can resolve this problem
