### ISSUE TITLE
ConsumerX(e.g. Consumer2 in Provider) alternate in GetX

### ISSUE THREAD

**Issue by jitendrapurohit12** [jonataslaw/getx#686] opened 2020-10-07 10:34 UTC
**Is your feature request related to a problem? Please describe.**
Im planning to use GetX in my production apps but i have a question.
Sometimes a widget depends upon two consumers,

```
Consumer2<Notifier1, Notifier2>(
      builder: (_, notifier1, notifier2, __) {
        return Container();
});
```

i want to know, what is its alternate in GetX.

**Comment by jitendrapurohit12** [comment] 2020-10-07 10:38
Im planning to use GetX in my production apps but i have a question.
Sometimes a widget depends upon two consumers,

```
Consumer2<Notifier1, Notifier2>(
      builder: (_, notifier1, notifier2, __) {
        return Container();
});
```

i want to know, what is its alternate in GetX.

**Comment by eduardoflorence** [comment] 2020-10-07 13:57
Duplicate of #525

**Comment by Nipodemos** [comment] 2020-10-07 14:09
Please remember to always use the issue template. It helps us understand your problem and in almost all cases help us solve it faster
Unfortunaly we don't have a Widget like that, you have two options here:

* Using the simple state manager, GetBuilder:
This is you have no choice, you have to nest one GetBuilder for each controller you'll use.

```dart
GetBuilder<Controller1>(
  builder: (controller1) => GetBuilder<Controller2>(
    builder: (controller2) => Container(
      child: Text(controller.someString + anotherController.otherValue),
    ),
  )
)
```
* Using the reactive state manager, GetX:

In this case is very easy, you just use Obx:

```dart
Controller controller = Get.put(Controller1());
AnotherController anotherController = Get.put(AnotherController());

@override
Widget build(BuildContext context) {
  return Container(
    child: Obx(
      () => Text(controller.someString + anotherController.otherValue)
    )
  )
}
```

As this is a question and is duplicate, i'm closing

**Closed by Nipodemos** 2020-10-07 14:09 UTC
