### ISSUE TITLE
An exception occurred while running example_nav2

### ISSUE THREAD

**Issue by shirlay-Chang** [jonataslaw/getx#1994] opened 2021-11-18 10:39 UTC
I try to run command “flutter run -d mydeviceid” in folder example_nav2.
but I got the following exception：

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder:
Navigator.onGenerateRoute returned null when requested to build route "/".

The onGenerateRoute callback must never return null, unless an onUnknownRoute callback is provided as well.
The Navigator was: NavigatorState#6c4f4(lifecycle state: initialized)
...
...
```

I replace GetRouterOutlet by an empty Container  in "lib/app/modules/root/views/root_view.dart",then the exception is gone.
```
body: Container(),
// body: GetRouterOutlet(
//   initialRoute: Routes.HOME,
//   // anchorRoute: '/',
//   // filterPages: (afterAnchor) {
//   //   return afterAnchor.take(1);
//   // },
// ),
```
but I do not konw how to fix the exception while  still using GetRouterOutlet.

**Comment by tonyhart7** [comment] 2021-11-20 16:08
dnt use navigation 2.0 its still buggy as hell on getx

**Comment by wilz05** [comment] 2021-11-21 08:10
Same here.. hoping for the quick fixes !!

**Comment by ahmednfwela** [comment] 2021-11-21 08:11
use my branch instead for now : https://github.com/Bdaya-Dev/getx

**Comment by ahmednfwela** [comment] 2021-11-21 08:12
> dnt use navigation 2.0 its still buggy as hell on getx

it's not that it's buggy, it's just that none of the PRs I make to fix this get merged

**Comment by wilz05** [comment] 2021-11-21 17:40
@ahmednfwela  thanks for the above branch, Do you have any detailed wiki (Documentation) link for GetRouterOutlet in nav 2.0

**Comment by ahmednfwela** [comment] 2021-11-22 07:16
> @ahmednfwela thanks for the above branch, Do you have any detailed wiki (Documentation) link for GetRouterOutlet in nav 2.0

Not yet unfortunately, I haven't found the time yet to add documentation, also I am working on some extra features that might change the API, like route-based dependencies

**Comment by wilz05** [comment] 2021-11-23 05:01
> Not yet unfortunately, I haven't found the time yet to add documentation, also I am working on some extra features that might change the API, like route-based dependencies

Oh okay, Getx is a great package, mainly Nav2 missing some features and detailed doc.
 it will be helpful for many developers.

**Comment by q876625596** [comment] 2021-11-26 09:20
> 暂时使用我的分支：[https](https://github.com/Bdaya-Dev/getx) : [//github.com/Bdaya-Dev/getx](https://github.com/Bdaya-Dev/getx)
Hi，Nav2's Get.Rootdelegate.toname seem to delete the upper level route. When will this problem be resolved

**Comment by ahmednfwela** [comment] 2021-11-26 09:42
@q876625596 this is intended behavior depending on how you structure your routes

create a new issue with example and I will try to help

**Comment by jonataslaw** [comment] 2021-11-26 23:17
fixed

**Closed by jonataslaw** 2021-11-26 23:17 UTC
