### ISSUE TITLE
Sample App | Showing capability of Get

### ISSUE THREAD

**Issue by NiranjanShah** [jonataslaw/getx#282] opened 2020-06-23 07:17 UTC
It is high time, that the GET capability is shown by the way of example. Request the Flutter masters to assist in documenting and creating sample app to show the capability of every GET functions.

This will make developers like me to utilise the Get capability with confidence and understanding.

Kindly kindly do the needful to make sample app with documentation.

**Comment by Katekko** [comment] 2020-06-23 11:37
> It is high time, that the GET capability is shown by the way of example. Request the Flutter masters to assist in documenting and creating sample app to show the capability of every GET functions.
> 
> This will make developers like me to utilise the Get capability with confidence and understanding.
> 
> Kindly kindly do the needful to make sample app with documentation.



I made a project to show the statemanament and routes from Get. If you have any question about or wanna help in something, feel free to ask in my discord. I created to help somepeople in Get/Flutter.

https://discord.gg/bb88Bud

**Comment by joanofdart** [comment] 2020-06-23 15:11
Hey @Katekko 
First of all, thank you for doing this :)
Second of all, you're following a clean architecture style, could we possibly have more of a simpler solution? or do you recommend doing this approach?

**Comment by Katekko** [comment] 2020-06-23 17:02
> Hey @Katekko
> First of all, thank you for doing this :)
> Second of all, you're following a clean architecture style, could we possibly have more of a simpler solution? or do you recommend doing this approach?

I'm trying to use this approach for all my projects. Yes, its seems overkill sometimes....

Only depends of your app complexity. I strongly recommend try to fit that arch in your projects.
But yes, there is some others approach, less complicated

Come to my discord, I can help you if you need

**Comment by jonataslaw** [comment] 2020-06-26 16:59
I am going to do this, and also open a public repository where users can submit models.
But this issue is a duplicate of: https://github.com/jonataslaw/getx/issues/290
So I'm closing this to keep the discussion on the previous issue.

**Closed by jonataslaw** 2020-06-26 16:59 UTC
