### ISSUE TITLE
Asynchronous instance with Get.putAsync

### ISSUE THREAD

**Issue by Dn-a** [jonataslaw/getx#555] opened 2020-09-03 11:32 UTC
hi, I tried to implement an asynchronous instance
```dart
Get.putAsync<SharedPreferences>(() async {
  final prefs = await SharedPreferences.getInstance();
  await prefs.setInt('counter', 12345);
  return prefs;
});
.
.
int count = Get.find<SharedPreferences>().getInt('counter');
print(count); // out: 12345
```
but when I run it, I get this error:
```
"SharedPreferences" not found. You need to call "Get.put(SharedPreferences())" or
"Get.lazyPut(()=>SharedPreferences())"
```

could you please provide a complete example? It would be useful to provide it in the example app. Thanks

**Comment by jonataslaw** [comment] 2020-09-03 12:42
```dart
await Get.putAsync<SharedPreferences>(() async {
  final prefs = await SharedPreferences.getInstance();
  await prefs.setInt('counter', 12345);
  return prefs;
});
```
As it is an asynchronous operation, it goes to the end of the stack, so you have to wait, and usually insert this into main.dart.

**Comment by indiepaul** [comment] 2020-09-04 16:57
How do you achieve this with bindings? 
I have a one dependency that needs async initialization and then another that depends on the first.

```dart
class AppBinding extends Bindings {
  @override
  Future<void> dependencies() async {
    await Get.putAsync<AuthController>(() async {
      final authController = AuthController();
      await authController.initialize();
      return authController;
    });
    Get.put(Client(accessToken: Get.find<AuthController>().token.value));
  }
}
```

When I do this the build method runs before the binding is complete. So the dependencies are null

**Comment by Nipodemos** [comment] 2020-09-04 17:06
`Get.putAsync` returns the instantiated class, so you can simply wait for the future:

```dart
class AppBinding extends Bindings {
  @override
  Future<void> dependencies() async {
    final instantiatedAuthController = await Get.putAsync<AuthController>(() async {
      final authController = AuthController();
      await authController.initialize();
      return authController;
    });
    Get.put(Client(accessToken: instantiatedAuthController.token.value));
  }
}
```

**Comment by indiepaul** [comment] 2020-09-04 17:14
The issue is not the instance in the dependencies method but when I want to access it elsewhere in the app
When I say Get.find<Client>() I get 
`"Client" not found. You need to call "Get.put(Client())" or "Get.lazyPut(()=> Client())"`

**Comment by jonataslaw** [comment] 2020-09-04 17:32
Asynchronous dependencies must be resolved in the main.dart 

```
void main() async {
WidgetsFlutterBinding.ensureInitialized();
AppBinding().dependencies();
```

Flutter (still) does not allow asynchronous events between clicking on a route and building it.

**Comment by indiepaul** [comment] 2020-09-04 17:46
Thanks, that works. Just had to await the call
`await AppBinding().dependencies();`

**Comment by jonataslaw** [comment] 2020-09-04 17:49
> Thanks, that works. Just had to await the call
> `await AppBinding().dependencies();`

I hope that in the future there is a better way to do this, but once the problem has been solved I am closing it.

**Closed by jonataslaw** 2020-09-04 17:49 UTC

**Comment by BobFactory** [comment] 2020-09-23 05:48
Thanks for this answer, But I think we need to explain more regarding these kinds of stuff in the documentation. Especially if we want to create a global depenedemcy using the Bindings. LIke I want to create a Dao instance that needs to be singleton and I want it to be initialized at the app level, since I want my first route to be able to interact with it at the start of it. This provides a single dependency definition pattern that most languages use (Similar to the get_it package). 

Even if the single dependency definition is not possible since I read the bindings are bind during the route is called, creating a doc for explaining such behaviour would be great. 

Also putAsync is heavily under explained in the docs. Whereas async operations are abundant in a dev's life.
