### ISSUE TITLE
Get.arguments is Null

### ISSUE THREAD

**Issue by zl910627** [jonataslaw/getx#676] opened 2020-10-02 13:39 UTC
- Reproduce case

* arrived fcm notification while app is in foreground / background
* parse payload then route by `Get.toNamed(route, arguments: parsed);`
* `Get.arguments` is null on target page.

Would you please fix this ?

**Comment by jonataslaw** [comment] 2020-10-02 13:56
![image](https://user-images.githubusercontent.com/35742643/94931001-991b1e80-049d-11eb-8b99-9b9c62e9521d.png)

Please do not delete and follow the script for opening issues. For support questions, use the community channels.
Closing for disrespecting the issue opening model.

**Comment by zl910627** [comment] 2020-10-02 14:36
Do you understand issue?
Which kind code do you think good for this report?

**Comment by jonataslaw** [comment] 2020-10-02 14:45
I have exactly the same use case, and for me the arguments are never null. If in your case it is null, you are certainly doing something wrong, or if you think this is in fact an error, you must provide a reproduction code (a self-executing code that demonstrates when the error occurs).
There is no way to identify behavior without code, just telling what happens to you.

**Comment by zl910627** [comment] 2020-10-02 14:48
Which sample code do you mean?
Let me try with your code.

**Comment by zl910627** [comment] 2020-10-02 15:08
1. at fcm callback
![image](https://user-images.githubusercontent.com/53897531/94938655-b5ea3d00-0503-11eb-93d5-ff49fd54b6e6.png)

2. at binding
![image](https://user-images.githubusercontent.com/53897531/94939009-22fdd280-0504-11eb-8909-afd320d62bc6.png)

3. at controller
![image](https://user-images.githubusercontent.com/53897531/94938841-f5b12480-0503-11eb-8b55-e020e1fcb183.png)

**Comment by zl910627** [comment] 2020-10-02 15:09
Please look above.

**Comment by zl910627** [comment] 2020-10-02 15:10
![Uploading image.png…]()

**Comment by jonataslaw** [comment] 2020-10-02 15:17
1- Check if "playlist" is not null, print it. 
Playlist.fromJson can to return null, so playlist can be null. 
2- How is your routes? Are you using getPages?

**Comment by zl910627** [comment] 2020-10-02 15:25
I am using Get cli (not clean architecture.)
I am creating view / controller using `get create view:playlist`
![image](https://user-images.githubusercontent.com/53897531/94940320-ed59e900-0505-11eb-9580-481cea8ba879.png)

Here is print of playlist at fcm callback.
![Uploading image.png…]()

**Comment by zl910627** [comment] 2020-10-02 15:29
PS: `gf<T>() = Get.find<T>()` and `PlaylistStore` is subclass of `GetxService`

**Comment by zl910627** [comment] 2020-10-04 12:19
Hello @jonataslaw 
Now, my 3 projects needs this issue to be solved.
May I ask any update about this ?

**Comment by roipeker** [comment] 2020-10-06 20:56
@zl910627  would you mind providing a little more info?
- Are you using the latest version of GetX? 
- Which Flutter version/branch?
- If you pass  ANY other argument to `Get.toNamed()`, say `Get.toNamed(Routes.PLAYLIST, arguments: 3)`. And in `PlaylistController::onReady()` you `print( Get.arguments );`, what's the output?
Regarding the case, the usage of `Get.lazyPut()` in a Binding might cause potential problems (I know that's get_cli i generating the templates) ... but if you are relying on Controller's lifecycle, which apparently u are, and using something like `GetView<Controller>` the call to `Get.find()` might not happen, and the controller will never get loaded in memory.
So, I advise you to play safe, and use `Get.put()` in your binding.

Anyway, let me know your finding passing other type of hardcoded arguments please.

**Comment by zl910627** [comment] 2020-10-07 01:53
1. Yes, due I am crazy fan of `GetX`, I am always using latest version - `3.12.1`
2. Please check above messages.
Latest stable flutter used.
![](https://user-images.githubusercontent.com/53897531/94939406-ab7c7300-0504-11eb-8924-6996738827d8.png)
3. 3 poins - `null` when `constructor`, `onInit` and even `onReady` .
4. at `bindings`, I tried to replace `lazyPut` with `put`. But nothing changed.
thank you.

**Comment by Darksoulsong** [comment] 2020-11-14 09:40
Same issue here. My setup is very alike OP's, and I'm unable to use `Get.arguments` on the controller.

I tried to replace `lazyPut `with put, and `print(Get.arguments)` is null when called on `onInit `and `onReady`.

Get version: ^3.16.0
Dart: 2.10.3
Flutter 1.22.3

**Comment by eduardoflorence** [comment] 2020-11-14 15:10
@zl910627 and @Darksoulsong, I know it's not possible to share all of our code, but to prove that there is a bug you need to isolate the problem in a test code, so we just need to copy, paste and run.
I made the sample code below and there is no problem with passing the argument. Feel free to change this code and try to reproduce your problem.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(
    initialRoute: '/home',
    getPages: [
      GetPage(
        name: '/home',
        page: () => HomePage(),
      ),
      GetPage(
        name: '/login',
        page: () => LoginPage(),
        binding: LoginBinding(),
      ),
    ],
  ));
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('HOME')),
      body: Center(
        child: RaisedButton(
          onPressed: () => Get.toNamed('/login', arguments: {"name": "test"}),
          child: Text('Login'),
        ),
      ),
    );
  }
}

class LoginBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => LoginController());
  }
}

class LoginController extends GetxController {
  final title = 'Login';
  @override
  void onInit() {
    print('Arguments: ${Get.arguments}');
    super.onInit();
  }
}

class LoginPage extends GetView<LoginController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(controller.title)),
      body: Container(),
    );
  }
}
```

![image](https://user-images.githubusercontent.com/9120528/99150267-02cc4200-2672-11eb-861a-7887868a3a30.png)

**Comment by Darksoulsong** [comment] 2020-11-15 09:49
@eduardoflorence Thanks for your reply. 

I isolated the relevant parts of my code to reproduce the bug. Please, take a look: https://github.com/Darksoulsong/gettest

Once the page gets loaded, press the "Go to details" button, I expect you to see a failed assertion.

There's a minor difference in my page definition and yours, as you are extending GetView. But I replaced the StatelessWidget with GetView and the issue is still there, that is, I'm still unable to access the arguments from the controller.

Thank you.

**Comment by Darksoulsong** [comment] 2020-11-16 08:45
Sorry guys, it was a mistake from my side. I was trying to access query parameters from Get.arguments when I should be using Get.parameters.

**Comment by eduardoflorence** [comment] 2020-11-16 09:13
@zl910627 can we clode this issue?

**Comment by zl910627** [comment] 2020-11-16 10:50
I am not sure this is fixed or not.
Let's close for now, and would we open it if not fixed ?

**Comment by eduardoflorence** [comment] 2020-11-16 11:05
> @ zl910627 e @Darksoulsong , sei que não é possível compartilhar todo o nosso código, mas para provar que existe um bug você precisa isolar o problema em um código de teste, então só precisamos copiar, colar e executar.
> Fiz o código de exemplo abaixo e não há problema em passar o argumento. Sinta-se à vontade para alterar este código e tentar reproduzir o seu problema.
> 
@zl910627, we were unable to reproduce the issue you mentioned. I put a code above to demonstrate. Is the problem still with you? If yes, provide a valid code so that we can test.

**Comment by zl910627** [comment] 2020-11-16 13:45
> 
> 
> > @ zl910627 e @Darksoulsong , sei que não é possível compartilhar todo o nosso código, mas para provar que existe um bug você precisa isolar o problema em um código de teste, então só precisamos copiar, colar e executar.
> > Fiz o código de exemplo abaixo e não há problema em passar o argumento. Sinta-se à vontade para alterar este código e tentar reproduzir o seu problema.
> 
> @zl910627, we were unable to reproduce the issue you mentioned. I put a code above to demonstrate. Is the problem still with you? If yes, provide a valid code so that we can test.

Thank you for your great support.
I will let you know once i need to fix this again.

**Closed** 2020-11-16 13:44 UTC
Labels: More info is needed, Waiting for customer response

**Comment by zl910627** [comment] 2020-11-16 13:47
I have already completed 3 project by using sharepreference.

**Comment by SmarterVision** [comment] 2020-11-24 11:22
> @zl910627 and @Darksoulsong, I know it's not possible to share all of our code, but to prove that there is a bug you need to isolate the problem in a test code, so we just need to copy, paste and run.
> I made the sample code below and there is no problem with passing the argument. Feel free to change this code and try to reproduce your problem.
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:get/get.dart';
> 
> void main() {
>   runApp(GetMaterialApp(
>     initialRoute: '/home',
>     getPages: [
>       GetPage(
>         name: '/home',
>         page: () => HomePage(),
>       ),
>       GetPage(
>         name: '/login',
>         page: () => LoginPage(),
>         binding: LoginBinding(),
>       ),
>     ],
>   ));
> }
> 
> class HomePage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text('HOME')),
>       body: Center(
>         child: RaisedButton(
>           onPressed: () => Get.toNamed('/login', arguments: {"name": "test"}),
>           child: Text('Login'),
>         ),
>       ),
>     );
>   }
> }
> 
> class LoginBinding extends Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut(() => LoginController());
>   }
> }
> 
> class LoginController extends GetxController {
>   final title = 'Login';
>   @override
>   void onInit() {
>     print('Arguments: ${Get.arguments}');
>     super.onInit();
>   }
> }
> 
> class LoginPage extends GetView<LoginController> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text(controller.title)),
>       body: Container(),
>     );
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/9120528/99150267-02cc4200-2672-11eb-861a-7887868a3a30.png)

The problem when the `loginController` already initialized `onInit()` method not invoked, How to get the `Get.arguments` in the controller,

Thank you for your support!

**Comment by zl910627** [comment] 2020-11-24 11:34
https://github.com/jonataslaw/getx/issues/676#issuecomment-702789004
https://github.com/jonataslaw/getx/issues/676#issuecomment-702798493
Above articles are enough answer for your question, I guess

**Comment by eduardoflorence** [comment] 2020-11-25 19:56
@SmarterVision, please open a new issue and provide a code that we can reproduce your problem.

**Comment by DharmaTech123** [comment] 2020-11-30 18:35
> 1. at fcm callback
>    ![image](https://user-images.githubusercontent.com/53897531/94938655-b5ea3d00-0503-11eb-93d5-ff49fd54b6e6.png)
> 2. at binding
>    ![image](https://user-images.githubusercontent.com/53897531/94939009-22fdd280-0504-11eb-8909-afd320d62bc6.png)
> 3. at controller
>    ![image](https://user-images.githubusercontent.com/53897531/94938841-f5b12480-0503-11eb-8b55-e020e1fcb183.png)
> 4. result for `flutter doctor`
>    ![image](https://user-images.githubusercontent.com/53897531/94939406-ab7c7300-0504-11eb-8924-6996738827d8.png)

You don't have to mention type in lazyPut, the one in angular brackets, lazy put worked for me. I was facing the same issue earlier.

**Comment by pqtrong17** [comment] 2021-01-26 08:57
@jonataslaw Sorry, I get an error when I pass data.
I pass from A page:
```
Get.to(BPage(), arguments: "Pass from A page");
```
and get data from B:
```
print("${Get.arguments)}";
```
My issue is I just get data ok at first time, but second time -> Data is null. Why, bro?
Note: I didn't exit B page while calling print();

**Comment by pqtrong17** [comment] 2021-01-28 04:44
> > 1. at fcm callback
> >    ![image](https://user-images.githubusercontent.com/53897531/94938655-b5ea3d00-0503-11eb-93d5-ff49fd54b6e6.png)
> > 2. at binding
> >    ![image](https://user-images.githubusercontent.com/53897531/94939009-22fdd280-0504-11eb-8909-afd320d62bc6.png)
> > 3. at controller
> >    ![image](https://user-images.githubusercontent.com/53897531/94938841-f5b12480-0503-11eb-8b55-e020e1fcb183.png)
> > 4. result for `flutter doctor`
> >    ![image](https://user-images.githubusercontent.com/53897531/94939406-ab7c7300-0504-11eb-8924-6996738827d8.png)
> 
> You don't have to mention type in lazyPut, the one in angular brackets, lazy put worked for me. I was facing the same issue earlier.

How to you solve this issue?

**Comment by hufu4635** [comment] 2021-03-17 13:04
> > > 1. at fcm callback
> > >    ![image](https://user-images.githubusercontent.com/53897531/94938655-b5ea3d00-0503-11eb-93d5-ff49fd54b6e6.png)
> > > 2. at binding
> > >    ![image](https://user-images.githubusercontent.com/53897531/94939009-22fdd280-0504-11eb-8909-afd320d62bc6.png)
> > > 3. at controller
> > >    ![image](https://user-images.githubusercontent.com/53897531/94938841-f5b12480-0503-11eb-8b55-e020e1fcb183.png)
> > > 4. result for `flutter doctor`
> > >    ![image](https://user-images.githubusercontent.com/53897531/94939406-ab7c7300-0504-11eb-8924-6996738827d8.png)
> > 
> > 
> > You don't have to mention type in lazyPut, the one in angular brackets, lazy put worked for me. I was facing the same issue earlier.
> 
> How to you solve this issue?
I had the same problem.
You can try to use it in the onReady method Get.arguments.

**Comment by edgarfroes** [comment] 2021-04-11 04:32
I can reproduce this error, but only when I show a snackBar "in the same thread" as the `Get.toNamed`, both at the same time. The code can be found in my GitHub: https://github.com/edgarfroes/getx_arguments_null_error

**Comment by ThangVuNguyenViet** [comment] 2021-08-18 07:06
I have the similar issue too. Initially I can get the argument too. But after I call setState method, the argument turned to null.

**Comment by chenasraf** [comment] 2021-09-12 21:37
Also getting this issue, don't understand how this hasn't been solved in so long.

**Comment by Albertbol** [comment] 2021-11-02 17:02
Same here the first time I get it it's not null, then it is.

**Comment by Ali-Azmoud** [comment] 2021-11-19 20:40
Same here, and to solve this issue, I put the value of `Get.arguments` into another variable in `onInit` method of the controller of the page.

**Comment by tva77** [comment] 2022-02-11 18:26
take a look at my solution to nested navigation using getx
https://github.com/tva77/getx_persistent_bottombar

**Comment by Limvunhoy** [comment] 2022-04-06 03:45
> I can reproduce this error, but only when I show a snackBar "in the same thread" as the `Get.toNamed`, both at the same time. The reproduceable code can be found in my GitHub: https://github.com/edgarfroes/getx_arguments_null_error

I face that issue too, may I know is there any solution for that?

**Comment by chandrabezzo** [comment] 2022-04-21 07:45
Same here, but I can only reproduce if running at Android.

**Comment by NTA-trongpq** [comment] 2022-11-04 01:52
Any solution?

**Comment by ghifariakbar01** [comment] 2023-02-02 12:14
Avoid using Get.dialog. Getx is a buggy mess, guys.

**Comment by ghifariakbar01** [comment] 2023-02-02 12:14
Try riverpod, it's recommended by flutter.

**Comment by luiszheng0627** [comment] 2023-02-02 14:30
Dear GETX.
I understand it is hard to reproduction the issue and fix it properly.
But I am still your fan, and hope you solve this.
Love to use you.
Thank you.

**Comment by oliverbytes** [comment] 2025-03-27 10:10
This issue is still present in GetX 5 unfortunately. I hope there can be a solution
