### ISSUE TITLE
Feature: Compile-safe get

### ISSUE THREAD

**Issue by jascodes** [jonataslaw/getx#651] opened 2020-09-26 19:33 UTC
Hey @jonataslaw 

Comeup with a way to make get compile safe like https://pub.dev/packages/riverpod

PS: Awesome work!!
Thx

**Comment by jonataslaw** [comment] 2020-09-27 02:55
Duplicate of https://github.com/jonataslaw/getx/issues/450

**Closed by jonataslaw** 2020-09-27 02:55 UTC
