### ISSUE TITLE
Weird behaviour of FullLifeCycleController when requesting permissions

### ISSUE THREAD

**Issue by ur-uw** [jonataslaw/getx#1490] opened 2021-05-28 04:14 UTC
**Weird behaviour of FullLifeCycleController when requesting permissions to access device services (Android to be specifice)**

**Describe the bug**
Im using [https://pub.dev/packages/permission_handler](permission_handler) package to request permissions.
When I try to request a specific permission from the user and the request get denied like when the response of permission_handler is `!PermissionStatus.isGranted` wether it is `denied || permanentlyDenied` an infinite loop will occur
when using the same function that requests the permission in `onResume` life cycle method.

**Reproduction code

```dart
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:get/get.dart';
import 'package:permission_handler/permission_handler.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Life cycle issue',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      getPages: [
        GetPage(
          name: '/',
          binding: BindingsBuilder.put(() => FullContoller()),
          page: () => MyHomePage(),
        ),
      ],
      initialRoute: '/',
    );
  }
}

class MyHomePage extends GetView<FullContoller> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GetBuilder<FullContoller>(builder: (_) {
        return Center(
          child: controller.shoePermRequest
              ? Icon(Icons.error, color: Colors.red)
              : Text(controller.userPostion.toString()),
        );
      }),
    );
  }
}

class FullContoller extends FullLifeCycleController with FullLifeCycle {
  bool _showPermRequest = false;
  Position? userPostion;
  bool get shoePermRequest => _showPermRequest;

  ///Reques user permission to device location
  Future<PermissionStatus> getPermission() async {
    PermissionStatus status = await Permission.location.status;
    if (!status.isGranted && !status.isPermanentlyDenied) {
      PermissionStatus requestNewStatus = await Permission.location.request();
      return requestNewStatus;
    }
    return status;
  }

  ///Implemenet geting location
  getUserLocation() async {
    PermissionStatus locationStatus = await getPermission();
    switch (locationStatus) {
      case PermissionStatus.granted:
        userPostion = await GeolocatorPlatform.instance.getCurrentPosition();
        update();
        break;
      default:
        print('Not granted');
        Get.snackbar('Not Granted', 'Please allow access to device location');
        _showPermRequest = true;
        update();
        break;
    }
  }

  @override
  void onReady() {
    getUserLocation();
    super.onReady();
  }

  @override
  void onDetached() {
    // TODO: implement onDetached
  }

  @override
  void onInactive() {
    // TODO: implement onInactive
  }

  @override
  void onPaused() {
    // TODO: implement onPaused
  }

  @override
  void onResumed() {
    getUserLocation();
  }
}

```

**To Reproduce**
1. Install get, permission_handler and geolocator packages
2. Add the required permissions to AndroidMainfest.xml _Location used above_
3. Try the above code with permissions specified in step 2 **Call the request to your permission in `onResume` method**
4. Deny the permission request
5. See the infinite loop by printing a statement , testing or using snackbar like I did

**Expected behavior**
Expected the `onResume` to be called only when the app comes from background, I tried the same code on IOS and I think it's fine
**Screenshots**

https://user-images.githubusercontent.com/16156658/119928208-cdd76b00-bf83-11eb-99e4-3310a4786359.mp4

![Screenshot_1622174774](https://user-images.githubusercontent.com/16156658/119928222-d3cd4c00-bf83-11eb-9387-77a5f8590f7e.png)

**Flutter Version:**
- 2.2.0

**Getx Version:**
- 4.1.4

**Describe on which device you found the bug:**
- Samsung galaxy S9
- Android studio emulator

**Minimal reproduce code**
[   +1 ms] An Observatory debugger and profiler on sdk gphone arm64 is available at: http://127.0.0.1:56315/Uox8sNfpd8Y=/
[   +7 ms] I/flutter ( 5505): Not granted
[  +43 ms] I/flutter ( 5505): Not granted
[  +85 ms] I/flutter ( 5505): Not granted
[  +56 ms] I/flutter ( 5505): Not granted
[  +51 ms] I/flutter ( 5505): Not granted
[  +50 ms] I/flutter ( 5505): Not granted
[  +63 ms] I/flutter ( 5505): Not granted
[  +41 ms] I/flutter ( 5505): Not granted
[  +59 ms] I/flutter ( 5505): Not granted
[  +41 ms] I/flutter ( 5505): Not granted
[  +76 ms] I/flutter ( 5505): Not granted
[  +66 ms] I/flutter ( 5505): Not granted
[  +51 ms] I/flutter ( 5505): Not granted
[  +47 ms] I/flutter ( 5505): Not granted
[  +41 ms] I/flutter ( 5505): Not granted
[  +80 ms] I/flutter ( 5505): Not granted
[  +86 ms] I/flutter ( 5505): Not granted
[  +61 ms] I/flutter ( 5505): Not granted
[  +38 ms] I/flutter ( 5505): Not granted
[  +79 ms] I/flutter ( 5505): Not granted
[  +48 ms] I/flutter ( 5505): Not granted
[  +39 ms] I/flutter ( 5505): Not granted
[ +108 ms] I/flutter ( 5505): Not granted
[  +52 ms] I/flutter ( 5505): Not granted
[  +53 ms] I/flutter ( 5505): Not granted
[  +72 ms] I/flutter ( 5505): Not granted
[  +14 ms] The Flutter DevTools debugger and profiler on sdk gphone arm64 is available at: http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A56315%2FUox8sNfpd8Y%3D%2F
[  +43 ms] I/flutter ( 5505): Not granted
[  +50 ms] I/flutter ( 5505): Not granted
[  +54 ms] I/flutter ( 5505): Not granted
[  +39 ms] I/flutter ( 5505): Not granted
[  +53 ms] I/flutter ( 5505): Not granted
[  +86 ms] I/flutter ( 5505): Not granted
[  +55 ms] I/flutter ( 5505): Not granted
[  +89 ms] I/flutter ( 5505): Not granted
[  +51 ms] I/flutter ( 5505): Not granted
[  +31 ms] I/flutter ( 5505): Not granted
[  +72 ms] I/flutter ( 5505): Not granted
[  +83 ms] I/flutter ( 5505): Not granted
[  +48 ms] I/flutter ( 5505): Not granted
[  +61 ms] I/flutter ( 5505): Not granted
[  +58 ms] I/flutter ( 5505): Not granted
[  +55 ms] I/flutter ( 5505): Not granted
[  +91 ms] I/flutter ( 5505): Not granted
[  +47 ms] I/flutter ( 5505): Not granted
[  +53 ms] I/flutter ( 5505): Not granted
[  +45 ms] I/flutter ( 5505): Not granted
[  +85 ms] I/flutter ( 5505): Not granted
[  +66 ms] I/flutter ( 5505): Not granted
[  +70 ms] I/flutter ( 5505): Not granted
[  +56 ms] I/flutter ( 5505): Not granted
[  +48 ms] I/flutter ( 5505): Not granted
[  +51 ms] I/flutter ( 5505): Not granted
[  +77 ms] I/flutter ( 5505): Not granted
[  +98 ms] I/flutter ( 5505): Not granted
[ +108 ms] I/flutter ( 5505): Not granted
[  +73 ms] I/flutter ( 5505): Not granted
[  +38 ms] I/flutter ( 5505): Not granted
[  +65 ms] I/flutter ( 5505): Not granted
[  +48 ms] I/flutter ( 5505): Not granted
[  +75 ms] I/flutter ( 5505): Not granted
[  +73 ms] I/flutter ( 5505): Not granted
[  +36 ms] I/flutter ( 5505): Not granted
[  +82 ms] I/flutter ( 5505): Not granted
[ +110 ms] I/flutter ( 5505): Not granted
[  +62 ms] I/flutter ( 5505): Not granted
[  +91 ms] I/flutter ( 5505): Not granted
[  +69 ms] I/flutter ( 5505): Not granted
[  +45 ms] I/flutter ( 5505): Not granted
[  +36 ms] I/flutter ( 5505): Not granted
[  +44 ms] I/flutter ( 5505): Not granted
[  +39 ms] I/flutter ( 5505): Not granted
[  +50 ms] I/flutter ( 5505): Not granted
[  +58 ms] I/flutter ( 5505): Not granted
[  +89 ms] I/flutter ( 5505): Not granted
[  +81 ms] I/flutter ( 5505): Not granted
[  +69 ms] I/flutter ( 5505): Not granted
[  +32 ms] I/flutter ( 5505): Not granted
[  +68 ms] I/flutter ( 5505): Not granted
[  +66 ms] I/flutter ( 5505): Not granted
[  +65 ms] I/flutter ( 5505): Not granted
[  +66 ms] I/flutter ( 5505): Not granted
[  +68 ms] I/flutter ( 5505): Not granted
[  +49 ms] I/flutter ( 5505): Not granted
[  +63 ms] I/flutter ( 5505): Not granted
[  +47 ms] I/flutter ( 5505): Not granted
[  +39 ms] I/flutter ( 5505): Not granted
[  +94 ms] I/flutter ( 5505): Not granted
[  +54 ms] I/flutter ( 5505): Not granted
[  +89 ms] I/flutter ( 5505): Not granted
[  +56 ms] I/flutter ( 5505): Not granted
[  +71 ms] I/flutter ( 5505): Not granted
[  +48 ms] I/flutter ( 5505): Not granted
[  +41 ms] I/flutter ( 5505): Not granted
[  +40 ms] I/flutter ( 5505): Not granted
[  +38 ms] I/flutter ( 5505): Not granted
[  +67 ms] I/flutter ( 5505): Not granted
[  +99 ms] I/flutter ( 5505): Not granted
[  +48 ms] I/flutter ( 5505): Not granted
[  +51 ms] I/flutter ( 5505): Not granted
[  +63 ms] I/flutter ( 5505): Not granted
[  +73 ms] I/flutter ( 5505): Not granted
[  +61 ms] I/flutter ( 5505): Not granted
[  +85 ms] I/flutter ( 5505): Not granted
[ +110 ms] I/flutter ( 5505): Not granted

**Comment by jonataslaw** [comment] 2021-05-28 05:01
You are calling getPermissions on onResume which is called whenever the permission dialog is closed and the app is back in the foreground. I'm still trying to understand what's wrong, the infinite loop is exactly the expected behavior for your code snippet.

**Comment by jonataslaw** [comment] 2021-05-28 05:16
Only if I am not clear enough, should you store the permission status, and only ask if the bool is true, otherwise, return. This is how you are sure on the dart side, that FlutterActivity is not in the background. Even though nothing is displayed on the screen, you do not know if the Flutter activity has not been superimposed, and I cannot say this because I cannot look at the source code of a third party package. But the only thing I can say is that this is the expected behavior, onResume is being called because FlutterAcitivity has returned to the foreground.
As this is the expected behavior and the alleged problem is related to another plugin, I am closing this issue.

**Closed by jonataslaw** 2021-05-28 05:16 UTC
Labels: Unrelated to GetX, expected behavior
