### ISSUE TITLE
onClose not working after update 

### ISSUE THREAD

**Issue by Eng-MohamedGadala** [jonataslaw/getx#583] opened 2020-09-09 10:34 UTC
**Describe the bug**
  @override
  onClose{
    SystemChannels.textInput.invokeMethod('TextInput.hide');
  }
not working after upgrade to get: ^3.8.0

**Flutter Version:**
Flutter 1.21.0-9.2.pre • channel beta

**Getx Version:**
get: ^3.8.0

**Minimal reproduce code**
  @override
  onClose{
    SystemChannels.textInput.invokeMethod('TextInput.hide');
  }

**Comment by eduardoflorence** [comment] 2020-09-09 19:30
The new sintax is:

```dart
@override
Future<void> onClose() {
  SystemChannels.textInput.invokeMethod('TextInput.hide');
  return super.onClose();
}
```

**Comment by jonataslaw** [comment] 2020-09-09 19:34
I will change "Future" by FutureOr to prevent sintaxes errors. 
Thanks @eduardoflorence !

**Comment by Eng-MohamedGadala** [comment] 2020-09-09 19:45
`class LoginController extends GetxController {
  AuthProvider authProvider = AuthProvider();
  final RegExp p1 = RegExp(regex.passwordEasy);
  String userName;
  String password;
  bool isUserVerivid;
  bool isUserLogin;
  bool isFormValid;
  String qrCode;
  // List<bool> isSelected = [true, false];
  @override
  onInit() {
    isFormValid = false;
    isUserLogin = false;
    super.onInit();
  }

@override
Future<void> onClose() {
  SystemChannels.textInput.invokeMethod('TextInput.hide');
  return super.onClose();
}`
thanks but it doesn't work   underline red color  in onClose() and   super.onClose(). how can I override onClose in a true way.

**Comment by Eng-MohamedGadala** [comment] 2020-09-09 19:48
![Screen Shot 2020-09-09 at 9 40 59 PM](https://user-images.githubusercontent.com/6634311/92646026-1b248700-f2e6-11ea-95b7-81904fc8ed30.png)

**Comment by Grohden** [comment] 2020-09-09 19:51
@jonataslaw @eduardoflorence 
I'm pretty sure that future is not the return yet.

And void is still accepted (if you're refering to my PR on type analyzer stuff I've used FutureOR, so void is acceptable)

@Eng-MohamedGadala  try using this: (and be sure that the `super.onClose();` is always the latest call):
```dart
  @override
  void onClose() {
    SystemChannels.textInput.invokeMethod('TextInput.hide');
    super.onClose();
  }
```

Do you still get errors with the above signature?

**Comment by Eng-MohamedGadala** [comment] 2020-09-09 19:58
![Screen Shot 2020-09-09 at 9 54 10 PM](https://user-images.githubusercontent.com/6634311/92646657-0b597280-f2e7-11ea-8c08-fd001d5ba815.png)
Thanks but still not working if I change Future to FutureOR only error hide from super.onClose(); but still on onClose()

**Comment by Grohden** [comment] 2020-09-09 20:01
@Eng-MohamedGadala which message is reported to you when you hover your mouse at those red lines?

**Comment by Grohden** [comment] 2020-09-09 20:02
oh, unless I looked at the wrong version:

```dart
  @override
  void onClose() async {
    SystemChannels.textInput.invokeMethod('TextInput.hide');
    super.onClose();
  }
```
hopefully solves it

**Comment by Eng-MohamedGadala** [comment] 2020-09-09 20:04
@Grohden  when hold on super.onClose();

package:get/src/state_manager/simple/get_state.dart

Called before [onDelete] method. [onClose] might be used to dispose resources used by the controller. Like closing events, or streams before the controller is destroyed. Or dispose objects that can potentially create some memory leaks, like TextEditingControllers, AnimationControllers. Might be useful as well to persist some data on disk.

Copied from DisposableInterface.

The expression doesn't evaluate to a function, so it can't be invoked.dartinvocation_of_non_function_expression


No changes after using  this 
```
 @override
  void onClose() async {
    SystemChannels.textInput.invokeMethod('TextInput.hide');
    super.onClose();
  }
```

**Comment by Eng-MohamedGadala** [comment] 2020-09-09 20:07
![Screen Shot 2020-09-09 at 10 07 21 PM](https://user-images.githubusercontent.com/6634311/92647837-de0dc400-f2e8-11ea-8f9f-6cec3e4d743c.png)

**Comment by Grohden** [comment] 2020-09-09 20:18
🤔  maybe a cache on dart analyzer?
@eduardoflorence and @jonataslaw are right about 3.8.0 having only future (I couldn't find the 3.8.0 tag on the repo)

`Future onClose()` is the right signature

```dart
import 'package:flutter/services.dart';
import 'package:get/state_manager.dart';

class LoginController extends GetxController {
  @override
  Future onClose() {
    SystemChannels.textInput.invokeMethod('TextInput.hide');
    return super.onClose();
  }
}
```

Is accepted at my project using exactly 3.8.0 on AS. So I don't have any clue about why your analyzer is reporting errors.

You could try restarting it (if you don't know how, restarting vscode will probably restart the analysis server)

**Comment by Eng-MohamedGadala** [comment] 2020-09-09 20:28
I did everything but not working the only working if I change get version to 3.4.6
![Screen Shot 2020-09-09 at 10 24 05 PM](https://user-images.githubusercontent.com/6634311/92649728-c1bf5680-f2eb-11ea-8e74-21e60401f526.png)
![Screen Shot 2020-09-09 at 10 25 36 PM](https://user-images.githubusercontent.com/6634311/92649735-c4ba4700-f2eb-11ea-8725-38805dd80756.png)

**Comment by jpkontreras** [comment] 2020-09-09 22:12
tested in android studio with latest update

<img width="527" alt="Captura de Pantalla 2020-09-09 a la(s) 19 09 31" src="https://user-images.githubusercontent.com/7862089/92660152-3f756900-f2d0-11ea-960e-cb4d7403c1af.png">

Could be the editor config ?

**Comment by Eng-MohamedGadala** [comment] 2020-09-10 10:00
After using this part of the code no error but not working, onClose not calling any time.
  ```
@override
  Future get onClose async {
    SystemChannels.textInput.invokeMethod('TextInput.hide');
    return super.onClose;
  }
```
After using this part of the code show error and not working. on the android studio on the same project but after creating new project and add the same version on   get: ^3.8.0 
 ```
   @override
  Future onClose()  {
    SystemChannels.textInput.invokeMethod('TextInput.hide');
    return super.onClose();
  }
```
THIS IS MAGIC FOR ME 
after opening GetXController, I Found the reason like the image I add the same get:^3.8.0 in both project's but get_state.dart  file not the same content and version old project 3.8.0 but new project 3.10.1 I don't now reason but that happened 

![Screen Shot 2020-09-10 at 11 43 58 AM](https://user-images.githubusercontent.com/6634311/92714888-10f19f80-f35d-11ea-9b7a-f783f278447c.png)
![Screen Shot 2020-09-10 at 11 45 56 AM](https://user-images.githubusercontent.com/6634311/92714900-1353f980-f35d-11ea-806e-e0b2e3471269.png)

Thank's for everyone to try to help me.

**Comment by jonataslaw** [comment] 2020-09-10 19:45
As I couldn't reproduce this in the last version, I'm closing it.
If you face problems, you can open another issue, or use the platform channels to ask for quick help

**Closed by jonataslaw** 2020-09-10 19:45 UTC
