### ISSUE TITLE
vs code hot reload issue when use GetView<Controller>

### ISSUE THREAD

**Issue by j574144** [jonataslaw/getx#566] opened 2020-09-06 01:06 UTC
**Describe the bug**
When use `GetView<Controller>` the hort reload of vscode launch a warning and you need restart the build to perform current and futures changes:

```shell
Hot reload received invalid response: {type: ReloadReport, success: false, notices: [{type: ReasonForCancellingReload, kind: TypeParametersChanged, class: {type: @Class, fixedId: true, id: classes/1471, name: LoginPage}, message: Limitation: changing type parameters does not work with hot reload.}]}
``` 

**To Reproduce**
1. Add `GetView<Controller>` 
2. Save file changes
3. Warning is launched

**Expected behavior**
Hot reload without any issue

**Screenshots**
![image](https://user-images.githubusercontent.com/30190050/92315948-d978a100-efb2-11ea-8ceb-e4852f8c4e56.png)

**Flutter Version:**
1.20.0

**Getx Version:**
`get: ^3.8.0`

**Describe on which device you found the bug:**
moto g 6 (android-arm).

**Minimal reproduce code**
```dart
class Home extends GetView<Controller> {
  @override
  Widget build(context) => Scaffold(
      appBar: AppBar(title: Text("counter")),
      body: Center(
        child: Obx(() => Text("${controller.counter}")),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: controller.increment,
      ));
}
```

**Comment by jonataslaw** [comment] 2020-09-06 03:53
This is not a package error, this is Flutter saying that there is a problem with the cache that is causing inconsistencies with the hot reload.
Close the project, then use `flutter clean` and build the project again, and everything should work.

**Comment by j574144** [comment] 2020-09-06 21:15
Thanks for your answer but this not solve the problem that only occurs when add GetView.

If you have any suggestion i will be appreciated

**Comment by jonataslaw** [comment] 2020-09-07 09:42
> Thanks for your answer but this not solve the problem that only occurs when add GetView.
> 
> If you have any suggestion i will be appreciated

Unfortunately Hot Reload and the like is not related to this library. If Flutter clean has not resolved, your installation should probably be corrupted. I can't reproduce your problem even on the same device you used.

**Comment by oaugustus** [comment] 2020-10-18 23:21
Same error here. When use GetView, appear the error message:

`Hot reload received invalid response: {type: ReloadReport, success: false, notices: [{type: ReasonForCancellingReload, kind: TypeParametersChanged, class: {type: @Class, fixedId: true, id: classes/1496, name: LoginScreen}, message: Limitation: changing type parameters does not work with hot reload.}]}`

Flutter clean doesn't work for me.

If I change GetView to Stateless with a single controller works normally.

````
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.14.6 18G87, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.49.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by Nipodemos** [comment] 2020-10-19 00:16
> Same error here. When use GetView, appear the error message:
> 
> `Hot reload received invalid response: {type: ReloadReport, success: false, notices: [{type: ReasonForCancellingReload, kind: TypeParametersChanged, class: {type: @Class, fixedId: true, id: classes/1496, name: LoginScreen}, message: Limitation: changing type parameters does not work with hot reload.}]}`
> 
> Flutter clean doesn't work for me.
> 
> If I change GetView to Stateless with a single controller works normally.

Hello!
Since this is a hard to catch bug, could you provide us a reproducible code that we can copy and past in our machines and reproduce this issue? As jonatas already mentioned, we can't reproduce this locally, so a code that gives this problem is required for us to help you

**Comment by oaugustus** [comment] 2020-10-19 10:30
Hi, sure.

This is my main:

```` main.dart
/// main.dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'login/login_page.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        textTheme: GoogleFonts.montserratTextTheme(
          Theme.of(context).textTheme,
        ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: LoginScreen(),
    );
  }
}
````
This is my GetView Widget:
```dart
/// login_page.dart
import 'package:brasil_fields/brasil_fields.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:get/get.dart';
import 'login_controller.dart';

class LoginScreen extends GetView<LoginController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: <Widget>[
          Container(
            decoration: BoxDecoration(
              image: DecorationImage(
                image: AssetImage('assets/images/bg.png'),
                fit: BoxFit.fitWidth,
                alignment: Alignment.topCenter,
              ),
            ),
          ),
          Container(
            margin: EdgeInsets.only(
              left: 20,
              top: 80,
              right: 20,
            ),
            decoration: BoxDecoration(
              image: DecorationImage(
                image: AssetImage('assets/images/logo.png'),
                fit: BoxFit.contain,
                alignment: Alignment.topCenter,
              ),
            ),
          ),
          Container(
            width: MediaQuery.of(context).size.width,
            margin: EdgeInsets.only(top: 300),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(20),
              color: Colors.white,
            ),
            child: Padding(
              padding: EdgeInsets.all(23),
              child: Form(
                key: controller.formKey,
                child: ListView(
                  children: <Widget>[
                    Padding(
                      padding: EdgeInsets.only(top: 20, left: 5),
                      child: Row(
                        children: <Widget>[
                          Text(
                            'Login',
                            style: GoogleFonts.montserrat(
                              textStyle: TextStyle(
                                fontSize: 30,
                                color: Colors.black,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.fromLTRB(0, 20, 0, 20),
                      child: Container(
                        child: TextFormField(
                          controller: controller.contaCtrl,
                          validator: controller.validateConta,
                          keyboardType: TextInputType.number,
                          style: TextStyle(
                            color: Colors.black,
                          ),
                          decoration: InputDecoration(
                            fillColor: Color(0xfff5f5f5),
                            filled: true,
                            border: OutlineInputBorder(),
                            labelText: 'Código do laticínio',
                            prefixIcon: Icon(Icons.business),
                            labelStyle: TextStyle(fontSize: 15),
                          ),
                        ),
                      ),
                    ),
                    Container(
                      child: TextFormField(
                        controller: controller.cpfCtrl,
                        keyboardType: TextInputType.number,
                        inputFormatters: [
                          FilteringTextInputFormatter.digitsOnly,
                          CpfInputFormatter(),
                        ],
                        validator: controller.validateCpf,
                        style: TextStyle(
                          color: Colors.black,
                        ),
                        decoration: InputDecoration(
                          fillColor: Color(0xfff5f5f5),
                          filled: true,
                          border: OutlineInputBorder(),
                          labelText: 'CPF do produtor',
                          prefixIcon: Icon(Icons.assignment_ind),
                          labelStyle: TextStyle(fontSize: 15),
                        ),
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.only(top: 20),
                      child: Obx(
                        () => MaterialButton(
                          disabledColor: Color(0xffff2d55),
                          onPressed: controller.isWaiting.value
                              ? null
                              : controller.submitRegistrar,
                          //since this is only a UI app
                          child: controller.isWaiting.value
                              ? SizedBox(
                                  width: 20,
                                  height: 20,
                                  child: CircularProgressIndicator(
                                    strokeWidth: 2,
                                    valueColor: AlwaysStoppedAnimation<Color>(
                                      Colors.white.withOpacity(0.5),
                                    ),
                                  ),
                                )
                              : Text(
                                  'REGISTRAR',
                                  style: TextStyle(
                                    fontSize: 15,
                                    color: Colors.white,
                                  ),
                                ),
                          color: Color(0xffff2d55),
                          elevation: 0,
                          minWidth: 400,
                          height: 50,
                          textColor: Colors.white,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10),
                          ),
                        ),
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.only(top: 20),
                      child: Center(
                        child: Text(
                          "Milk's Farmer | Versão 0.1",
                          style: TextStyle(
                            fontSize: 15,
                            fontWeight: FontWeight.bold,
                            color: Colors.black,
                          ),
                        ),
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.only(top: 30),
                      child: Center(
                        child: RichText(
                          text: TextSpan(children: [
                            TextSpan(
                              text: "© Plataforma Milk's",
                              style: TextStyle(
                                fontSize: 15,
                                fontWeight: FontWeight.bold,
                                color: Colors.black,
                              ),
                            ),
                          ]),
                        ),
                      ),
                    )
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
`````
And this is my Controller:
````dart
import 'package:cpfcnpj/cpfcnpj.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:myapp/app/main/main_page.dart';

class LoginController extends GetxController {
  /// Controlador do campo de texto da conta do formulário de login.
  final TextEditingController contaCtrl = TextEditingController();

  /// Controlador do campo de texto da do cpf do formulário de login.
  final TextEditingController cpfCtrl = TextEditingController();

  /// Referência ao formulário de login.
  final formKey = GlobalKey<FormState>();

  /// Identifica que o formulário está aguardando retorno da api.
  final isWaiting = false.obs;

  /// Tenta registrar o dispositivo através da api remota.
  void submitRegistrar() async {
    if (formKey.currentState.validate()) {
      isWaiting.toggle();
      // TODO: implementar chamada do método da api.
      await Future.delayed(Duration(seconds: 2));
      isWaiting.toggle();
      Get.to(MainPage());
    }
  }

  /// Valida a [conta] do formulário de login.
  String validateConta(String conta) {
    if (conta.isEmpty) {
      return 'Código do laticínio é obrigatório';
    }

    return null;
  }

  /// Valida o [cpf] do formulário de login.
  String validateCpf(String cpf) {
    if (cpf.isEmpty) {
      return 'CPF é obrigatório';
    }

    if (!CPF.isValid(cpf)) {
      return 'CPF inválido';
    }

    return null;
  }

}

**Comment by eduardoflorence** [comment] 2020-10-19 13:59
@oaugustus in the code above there is no Get.Put for your controller to start and neither a Binding, where do you start it?

**Comment by eduardoflorence** [comment] 2020-10-19 14:06
@oaugustus I only made this change and it is working normally (hot reload):
```dart
void main() {
  Get.put(LoginController());  // <--  insert this
  runApp(MyApp());
}
```

**Comment by eduardoflorence** [comment] 2020-10-19 14:09
@j574144 your problem may also be the lack of controller initialization as I reported above

**Comment by oaugustus** [comment] 2020-10-19 16:05
> @oaugustus I only made this change and it is working normally (hot reload):
> 
> ```dart
> void main() {
>   Get.put(LoginController());  // <--  insert this
>   runApp(MyApp());
> }
> ```

Really, it was the problem. Putting Get.put(LoginController()) on my main works fine. 

Thanks.

**Comment by jonataslaw** [comment] 2020-10-19 16:40
This is a random Flutter cache problem that is not related to Getx.
I am definitely closing this issue. If you think this is a problem, open another issue with a reproduction case that shows the problem and its relationship with Getx. However, definitely, Flutter clean should solve the problem that occurs due to the conflict of files in the cache, and it does not happen by using Getx, but it happens randomly.
On lastest version of Flutter the cache was improvement, maybe this error disappear, i nota sure because this error rarely occurs with me

**Closed by jonataslaw** 2020-10-19 16:40 UTC
Labels: More info is needed, Without a valid reproduction code
