### ISSUE TITLE
Controller not close

### ISSUE THREAD

**Issue by KeepFish** [jonataslaw/getx#460] opened 2020-08-10 03:15 UTC
**To Reproduce**
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() => runApp(GetMaterialApp(home: MainPage()));

class MainPageController extends GetxController {
  var _index = 0.obs;

  int get index => _index.value;

  changeIndex(int index) {
    _index.value = index;
  }
}

class MainPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    MyHomePage homePage = MyHomePage();
    SecondPage secondPage = SecondPage();

    return GetX<MainPageController>(
      init: MainPageController(),
      builder: (c) {
        return Scaffold(
          body: IndexedStack(
            index: c.index,
            children: [homePage, secondPage],
          ),
          bottomNavigationBar: BottomNavigationBar(
            items: <BottomNavigationBarItem>[
              BottomNavigationBarItem(
                icon: Icon(Icons.camera_roll),
                title: Text('home'),
              ),
              BottomNavigationBarItem(
                icon: Icon(Icons.save),
                title: Text('second'),
              ),
            ],
            currentIndex: c.index,
            onTap: (index) {
              c.changeIndex(index);
            },
          ),
        );
      },
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final c = Get.put(HomePageController());
    return Scaffold(
      appBar: AppBar(
        title: Text('app'),
      ),
      body: Center(
        child: Text(
            '213',
          ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class HomePageController extends GetxController {}

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Get.put(SecondController());

    return Scaffold(
      appBar: AppBar(
        title: Text('SecondPage'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          print('click');
          Get.offAll(MainPage());
        },
        child: Icon(Icons.map),
      ),
    );
  }
}

class SecondController extends GetxController {}

```
Click button in SecondPage, print like:

```
flutter: [GETX] GOING TO ROUTE /
flutter: [GETX] MainPageController has been initialized
flutter: [GETX] HomePageController has been initialized
flutter: [GETX] SecondController has been initialized
flutter: click
flutter: [GETX] GOING TO ROUTE /MainPage
flutter: [GETX] REMOVING ROUTE /
flutter: [GETX] onClose of MainPageController called
flutter: [GETX] MainPageController deleted from memory

```

**Expected behavior**
- MainPageController reinit
- HomePageController and SecondController delete from memory

**Flutter Version:**
Flutter (Channel stable, 1.20.1, on Mac OS X 10.14.5 18F132, locale  zh-Hans-CN)

**Get Version:**
3.4.3

**Describe on which device you found the bug:**
iPhone simulator 13.3

Am I wrong? 
What is the right way to remove a page with some subpage?

**Comment by jonataslaw** [comment] 2020-08-10 05:08
IndexedStack will not even display the widgets you used on it, so it would never remove a controller from memory, as it is actually being used.
IndexedStack is not navigation, it is not a new page, and definitely, the print reproduces exactly the expected behavior.
IndexedStack is just a Widget Stack, which orders your children according to the given index.
It looks like you are looking for non-standard behavior, or are using the wrong widget (look for TabBar).
Please, if this is a question of use, or non-standard behavior, I recommend that you look for support channels for this.
If you find a bug, feel free to open another issue.
Closing it.

**Closed by jonataslaw** 2020-08-10 05:08 UTC
Labels: invalid

**Comment by KeepFish** [comment] 2020-08-10 06:46
Thanks, I thought the widget is like iOS TabBarController
