### ISSUE TITLE
Error: No named parameter with the name 'scrollBehavior'

### ISSUE THREAD

**Issue by mirxtrem-apps** [jonataslaw/getx#1689] opened 2021-07-25 03:28 UTC
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
Flutter run throw this message using example_nav2:

Launching lib\main.dart on Chrome in debug mode...
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.2.5/lib/get_navigation/src/root/get_material_app.dart:297:15: Error: No named parameter with the name 'scrollBehavior'.
              scrollBehavior: scrollBehavior,
              ^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/app.dart:217:9: Context: Found this candidate, but the arguments don't match.
  const MaterialApp.router({
        ^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.2.5/lib/get_navigation/src/root/get_material_app.dart:340:15: Error: No named parameter with the name 'scrollBehavior'.
              scrollBehavior: scrollBehavior,
              ^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/app.dart:167:9: Context: Found this candidate, but the arguments don't match.
  const MaterialApp({
        ^^^^^^^^^^^
Waiting for connection from debug service on Chrome...             16,6s
Failed to compile application.

**Reproduction code
Here is all my code.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() => runApp(
      GetMaterialApp(
        title: 'Material App',
        getPages: [
          GetPage(
            name: '/',
            page: () => RootPage(),
          )
        ],
      ),
    );

class RootPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Home"),
      ),
      body: Center(
        child: Text("Home works"),
      ),
    );
  }
}

```

**To Reproduce**
1. Install latest get package
2. User GetMaterialApp.router(...)
3. user getPages attribute with only 1 getPage
4. Flutter run
5. Error: No named parameter with the name 'scrollBehavior'. scrollBehavior: scrollBehavior,

**Expected behavior**
Flutter run application normally

**Flutter Version:**
v 2.0.4

**Getx Version:**
v 4.2.5

**Describe on which device you found the bug:**
Chrome and android

**Comment by jonataslaw** [comment] 2021-07-25 05:06
Update your Flutter, you are using a legacy version

**Comment by arsalalgorepublic** [comment] 2021-07-25 06:04
i'm facing the same issue. any solution?

**Comment by ali80** [comment] 2021-07-25 12:30
use previous version like `get: 4.1.4` without the `^`, IMO this is a bug cause `4.2.5` is not compatible with `4.1.4` but I think is flagged as such

**Comment by jonataslaw** [comment] 2021-07-25 14:51
This is not a bug, just do it
`flutter upgrade`

You are using legacy version.
closing it

**Closed by jonataslaw** 2021-07-25 14:51 UTC

**Comment by calvintam236** [comment] 2021-08-05 03:55
> Update your Flutter, you are using a legacy version

@jonataslaw Our project is stuck at Flutter v2.0.x due to some packages are not compatible to v2.2 yet. It is common practice to note in changelog that a breaking change has introduced for older flutter version (testing for one older major version is common practice).

The breaking changes were made in #1666, and without setting up version constraints for flutter in `pubspec` causes this **bug**.

https://github.com/jonataslaw/getx/blob/ebbb55519dac53ef08a5337e36e18f74a21f7fb5/pubspec.yaml#L6-L11

The constraints can be set in `environments` section per https://dart.dev/tools/pub/pubspec in the `Flutter SDK constraints` section. This is a breaking change for other packages which depends `get` (they have no way to know it is no longer compatible with flutter v2.0 or lower).

**Comment by mhammedkh20** [comment] 2021-09-14 10:08
I found the solution
You just have to delete the scrollBehavior feature completely so that you search for the feature and delete it Via C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.3.8/lib/get_navigation/src/root/get_material_app.dart
