### ISSUE TITLE
SnackBar Error

### ISSUE THREAD

**Issue by diegudias** [jonataslaw/getx#759] opened 2020-11-01 14:16 UTC
Quando a SnackBar é fechada, no Flutter Web, aparece o erro:

overlayEntries.isEmpty
is not true

════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
Assertion failed: ../…/snackbar/snack_route.dart:263

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
packages/get/get_navigation/src/snackbar/snack_route.dart 263:33              [_handleStatusChanged]
packages/flutter/src/animation/listener_helpers.dart 199:27                   notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 795:7                [_checkStatusChanged]
...
The AnimationController notifying status listeners was: AnimationController#9efc3(⏮ 0.000; paused; for SnackRoute<dynamic>)

**Comment by worldofsites** [comment] 2020-11-03 09:35
Same issue

**Comment by zzterrozz** [comment] 2020-11-03 15:05
@diegudias @worldofsites Please try [https://github.com/jonataslaw/getx/issues/748#issuecomment-719138586](https://github.com/jonataslaw/getx/issues/748#issuecomment-719138586)

**Comment by jonataslaw** [comment] 2020-11-03 16:52
Duplicate of https://github.com/jonataslaw/getx/issues/748
Look at https://github.com/jonataslaw/getx/issues/748#issuecomment-719138586

**Closed by jonataslaw** 2020-11-03 16:52 UTC
