### ISSUE TITLE
Cannot access arguments for nested navigators

### ISSUE THREAD

**Issue by AcnoSaga** [jonataslaw/getx#584] opened 2020-09-10 04:48 UTC
As of Get 3.10.1, there seems to be no way to access currentRoute and arguments etc. for nested naviagtors. Can we have an API to select navigator by id for these things (as we do when we navigate)?

**Comment by rizalashidiq97** [comment] 2020-09-19 09:23
I have this issue as well .

**Comment by rizalashidiq97** [comment] 2020-09-19 11:39
@mention https://github.com/jonataslaw/getx/issues/179

**Comment by rizalashidiq97** [comment] 2020-09-19 11:44
closed#179

**Comment by rizalashidiq97** [comment] 2020-09-19 11:44
closed #179

**Comment by rizalashidiq97** [comment] 2020-09-19 11:45
#179

**Comment by rizalashidiq97** [comment] 2020-09-19 11:46
GH-179

**Comment by rizalashidiq97** [comment] 2020-09-19 11:48
#179

**Comment by rizalashidiq97** [comment] 2020-09-19 14:48
#179

**Comment by jonataslaw** [comment] 2020-09-19 15:57
Duplicate of https://github.com/jonataslaw/getx/issues/179
Thanks @rizalashidiq97

**Closed by jonataslaw** 2020-09-19 15:57 UTC
Labels: Not an issue, Without a valid reproduction code
