### ISSUE TITLE
GetBuilder - select values from the Controller

### ISSUE THREAD

**Issue by lukaszdebowski** [jonataslaw/getx#489] opened 2020-08-22 15:29 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes, when we call the `update()` method inside the controller, some `GetBuilder` get rebuild unnecessarily, i.e let's say we have a `User` class with `name` and `email` fields.

This is our controller:
```
class UserController extends GetxController {
  static UserController get I => Get.find();

  User value = User(
    id: 0,
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@gmail.coim",
  );

  void setFirstName(String newName) {
    value.firstName = newName;
    update();
  }

  void setEmail(String newEmail) {
    value.email = newEmail;
    update();
  }
}

```

Then somewhere inside our view, we have something like this:

```
Column(
  mainAxisSize: MainAxisSize.min,
  children: [
    Text("Dashboard Screen"),
    GetBuilder<UserController>(
      builder: (_) {
        return Text("Full Name: ${_.value.fullName}");
      },
    ),
    GetBuilder<UserController>(
      builder: (_) {
        return Text("Email: ${_.value.email}");
      },
    ),
  ],
),
```

Even if we only use the `setFirstName` method on the controller, the `email` builder will rebuild (even though the email did not change). 

**Describe the solution you'd like**
It would be nice to have something like a `select` property on the `GetBuilder` widget, which is basically a function that returns the value, that must be changed inside our controller, for the builder to get rebuild. So something like:

```
GetBuilder<UserController>(
  select: (controller) => controller.value.email,
  builder: (_) {
    return Text("Email: ${_.value.email}");
  },
),
```

This would mean that only if the `email` field is different than it was before the `update()` call, this builder should get updated.

**Describe alternatives you've considered**
Could't really find anything that would supply me with this functionality, but I could've searched wrong. Maybe there is something like that already?

**Comment by jonataslaw** [comment] 2020-08-24 13:59
As the existing tools for this resource were pointed out, and the issue was no longer answered, I am closing this issue.

**Closed by jonataslaw** 2020-08-24 13:59 UTC
Labels: Existing feature, enhancement

**Comment by subzero911** [comment] 2021-07-04 11:28
@jonataslaw 
+1 for selector
GetX and Obx are easy in use but heavily ram-consuming. GetBuilder is the fastest. It would be even better with an option to selectively update on certain variables changing, to avoid unnecessary rebuilds.
Also, it would be easier to transfer the existing Provider-based project to Get.
ids / tags assignment looks like an antipattern, because it makes your widgets and controllers tightly coupled - you MUST add the same tags in your GetBuilders, which are listed in corresponing update([...]). According to domain-driving model, controller shouldn't know anything about widgets and their tags, it should care about business logic only. It's better to let widgets to choose on which variables change they should rebuild.

**Comment by jonataslaw** [comment] 2021-07-31 16:43
> @jonataslaw
> +1 for selector
> GetX and Obx are easy in use but heavily ram-consuming. GetBuilder is the fastest.
> Also, it would be easier to transfer the existing Provider-based project to Get.
> Ids / tags assignment looks like an antipattern, because it makes your widgets and controllers tightly coupled - you MUST add the same tags in your GetBuilders, which are listed in corresponing update([...]). Normally, controller shouldn't know anything about widgets and their tags, it should care about business logic only. It's better to let widgets to choose on which variables change they should rebuild.

GetBuilder has a `filter` property where you can filter rebuilds.

**Comment by subzero911** [comment] 2021-07-31 17:15
I can't find how exactly it filters rebuilds. It just does `setState` on any change!
You can set any filter function, but seems like GetBuilder doesn't use it anywhere.

![image](https://user-images.githubusercontent.com/12999702/127747173-2dae9953-9f24-4bff-86e4-82f30432d337.png)
![image](https://user-images.githubusercontent.com/12999702/127747208-659b3d22-1a4c-430a-8346-2e820c65ab4c.png)

**Comment by subzero911** [comment] 2021-08-07 06:52
I compiled a minimal reproducible example, and can confirm that `filter` actually works. Just wanted to make sure.

Without filter - all 3 widgets print "rebuilt"
With filter - only widget I clicked prints "rebuilt"

<summary>Main</summary>
<details> 

```dart

import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'controller.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    Get.put(MyController());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            GetBuilder<MyController>(
              filter: (c) => c.textA,
              builder: (c) {
                print('Controller A rebuilt');
                return ElevatedButton(
                  onPressed: () => c.changeA(),
                  child: Text(c.textA),
                );
              },
            ),
            GetBuilder<MyController>(
              filter: (c) => c.textB,
              builder: (c) {
                print('Controller B rebuilt');
                return ElevatedButton(
                  onPressed: () => c.changeB(),
                  child: Text(c.textB),
                );
              },
            ),
            GetBuilder<MyController>(
              filter: (c) => c.textC,
              builder: (c) {
                print('Controller C rebuilt');
                return ElevatedButton(
                  onPressed: () => c.changeC(),
                  child: Text(c.textC),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>


<summary>Controller</summary>
<details> 

```dart
import 'package:get/get.dart';

class MyController extends GetxController {
  MyController();

  String textA = '';
  String textB = '';
  String textC = '';

  void changeA() {
    textA.isEmpty ? textA = 'bla bla' : textA = '';
    update();
  }

  void changeB() {
    textB.isEmpty ? textB = 'bla bla' : textB = '';
    update();
  }

  void changeC() {
    textC.isEmpty ? textC = 'bla bla' : textC = '';
    update();
  }
}

```
</details>
