### ISSUE TITLE
Failed to compile application.

### ISSUE THREAD

**Issue by htueko** [jonataslaw/getx#774] opened 2020-11-07 11:53 UTC
**Describe the bug**
Failed to compile application.

**Reproduction code

```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        return OrientationBuilder(
          builder: (context, orientation) {
            SizeConfig().init(constraints, orientation);
            return GetMaterialApp(
              debugShowCheckedModeBanner: false,
              getPages: AppNavigator.route,
              initialRoute: homeRoute,
              theme: AppTheme.darkTheme,
              defaultTransition: Transition.fade,
            );
          },
        );
      },
    );
  }
}

```

**To Reproduce**
1. Choose **CHROME (WEB)** at **Flutter Device Selection**
2. Click **Run 'main.dart'**
3. Open the **Run dialog box**

**Expected behavior**
Running on local machine web

**Screenshots**
![getx_error](https://user-images.githubusercontent.com/33115344/98440259-4250d680-2126-11eb-9a81-faa825d1e36f.png)

**Flutter Version:**
Flutter 1.24.0-8.0.pre.142 • channel master

**Getx Version:**
get: ^3.15.0

**Describe on which device you found the bug:**
ex: local host (web), XIAOMI REDMI NOTE 2, Pixel 4, Pixel 3

**Minimal reproduce code**
Update the Flutter version (master) to 11.24.0-8.0.pre.142 then run the app

**Comment by jonataslaw** [comment] 2020-11-07 21:50
Duplicate of https://github.com/jonataslaw/getx/issues/762

**Closed by jonataslaw** 2020-11-07 21:50 UTC
