### ISSUE TITLE
View update as list update in controller

### ISSUE THREAD

**Issue by ziasultan2** [jonataslaw/getx#527] opened 2020-08-29 14:55 UTC
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
How can I update specific value inside view

**Expected behavior**
update data in listview

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

// List of Foods 
final cart = List<Foods>().obs;

  increase(index) {
  // Here I'm updating the value in list how can I update this in view. 
 // Here index is the index position of food in cart list
    cart.value[index].quantity++;
    update();
  }

I tried cart.update()  but it's not showing any relevant method to update list

**Comment by jonataslaw** [comment] 2020-08-29 15:20
- Observable variables are not updated via update.
- Observable lists should not use `.value` properties. In fact, you should avoid using the .value in Lists and Maps as much as possible.
- Please read the documentation that is here:
https://github.com/jonataslaw/getx/blob/master/docs/en_US/state_management.md
- A reproduction code was not provided.
Reproduction code is a complete, self-executable code (without any dependency), which allows you to view the problem with a quick build.
- `[index].quantity++;` gives me the impression that you are trying to change the food property, not the list, since there is no "quantity" property in Lists. If you want this property to be Observable, it must also be an observable value.
- For questions about the use, if you are not sure that what you are facing is a reproducible problem that should not occur in the framework, look for community channels. Opening questions in the issues field will disturb other users who may be looking for similar cases of real problems.

I am closing this issue because it does not contain a case of reproduction, and because it is an inappropriate use of the library. If you think this is really a bug, open another issue with a valid reproduction case, but first, read the documentation above, and check if really what you are facing is a bug, before opening an issue. Community channels are the fastest place for you to ask questions like this.

**Closed by jonataslaw** 2020-08-29 15:20 UTC

**Comment by Nipodemos** [comment] 2020-08-29 17:53
just to complete the issue, since have a observable list usually is not the best, you should instead have a normal list of observable values:

```dart
//before:
final cart = List<Foods>().obs;

//after
final cart = List<Rx<Foods>>();
```

that way you have a list with multiple observable food classes

and to update them:
```dart
cart[index].update( (food) { // this parameter is the class itself that you want to update
food.quantity++;
});
```

coincidence or not, the documentation about this were added today!
https://github.com/jonataslaw/getx/blob/master/docs/en_US/state_management.md#note-about-lists

**Comment by ziasultan2** [comment] 2020-08-29 18:06
Thank you dear for this solution.
