### ISSUE TITLE
Ever is not called at the initial value

### ISSUE THREAD

**Issue by Ditway** [jonataslaw/getx#338] opened 2020-07-03 03:21 UTC
when i use it for listen some observable variable it doesn't do on first time, but it do when variable change on second time.
i need help!!!

**Comment by ghprod** [comment] 2020-07-03 11:01
Any sample code?

**Comment by jonataslaw** [comment] 2020-07-03 14:28
I tested this on the latest version and it works properly. The problem is certainly in your code, but I need a reproduction case or example of how you are using it to help you.
Please, the next time you open this, I kindly ask you not to delete the issue opening template.

```dart
  test('once', () async {
    final count = 0.obs;
    var result = -1;
    once(count, (_) {
      result = _ as int;
    });
    count.value++;
    await Future.delayed(Duration.zero);
    expect(1, result); // value changed first time
    count.value++;
    await Future.delayed(Duration.zero);
    expect(1, result);
    count.value++;
    await Future.delayed(Duration.zero);
    expect(1, result);
  });
```

**Comment by Ditway** [comment] 2020-07-04 04:00
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class FirstScreen extends StatelessWidget {
  const FirstScreen({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("First Screen"),
      ),
      body: Center(
        child: RaisedButton(
          child: Text("Goto Second Screen"),
          onPressed: () {
            Get.toNamed("/second");
          },
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  SecondScreen({Key key}) : super(key: key);
  final controller = Get.put(CounterController());
  @override
  Widget build(BuildContext context) {
    bool doFirstTime = false;
    ever(controller.count, (value) {
      if (!doFirstTime) doFirstTime = true;
      print("counter changed $value");
    });
    print("Do first time $doFirstTime");

    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Obx(() => Text("Counter : " + controller.count.string)),
            SizedBox(
              height: 30,
            ),
            RaisedButton(
              child: Text("Increase"),
              onPressed: () {
                controller.increase();
              },
            )
          ],
        ),
      ),
    );
  }
}

class CounterController extends GetxController {
  final count = 0.obs;

  void increase() => count.value++;
}

here simple code.

**Comment by Ditway** [comment] 2020-07-04 04:18
when i goto second screen. 
print result : Do first time false.

why false?

```dart

import 'package:flutter/material.dart';
import 'package:get/get.dart';

class FirstScreen extends StatelessWidget {
  const FirstScreen({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("First Screen"),
      ),
      body: Center(
        child: RaisedButton(
          child: Text("Goto Second Screen"),
          onPressed: () {
            Get.toNamed("/second");
          },
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  SecondScreen({Key key}) : super(key: key);
  final controller = Get.put(CounterController());
  @override
  Widget build(BuildContext context) {
    bool doFirstTime = false;
    ever(controller.count, (value) {
      if (!doFirstTime) doFirstTime = true;
      print("counter changed $value");
    });
    print("Do first time $doFirstTime");

    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Obx(() => Text("Counter : " + controller.count.string)),
            SizedBox(
              height: 30,
            ),
            RaisedButton(
              child: Text("Increase"),
              onPressed: () {
                controller.increase();
              },
            )
          ],
        ),
      ),
    );
  }
}

class CounterController extends GetxController {
  final count = 0.obs;

  void increase() => count.value++;
}



```

**Comment by jonataslaw** [comment] 2020-07-04 04:56
Initially, I need to aim for something.
This example is definitely going over all the points about what are considered good practices with Getx.

Initially:
Workers should only be called using the onInit or onReady method (depending on the situation).
You should never, under any circumstances, call a worker within a build method, in fact, according to official Flutter documentation, builder methods should only receive pure widgets. I have no problem inserting internal variables, but calling methods is definitely prohibitive.
Please, when using this library, try to transfer 100% of your methods and variables to your controller, the view should only contain only widgets, and at most internal variables.
Second: testing his exact example, even though still against the guarantees of good practices, he works exactly as planned, being called the first time the variable is changed.
I think you missed something in the Workers documentation, you can go back and read again how they work.

**Comment by jonataslaw** [comment] 2020-07-04 05:00
Seeing your edited question I was able to confirm, you are wanting to use workers for a job like onInit.
Workers are only called when a variable is changed. If you need their initial value, override onInit or onReady to get their current value.

**Comment by jonataslaw** [comment] 2020-07-04 05:10
And you can also create custom Workers, you created something similar to the mobx autorun by starting the callback before the listen, there is no problem using custom Workers, we even encourage that. But you should also be aware that there are other apis to be explored that can have the same result, before creating a Workers.
I don't know if I documented the life cycle in detail, but basically.

onInit is called when the Controller enters memory.
onReady is called after onInit, and after completion of all current build methods (second to use snackbar, dialogs, routes, etc. in it)
onClose is called before your controller goes to onDelete. onClose is the ideal place to close streams, for example.

Workers are only called when you actually change a variable (except the first time), this means that if you have a variable 3, and send a 3 again, worker will not be triggered, the state in the view (Obx / GetX) will refuse the status update, and nothing will be rebuilt, to avoid unnecessary rebuilds altogether.

**Comment by jonataslaw** [comment] 2020-07-04 14:41
Well, as it was clarified that ever is called when the value is changed, and the initial value is not a value change, I am closing this.

**Closed by jonataslaw** 2020-07-04 14:41 UTC
Labels: Waiting for customer response
