### ISSUE TITLE
not use getx to jump and close page, onclose cannot execute 

### ISSUE THREAD

**Issue by liaovq** [jonataslaw/getx#869] opened 2020-12-07 09:11 UTC
When I use Navigator to jump and close the page, the onclose in the controller cannot be triggered
But  use getx to jump and close page, onclose can execute 

**Flutter Version**: 1.17.1

**Getx Version**: 3.22.2

This is the demo I wrote
```dart
import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
      getPages: [
        GetPage(name: '/first', page: () => FirstPage()),
        GetPage(name: '/second', page: () => SecondPage()),
      ],
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _toFirst() {
    // use this way jump page and back, can call controller onClose
    Get.toNamed('first');
  }

  void _toSecond() {
    // use this way jump page and back, cant call controller onClose
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => SecondPage()),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            InkWell(child: Text('toFirst'), onTap: _toFirst),
            SizedBox(height: 100),
            InkWell(child: Text('toSecond'), onTap: _toSecond)
          ],
        ),
      ),
    );
  }
}

class FirstPage extends StatelessWidget {
  FirstPage({Key key}) : super(key: key);
  final FirstCon firstCon = Get.put<FirstCon>(FirstCon());
  @override
  Widget build(BuildContext context) {
    return Container(child: Text('first'));
  }
}

class SecondPage extends StatelessWidget {
  SecondPage({Key key}) : super(key: key);
  final SecondCon secondCon = Get.put<SecondCon>(SecondCon());
  @override
  Widget build(BuildContext context) {
    return Container(child: Text('second'));
  }
}

class FirstCon extends GetxController {
  static FirstCon to = Get.find();

  @override
  void onReady() {
    log('first con ready');
    super.onReady();
  }

  @override
  void onClose() {
    log('first con close');
    super.onClose();
  }
}

class SecondCon extends GetxController {
  static FirstCon to = Get.find();

  @override
  void onReady() {
    log('second con ready');
    super.onReady();
  }

  @override
  void onClose() {
    log('second con close');
    super.onClose();
  }
}
```

**Comment by eduardoflorence** [comment] 2020-12-07 12:06
@liaovq, you must place Get.put inside the build method. See an example:
```dart
class FirstPage extends StatelessWidget {
  FirstPage({Key key}) : super(key: key);
  // Not here
  @override
  Widget build(BuildContext context) {
    final FirstCon firstCon = Get.put<FirstCon>(FirstCon()); // here
    return Container(child: Text('first'));
  }
}
```

**Comment by jonataslaw** [comment] 2020-12-07 18:03
If you are using normal navigation, you should use GetBuilder/GetX to initialize your widgets, since navigation will not be tracked, so onClose will never be called.



> When I use Navigator to jump and close the page, the onclose in the controller cannot be triggered
> But use getx to jump and close page, onclose can execute
> 
> **Flutter Version**: 1.17.1
> 
> **Getx Version**: 3.22.2
> 
> This is the demo I wrote
> 
> ```dart
> import 'dart:developer';
> 
> import 'package:flutter/material.dart';
> import 'package:get/get.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return GetMaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>         visualDensity: VisualDensity.adaptivePlatformDensity,
>       ),
>       home: MyHomePage(title: 'Flutter Demo Home Page'),
>       getPages: [
>         GetPage(name: '/first', page: () => FirstPage()),
>         GetPage(name: '/second', page: () => SecondPage()),
>       ],
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   MyHomePage({Key key, this.title}) : super(key: key);
>   final String title;
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   void _toFirst() {
>     // use this way jump page and back, can call controller onClose
>     Get.toNamed('first');
>   }
> 
>   void _toSecond() {
>     // use this way jump page and back, cant call controller onClose
>     Navigator.push(
>       context,
>       MaterialPageRoute(builder: (context) => SecondPage()),
>     );
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text(widget.title)),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: <Widget>[
>             InkWell(child: Text('toFirst'), onTap: _toFirst),
>             SizedBox(height: 100),
>             InkWell(child: Text('toSecond'), onTap: _toSecond)
>           ],
>         ),
>       ),
>     );
>   }
> }
> 
> class FirstPage extends StatelessWidget {
>   FirstPage({Key key}) : super(key: key);
>   final FirstCon firstCon = Get.put<FirstCon>(FirstCon());
>   @override
>   Widget build(BuildContext context) {
>     return Container(child: Text('first'));
>   }
> }
> 
> class SecondPage extends StatelessWidget {
>   SecondPage({Key key}) : super(key: key);
>   final SecondCon secondCon = Get.put<SecondCon>(SecondCon());
>   @override
>   Widget build(BuildContext context) {
>     return Container(child: Text('second'));
>   }
> }
> 
> class FirstCon extends GetxController {
>   static FirstCon to = Get.find();
> 
>   @override
>   void onReady() {
>     log('first con ready');
>     super.onReady();
>   }
> 
>   @override
>   void onClose() {
>     log('first con close');
>     super.onClose();
>   }
> }
> 
> class SecondCon extends GetxController {
>   static FirstCon to = Get.find();
> 
>   @override
>   void onReady() {
>     log('second con ready');
>     super.onReady();
>   }
> 
>   @override
>   void onClose() {
>     log('second con close');
>     super.onClose();
>   }
> }
> ```

MaterialPageRoute is not able to track the controllers and dispose of them when necessary.
Change this to GetPageRoute, or use GetBuilder/GetX to track your controllers instead of using Get.put ().
This is expected behavior, and there is no reason to use MaterialPageRoute using GetX, but if you want to follow this path, you must change the working logic for your builder widgets (GetX/GetBuilder), once you lose the security of the device. through the routes.

Well, as there is no problem with this issue, and it is the expected behavior, I am closing this.

**Closed by jonataslaw** 2020-12-07 18:03 UTC
Labels: Not an issue, expected behavior

**Comment by chihuy105** [comment] 2020-12-11 14:20
Can anyone show me the example, I try to implement it but it still not work!!

**Comment by eduardoflorence** [comment] 2020-12-12 12:01
The improper use is because you did not put any obs variables in your controller and inside GetX/GetBuilder
