### ISSUE TITLE
GetPage can't  get the right page name that android passed to me 

### ISSUE THREAD

**Issue by Cvilia** [jonataslaw/getx#784] opened 2020-11-11 03:02 UTC
**_PLEASE_**

In my android project ,i create flutter module,and use getx to manage state,
like this:

  static final routes = [
    GetPage(name: Routes.HOME, page: () => HomeView(), binding: HomeBind()),
    GetPage(
        name: Routes.MAIN,
        page: () {
          return routePage(window.defaultRouteName);
        })
  ];

Widget routePage(String routeName) {
  switch (routeName) {
    case '/page1':
      return MyHomePage(
        title: routeName,
      );
    case '/page2':
      return Page2();
    default:
      return Center(
        child: Text('什么都没有'),
      );
  }
}
but i can't get the right page name that android passed to me.

**Comment by jonataslaw** [comment] 2020-12-08 16:47
I can't reproduce the problem, and the description shows that there is an error between passing arguments from android to navigation.
GetX will only perform Flutter navigation, so this problem has no relation to getx.
That way, I'm closing this.

**Closed by jonataslaw** 2020-12-08 16:47 UTC
Labels: Unrelated to GetX
