### ISSUE TITLE
Raw snackbar strange behaviour

### ISSUE THREAD

**Issue by itssidhere** [jonataslaw/getx#347] opened 2020-07-05 16:07 UTC
In raw snackbar messageText is of type Widget and message is of type Text. Is this intended? And text defined inside messageText i.e., Widget like Column(children:<Widget>[Text ()]) isn't changing wrt to snackbar color instead it's changing according to the primary text color as opposed to Original snackbar.!

**Comment by jonataslaw** [comment] 2020-07-05 16:41
Hi, Yes, that is intended.
"message" is String, and messageText is a Widget. You can customize the color as you like using the style property of Text(). 
As this is not a bug description, but a question that has been answered, I am closing this.

**Closed by jonataslaw** 2020-07-05 16:41 UTC
