### ISSUE TITLE
Add back the previous routes on navigation stack when directly accessing a url on web

### ISSUE THREAD

**Issue by arthurpiccoli** [jonataslaw/getx#336] opened 2020-07-03 00:27 UTC
Previously on namedRoutes if you typed `hostname/foo/bar` you would end up in BarScreen and your navigation stack would be:

> HomeScreen
> FooScreen
> BarScreen

Now on getPages if you type `hostname/foo/bar` your navigation stack will only be:

> BarScreen

This was a really useful feature that is now gone, is it gonna be implemented back in the near future or is it deprecated?

**Comment by jonataslaw** [comment] 2020-07-03 00:53
duplicate of: https://github.com/jonataslaw/getx/issues/291#issuecomment-649977061 (read comment)

**Closed by jonataslaw** 2020-07-03 00:53 UTC
