### ISSUE TITLE
onInit doesn't trigger in second time

### ISSUE THREAD

**Issue by niypoo** [jonataslaw/getx#782] opened 2020-11-10 13:57 UTC
I have created page and define a route called  '/test-page' like that 
**note `BottomSheetController` is controller that serve this page and called as lazy in binding**

```
  GetPage(
      name: '/test-page',
      page: () => BottomSheetView(),
      binding: BottomSheetBinding(),
      popGesture: true,
      fullscreenDialog: true,
      title: LocaleService.tra('Store Item Preview'),
      transition: Transition.downToUp,
    ),

```
Issue steps:

1- I called that page first time -> `oninit` trigger
2- I tap on button that trigger `Get.back()`
3- handle data then called same page again -> second time with different data
4- onInit doesn't trigger to handle new data. --> that issue

called route
```
return await Get.toNamed(
      '/test-page',
      arguments: {
        'isConfirm': true,
      },
     preventDuplicates: true, // OR false same result
)


```

log
```
flutter: open first time ++
[GETX] GOING TO ROUTE /test-page
[GETX] Lazy instance "BottomSheetController" created
[GETX] "BottomSheetController" has been initialized
[GETX] CLOSE TO ROUTE /test-page
flutter: open second time ++
[GETX] GOING TO ROUTE /test-page
[GETX] "BottomSheetController" onClose() called
[GETX] "BottomSheetController" deleted from memory


```

**Comment by jonataslaw** [comment] 2020-11-10 19:14
Please attach a reproduction code.

**Comment by niypoo** [comment] 2020-11-10 19:55
> Please attach a reproduction code.

there is [https://github.com/niypoo/getXTestIssueOnInitTrigger.git](url) a test code you can test it

**Comment by eduardoflorence** [comment] 2020-11-10 20:52
In the execution of the second `Get.toNamed`, the GetX smartManagement did not have time to remove TestController from memory. A possible solution would be to make a delay before the second `Get.toNamed` as in the example below:

```dart
RaisedButton(
  onPressed: () async {
    await Get.toNamed('/test',
        arguments: {'title': 'First Attempt...'}, preventDuplicates: false);
    print('Handle some stuff ....');
    await Future.delayed(Duration(milliseconds: 300)); // <- Insert this
    await Get.toNamed('/test',
        arguments: {'title': 'Second Attempt...'}, preventDuplicates: false);
  },
  child: Text(
    'Open Test Page',
  ),
),
```

**Comment by niypoo** [comment] 2020-11-10 20:55
> In the execution of the second `Get.toNamed`, the GetX smartManagement did not have time to remove TestController from memory. A possible solution would be to make a delay before the second `Get.toNamed` as in the example below:
> 
> 
> 
> ```dart
> 
> RaisedButton(
> 
>   onPressed: () async {
> 
>     await Get.toNamed('/test',
> 
>         arguments: {'title': 'First Attempt...'});
> 
>     print('Handle some stuff ....');
> 
>     await Future.delayed(Duration(milliseconds: 300)); // <- Insert this
> 
>     await Get.toNamed('/test',
> 
>         arguments: {'title': 'Second Attempt...'});
> 
>   },
> 
>   child: Text(
> 
>     'Open Test Page',
> 
>   ),
> 
> ),
> 
> ```

So I didn't miss something! And this is normal behavior!?

**Comment by eduardoflorence** [comment] 2020-11-10 21:38
It is not common to navigate to the same route immediately after returning from it. In my point of view this is an expected behavior, because it is not Get.back that removes the controller from memory, but SmartManagement, for that it needs a minimum time. When you navigate to the same route again, SmartManagement understands that you should not remove the controller from memory and that is why onInit is not triggered.
Either way, @jonataslaw, the owner of this package, can provide better feedback.

**Comment by eduardoflorence** [comment] 2020-11-16 11:11
@niypoo, can we close this issue?

**Comment by niypoo** [comment] 2020-11-16 22:41
> @niypoo, can we close this issue?

Sure I did sone delay as you suggested and it's working

**Closed** 2020-11-17 22:08 UTC

**Comment by jonataslaw** [comment] 2020-11-17 22:25
Just a side note: @eduardoflorence is right about the current approach, however, I intend to improve this in the future.
