### ISSUE TITLE
What is the purpose/benefit of having Snackbars/dialogs be routes?

### ISSUE THREAD

**Issue by jlubeck** [jonataslaw/getx#365] opened 2020-07-10 20:06 UTC
What the title says... I run into problems all the time having Snackbars be routes, is there a benefit for this decision?

It seems like behavior changes every now and then. 

Example, this was working fine with an older version of get:

```dart
      Get.snackbar(
        'User 123',
        'Successfully created',
      );
      Get.back();
```

That would show the snackbar and go back to the previous screen at the same time (leaving the snackbar present on top of the previous screen, as intended)

Now it is not showing the snackbar at all (I assume because it is closing it automatically)

I tried putting the Get.back() first, and it works on mobile, but not on Web.

So, besides the main question of the ticket, what would be the best approach to leave the snackbar open while going to previous screens? One use case is a new user screen, where after saving I want to go back to the previous screen and show the success snackbar.

Thank you!

**Comment by jonataslaw** [comment] 2020-07-10 20:55
> What the title says... I run into problems all the time having Snackbars be routes, is there a benefit for this decision?

Everything in the Flutter are routes.
In fact, any screen overlay is a new route. You can follow the log to see that even opening a PopupMenu or Dropdrow a route will be pushed.
There is no "benefit" or harm in doing this, because that is simply the Flutter.

> It seems like behavior changes every now and then.
> 
> Example, this was working fine with an older version of get:
> 
> ```dart
>       Get.snackbar(
>         'User 123',
>         'Successfully created',
>       );
>       Get.back();
> ```

This was a bug fixed where the snackbar had a certain delay to be marked as started, and caused this bug, but pushing a Get.back() in front of a snackbar will not close the screen, but the snackbar.
> 
> That would show the snackbar and go back to the previous screen at the same time (leaving the snackbar present on top of the previous screen, as intended)
       
```
      Get.back();
      Get.snackbar(
        'User 123',
        'Successfully created',
      );
```
This works both on android and on the web, maybe the version you are using has a bug, but I just tested it and it works well on the web.

> 
> Now it is not showing the snackbar at all (I assume because it is closing it automatically)
> 
> I tried putting the Get.back() first, and it works on mobile, but not on Web.

You should have more refined control over when to close a screen or a snack bar.
Get.back(closeOverlays: true); will close the page and the snackbar.
Get.until((_) => Get.isSnackbarOpen); it will only close the snackbar.
The only way to let a current snackbar be displayed on a new route is using Get.removeRoute().

> 
> So, besides the main question of the ticket, what would be the best approach to leave the snackbar open while going to previous screens? One use case is a new user screen, where after saving I want to go back to the previous screen and show the success snackbar.

Always send the route first and the snackbar later, I think I also mentioned this in version 1.0 of Get.

> 
> Thank you!

**Comment by jlubeck** [comment] 2020-07-10 20:59
Thank you for your quick replies as always.. Just one more question, since you added this:

> You should have more refined control over when to close a screen or a snack bar.
Get.back(closeOverlays: true); will close the page and the snackbar.
Get.until((_) => Get.isSnackbarOpen); it will only close the snackbar.
The only way to let a current snackbar be displayed on a new route is using Get.removeRoute().

You mention a way to close both, and a way to close only the snackbar. Could there be a way to only close the page?

Maybe that's what you meant by 

> The only way to let a current snackbar be displayed on a new route is using Get.removeRoute().

But could you elaborate?

Thanks!

**Comment by jlubeck** [comment] 2020-07-10 21:07
Also, I'm using Transition.noTransition for my routes. Could that be why it's not working for me on Web? 
I'm using Transition.cupertino on iOS and it's working fine there

**Comment by jonataslaw** [comment] 2020-07-14 09:24
Are you using Get.snackbar or Get.rawSnackbar?

**Comment by jlubeck** [comment] 2020-07-14 17:25
Get.snackbar

**Comment by jonataslaw** [comment] 2020-07-21 14:27
![Screen Capture_code-oss_20200721112253](https://user-images.githubusercontent.com/35742643/88066857-a4b8a380-cb44-11ea-91e9-3882d2863dee.gif)

As shown in the video, everything works fine on the web. Maybe you made changes in a local version and ended up facing this error, but in fact, it works normally on the web, as well as desktop, because GetX is written 100% in dart, that is, all behaviors must be the same on the web , mobile and desktop, otherwise, we would be facing a problem with Flutter and dart2js and not with Get.
In view of the fact that it was impossible to reproduce your problem, and the question of the title has been answered, I am closing this.
If you think there really is a bug, please open another issue, inserting a reproduction case, as well as the affected platform.

**Closed by jonataslaw** 2020-07-21 14:27 UTC
