### ISSUE TITLE
Obx does not work on appBar

### ISSUE THREAD

**Issue by 6643** [jonataslaw/getx#690] opened 2020-10-08 04:22 UTC
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  Get.put(Ic());

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Index(),
    );
  }
}

class Index extends StatelessWidget {
  final controller = Get.find<Ic>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: Obx(
        () => AppBar(
          actions: [if (controller.changed.value) IconButton(icon: Icon(Icons.publish), onPressed: controller.uploadData)],
        ),
      ),
      floatingActionButton: IconButton(icon: Icon(Icons.cached), onPressed: controller.changed),
    );
  }
}

class Ic extends GetxController {
  final changed = RxBool(false);

  void change() {
    changed.value = true;
  }

  void uploadData() {
    changed.value = false;
  }
}

```

**Comment by eduardoflorence** [comment] 2020-10-08 14:28
First, there is an error here
`floatingActionButton: IconButton(icon: Icon(Icons.cached), onPressed: controller.changed)`
This correct is:
`floatingActionButton: IconButton(icon: Icon(Icons.cached), onPressed: controller.change)`

Second, appBar does not accept Obx, as it is not a subtype of PreferredSizeWidget, so you can do this:
```dart
appBar: AppBar(
  actions: [
    Obx(() {
      if (controller.changed.value) return IconButton(icon: Icon(Icons.publish), onPressed: controller.uploadData);
      return SizedBox(); // Obx expects a widget in return
    })
  ],
)
```

**Comment by jonataslaw** [comment] 2020-10-09 18:10
As answered by Eduardo, appBar only accepts widgets of the PreferredSizeWidget subtype.
As this question has nothing to do with Getx, but as a basic knowledge of Flutter, I'm closing it.

**Closed by jonataslaw** 2020-10-09 18:10 UTC
Labels: invalid

**Comment by alexrainman** [comment] 2021-09-26 16:11
I am having the same problem and using @eduardoflorence solution doesn't work.

**Comment by 515445681** [comment] 2021-10-31 04:07
> > 我找到了一种方法。
> 
> I don't understand why the `preferredSize` is set to `0` , is there a way to give the `AppBar` a height based on controller state ? what property should i use to give it a height despite the parent is being set to `0` !

It can be set to other heights. 0 is what I need

**Comment by SittiphanSittisak** [comment] 2022-02-20 10:33
I can use Obx by using a globals controller.
Like this 
[](https://stackoverflow.com/questions/71192615/flutter-getx-can-obs-create-a-global-variable)

Example

File cont.dart:
Cont contGlobals = Get.put(Cont ());

class Cont extends GetxController {
  RxString var1= "".obs;
}


```
  Widget build(BuildContext context) {

    Future.delayed(
        Duration(seconds: 3), () => contGlobals .var1.value = "55555");

    return Scaffold(
      appBar: AppBar(
        actions: [Obx(() => Text(contGlobals .var1.value))]),
    );
  }
```

I hope it works for your work.

**Comment by SittiphanSittisak** [comment] 2022-02-20 10:35
try this:
```
  Widget build(BuildContext context) {
    var var1 = "".obs;

    Future.delayed(Duration(seconds: 3), () => var1.value = "55555");

    return Scaffold(
      appBar: AppBar(actions: [Obx(() => Text(var1.value))]),
    );
  }
```

**Comment by maltemedocs** [comment] 2022-02-21 08:42
@SittiphanSittisak Obx will work inside the app bar for the parameters that expect a Widget. But the issue here is that it can't encapsulate the Appbar itself. 

It's not a bug, but it's a limitation. Sad that the issue got closed, it's a valid problem.
