### ISSUE TITLE
Get incompatible with RouteAware ?

### ISSUE THREAD

**Issue by na2axl** [jonataslaw/getx#447] opened 2020-08-05 06:35 UTC
I'm facing an issue using Get on a widget with `RouteAware` implementation. The `didPush` and `didPopNext` callbacks are never fired.

1. Create a simple `StatefulWidget` page and implement the `RouteAware` class in its state
2. Launch the app and open the page
3. The page is shown, but do not fire the `didPush` event
4. Go to another page, and go back again
5. The page is shown, but do not fire the `didPopNext` event

**Expected behavior**
`RouteAware` events are fired when the page is pushed (`didPush`) and when the top route has been popped off, and the page shows up (`didPopNext`).

**Flutter Version:**
1.20.0-7.4.pre (latest beta version at this time)

**Get Version:**
3.4.2

**Used devices:**
Android emulator and PC (using Hover)

**Minimal reproduce code**
```dart
import 'package:flutter/material.dart';

class HelloPage extends StatefulWidget {
  @override
  _HelloPageState createState() => HelloPageState();
}

class _HelloPageState extends State<HelloPage> with RouteAware {
  @override
  void didPush() {
    print("did push");
  }

  @override
  void didPopNext() {
    print("did pop next");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text("Hello World"),
      ),
    );
  }
}
```

**Side notes**
- The code sample works when using Flutter without Get
- Sorry if I'm doing something wrong here, I'm new to Get 😁

**Comment by jonataslaw** [comment] 2020-08-09 22:33
Works normally:

```dart
import 'package:flutter/material.dart';
import 'package:get/route_manager.dart';

RouteObserver<PageRoute> routeObserver = RouteObserver<PageRoute>();

void main() {
  runApp(GetMaterialApp(
    title: 'Navigation Test',
    home: StartWidget(),
    navigatorObservers: <NavigatorObserver>[routeObserver],
  ));
}

class StartWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Start'),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            RaisedButton(
              child: Text('Open FirstWidget'),
              onPressed: () {
                Get.to(FirstWidget());
              },
            ),
          ],
        ),
      ),
    );
  }
}

class FirstWidget extends StatefulWidget {
  @override
  _FirstWidgetState createState() => _FirstWidgetState();
}

class _FirstWidgetState extends RouteAwareState<FirstWidget> {
  Widget build(BuildContext context) {
    print("build $widget");
    return Scaffold(
      appBar: AppBar(
        title: Text('FirstWidget'),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            RaisedButton(
              child: Text('Open SecondWidget'),
              onPressed: () {
                Get.to(SecondWidget());
              },
            ),
            RaisedButton(
              child: Text('back'),
              onPressed: () {
                Get.back();
              },
            ),
          ],
        ),
      ),
    );
  }
}

class SecondWidget extends StatefulWidget {
  @override
  _SecondWidgetState createState() => _SecondWidgetState();
}

class _SecondWidgetState extends RouteAwareState<SecondWidget> {
  @override
  Widget build(BuildContext context) {
    print("build $widget");
    return Scaffold(
      appBar: AppBar(
        title: Text('SecondWidget'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('back'),
          onPressed: () {
            Get.back();
          },
        ),
      ),
    );
  }
}

abstract class RouteAwareState<T extends StatefulWidget> extends State<T>
    with RouteAware {
  @override
  void didChangeDependencies() {
    print("didChangeDependencies $widget");
    routeObserver.subscribe(this, ModalRoute.of(context)); //Subscribe it here
    super.didChangeDependencies();
  }

  @override
  void didPush() {
    print('didPush $widget');
  }

  @override
  void didPopNext() {
    print('didPopNext $widget');
  }

  @override
  void didPop() {
    print('didPop $widget');
  }

  @override
  void didPushNext() {
    print('didPushNext $widget');
  }

  @override
  void dispose() {
    print("dispose $widget");
    routeObserver.unsubscribe(this);
    super.dispose();
  }
}

```

It looks like you're missing a few steps on how to use it.

Note that you can use NavigatorObservers which has a more current API, or even the GetMaterialApp routingCallback to observe changes in the route.
As this is a question, it is not an issue, nor does it have a case of reproducing a problem, I am closing this.

**Closed by jonataslaw** 2020-08-09 22:33 UTC

**Comment by axu6705** [comment] 2020-12-26 01:59
@jonataslaw How to use RouteAware in GetView.

**Comment by Edorin9** [comment] 2021-02-26 19:27
can this be done in a GetXController to simulate an Android Activity's onResume?

**Comment by eduardoflorence** [comment] 2021-02-26 23:04
> can this be done in a GetXController to simulate an Android Activity's onResume?

Use `FullLifeCycleController` of the GetX:
https://gist.github.com/eduardoflorence/d918d05ad71175b52c2aca95588c305d

**Comment by Edorin9** [comment] 2021-02-27 00:09
I've tried your example, the mandatory overrides are being called, onResume is called when getting back to the app from background to foreground but not the optional ones. 

I'm specifically trying to capture the Android Activity's onResume when the page shows up again from navigating back (in this case navigating back from cities to home). I'm trying to achieve that by listening for didPop() and getting the previous route like so:
```
@override
  Future<bool> didPopRoute() {
    print('didPopRoute');
    if (Get.routing.previous == "/city") print("page resumed");
    return super.didPopRoute();
  }
```

However, it looks like it's not implemented yet since it has a static return: (as copied from actual getx source)
```
Future<bool> didPopRoute() => Future<bool>.value(false);```

Am I right?

**Comment by eduardoflorence** [comment] 2021-02-27 14:11
`didPopRoute` is triggered when we are on the first page of the App and we press the Android back button, causing the App to close
