### ISSUE TITLE
Theme not applied in get 4.1.3

### ISSUE THREAD

**Issue by psrcek** [jonataslaw/getx#1290] opened 2021-04-06 12:03 UTC
**Describe the bug**
The theme argument of GetMaterialApp is completely ignored in GetX 4.1.3.

**Reproduction code**

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.green,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('GetX bug'),
      ),
      body: Center(
        child: Text('The app bar of this app should be green.'),
      ),
    );
  }
}
```

**To Reproduce**
1. Run the app
2. Observe GetX completely ignoring the theme.
3. Change `GetMaterialApp` to `MaterialApp`.
4. The theme now works correctly.

**Expected behavior**
I expected theming to work.

**Screenshots**
![Screenshot_20210406-135720](https://user-images.githubusercontent.com/13370323/113707722-97e2dc80-96e0-11eb-9a30-a16741bca5ec.jpg)

**Flutter Version:**
Channel stable, 2.0.1

**Getx Version:**
4.1.3

**Describe on which device you found the bug:**
Device independent, but Samsung galaxy A51 if you want a concrete device.

**Comment by eduardoflorence** [comment] 2021-04-06 12:14
Duplicate of #1281

**Closed by eduardoflorence** 2021-04-06 12:14 UTC
