### ISSUE TITLE
A bug about dialog page jump to navigator page

### ISSUE THREAD

**Issue by gneL1** [jonataslaw/getx#1209] opened 2021-03-18 07:59 UTC
**Describe the bug**
&emsp;&emsp;Now I'm in **PageA** , and I use `Get.dialog()` to open **PageB** , it's good. Then I use a button of **PageB** with method `Get.to()` to open **PageC** , in first time I can open **pageC** successfully . But next , I close **pageC** and use the button of **PageB** to open **pageC** again , it does'nt work , this means I can't open a navigator page from a dialog page more than once.

example:
* **Page A**  
```dart
class PageA extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page A'),
      ),
      body: Center(
        child: TextButton(
          child: Text('Open PageB'),
          onPressed: () {
            //open a dialog page
            Get.dialog(PageB());
          },
        ),
      ),
    );
  }
}
```

* **Page B**  
```dart
class PageB extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Material(
        child: Container(
          width: 500,
          height: 300,
          decoration: BoxDecoration(
            color: Colors.white,
            border: Border.all(
              color: Colors.grey
            )
          ),
          child: Column(
            children: [
              Text('Page B',style: TextStyle(fontSize: 28),),
              Expanded(
                flex: 1,
                child: Center(
                  child: TextButton(
                    child: Text('Open PageC'),
                    style: ButtonStyle(backgroundColor: MaterialStateProperty.all(Colors.tealAccent)),
                    onPressed: () {
                      // open a navigator page
                      Get.to(PageC());
                    },
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```

* **Page C**  
```dart
class PageC extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page C'),
      ),
      body: Center(
        child: Text('Page C'),
      ),
    );
  }
}
```

**Getx Version:**
&emsp;&emsp;`get: ^3.26.0`

**Comment by jonataslaw** [comment] 2021-03-24 11:21
Duplicate of https://github.com/jonataslaw/getx/issues/653

**Closed by jonataslaw** 2021-03-24 11:21 UTC
