### ISSUE TITLE
After adding get in my project it showing error

### ISSUE THREAD

**Issue by Prantik335** [jonataslaw/getx#777] opened 2020-11-09 02:38 UTC
I recently upgraded flutter. After upgrading, when I going to use **Get** it's showing down error.
without adding **get** my project work fine.

>**Codes**
```
import 'package:flutter/material.dart';
import 'package:flutterfire_auth/src/homepage.dart';
import 'package:get/get.dart';

void main() {
  return runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter App',
      debugShowCheckedModeBanner: false,
      home: Homepage(),
    );
  }
}

 ```

>**errors**

```Restarted application in 78ms.
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/get-3.15.0/lib/get_navigation/src/extension_navigation.dart:235:37: Error: No named parameter with the name 'shadowThemeOnly'.
    final theme = Theme.of(context, shadowThemeOnly: true);
                                    ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
```

>**A solution**
I tried to solve this problem. so I delete_shadowThemeOnly: true_ this parameter.
After doing this **Get** is working fine in my project

**Comment by eduardoflorence** [comment] 2020-11-09 03:10
Duplicate of #762

**Comment by jonataslaw** [comment] 2020-11-09 04:21
Thanks @eduardoflorence 
Duplicate of https://github.com/jonataslaw/getx/issues/762

**Closed by jonataslaw** 2020-11-09 04:21 UTC
