### ISSUE TITLE
Get.to not work some where in release mode

### ISSUE THREAD

**Issue by navidonline** [jonataslaw/getx#324] opened 2020-07-01 07:44 UTC
when use Get.to for open a screen in release mode its not work and show error in log: 
`Another exception was thrown: Instance of 'ErrorSummary'`
this problem exist in version (3.1.4)
ver 2.14.1 work perfectly

**Comment by jonataslaw** [comment] 2020-07-01 08:05
I just tested on a physical device, and it worked normally.
Please check your code and your other libraries, or provide a reproduction case.

**Comment by ahmedmirza994** [comment] 2020-07-01 11:36
I have the same issue, Get.to not working on release mode on some screen, not all screens

**Comment by Nipodemos** [comment] 2020-07-01 18:23
@ahmedmirza994 as jonatas said:
Please check your code and your other libraries, or provide a reproduction case.

**Comment by jonataslaw** [comment] 2020-07-01 18:31
There are several recent bugs open in Flutter about this, most are about using dart: io on the web.
So maybe this may be unrelated to Get.
Anyway, I do not rule out that it could be a bug (which would be very difficult, since from one version to another I have not changed anything in Get.to), but I definitely need a reproduction code, otherwise I will not be able to proceed with this issue.

**Comment by jonataslaw** [comment] 2020-07-03 15:35
Without a reproduction case, it will not be possible to proceed with this issue, since in tests (which also uses the build in the 3 modes) everything works as expected.
I made a case of real reproduction and it also works as expected.
Perhaps a flutter clean to eliminate cache of old builds can solve your problem. If you believe that this is not something with your project, please provide a reproduction case.
Closing it.

**Closed by jonataslaw** 2020-07-03 15:35 UTC
Labels: Waiting for customer response

**Comment by ahmedmirza994** [comment] 2020-07-08 13:05
With debug mode, I get this route

I/flutter (30108): [GOING TO ROUTE] /
I/flutter (30108): [GOING TO ROUTE] /signupscreenv2
I/flutter (30108): [GOING TO ROUTE] /signupform

But in release mode when I push from home screen to signupscreen
I/flutter (31103): [GOING TO ROUTE] /widget

and route not working. if i replace GEt.to with material page route then it is working
