### ISSUE TITLE
Transition not working correctly

### ISSUE THREAD

**Issue by haophan1996** [jonataslaw/getx#1675] opened 2021-07-22 20:07 UTC
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
version getx 4.1.4 or below, it works fine, but after upgrade 4.2.0 and up, transition not working correctly
here is the video
https://www.youtube.com/watch?v=XTEzGcGDdik

As user pop gesture back, the child behind not moving 

Is there something I can make animation 4.2.0 works like 4.1.0

**Comment by sejun2** [comment] 2021-07-23 08:57
May I see your code please? Thank you

**Comment by haophan1996** [comment] 2021-07-23 18:47
> May I see your code please? Thank you

yes, here is the Main.dart
`class MyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      defaultTransition: Transition.cupertino,
      transitionDuration: Duration(milliseconds: 200),
      translations: Language(),
      locale: GlobalController.i.langList.elementAt(GlobalController.i.userStorage.read('lang')),
      theme: Themes().lightTheme,
      darkTheme: Themes().darkTheme,
      initialRoute: "/HomePage",
      getPages: [
        GetPage(name: "/HomePage", page: () => HomePageUI(), popGesture: true, binding: HomeBinding(), maintainState: false),
        GetPage(name: "/ThreadPage", page: () => ThreadUI(), popGesture: true, binding: ThreadBinding(), maintainState: false),`

**Comment by sejun2** [comment] 2021-07-27 03:10
I can't reproduce your issue. Every version of getX represent that the child do not move when I pop.
Here is my practice code to reproduce your issue.
https://github.com/sejun2/transition_issue_1675

**Comment by jonataslaw** [comment] 2021-07-27 03:51
Hi, I can't reproduce this in the latest version, please update GetX, and see if you don't set showCupertinoParallax: false, in GetPage.
It could be that the behavior was false by default in some transitional version, but if you update to last, the default is true

**Comment by haophan1996** [comment] 2021-07-27 04:02
> Hi, I can't reproduce this in the latest version, please update GetX, and see if you don't set showCupertinoParallax: false, in GetPage.
> It could be that the behavior was false by default in some transitional version, but if you update to last, the default is true



> I can't reproduce your issue. Every version of getX represent that the child do not move when I pop.
> Here is my practice code to reproduce your issue.
> https://github.com/sejun2/transition_issue_1675

Thank you for helping me, I think in the lastest update, the problem fix, :)))))))

**Comment by jonataslaw** [comment] 2021-07-27 04:14
Based on your comment, I'm closing this

**Closed by jonataslaw** 2021-07-27 04:14 UTC
