### ISSUE TITLE
getController onInit method  only called  one  time ,so if we have different params, we could not make a different request

### ISSUE THREAD

**Issue by wangxingxing123654** [jonataslaw/getx#1429] opened 2021-05-14 09:21 UTC

**Comment by wangxingxing123654** [comment] 2021-05-14 09:29
pageA  ( params {a:1,b:2})--- > pageB ,
pageBController onInit called firstime ,and get the params ,make a request.

and the back to pageA, with another  ( params {c:1,d:2})--- > pageB ,
pageBController onInit not called,

**Comment by KevinZhang19870314** [comment] 2021-05-14 10:50
When you push a route, you are just stacking a route up, the route below is still there in the stack.
That way you are not opening a screen again, but just removing the view above it.
Life cycles are called only once, since it is the same controller. 
This is expected behavior.

**Comment by wangxingxing123654** [comment] 2021-05-15 05:45
so there is any solutions to solve the problem? getx  send api with different params

**Comment by KevinZhang19870314** [comment] 2021-05-18 02:47
One method is when you back to pageA, remove the pageB from the widget stack trees. Another method is before you navigate to pageB, make the request and observe the response data, and then in you page you can obx the data.

**Comment by jonataslaw** [comment] 2021-05-18 20:29
This is expected behavior, and you shouldn't have a problem with it unless you are using the resources in the wrong way.
1- Different pages must use different controllers. Unless you have only one source of truth for the same pages, immutable you should not have a single controller.
2- If you are opening two equal routes and need different controllers, you must use Get.create or tags to provide another controller for it, and so onInit will be called again.
3- If you do not need more than one route, be sure to close the route with the current controller before opening a new route.

**Comment by roipeker** [comment] 2021-05-25 00:57
Closing the issue for the explanations provided, if you think this is a bug or more info has to be added to the docs, please reopen.

**Closed by roipeker** 2021-05-25 00:57 UTC
Labels: expected behavior

**Comment by niamulhasan** [comment] 2023-12-27 06:54
Most Probably youre pushing same (duplicate) route in the routing stack. That's the default behavior of Getx routing. If you want to push duplicate route in the routing stack, and still want them to be different. use `preventDuplicates: false` in the argument. 

example:
```dart
Get.toNamed(Routes.TOPICS, arguments: arguments, preventDuplicates: false);
```
