### ISSUE TITLE
Error: Type 'ui.Window' not found.

### ISSUE THREAD

**Issue by IsmailAlamKhan** [jonataslaw/getx#809] opened 2020-11-22 21:41 UTC
```
Downloading Web SDK...
Running "flutter pub get" in client...
Launching lib\main.dart on Chrome in debug mode...
lib\main.dart:1
/C:/Users/mdism/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/get-3.17.1/lib/get_navigation/src/extension_navigation.dart:1047:3: Error: Type 'ui.Window' not found.
  ui.Window get window => ui.window;
  ^^^^^^^^^
Failed to compile application.
Exited (sigterm)
```
flutter doctor
```
[flutter] flutter doctor -v
[√] Flutter (Channel master, 1.24.0-8.0.pre.344, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.24.0-8.0.pre.344 at D:\development\flutter_master\flutter
    • Framework revision de56c6ad72 (71 minutes ago), 2020-11-23 05:28:06 +0900
    • Engine revision 23a8e027db
    • Dart version 2.12.0 (build 2.12.0-62.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\mdism\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30128.74
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\mdism\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.41

• No issues found!
exit code 0
```
Get version `3.17.1`

**Comment by eduardoflorence** [comment] 2020-11-23 00:39
Duplicate of #804

**Closed by eduardoflorence** 2020-11-23 00:39 UTC
