### ISSUE TITLE
GetxControllers methods (onInit, onReady, onClose) are not called when navigating to a previously rendered page

### ISSUE THREAD

**Issue by jedidas** [jonataslaw/getx#1046] opened 2021-01-31 23:06 UTC
**Describe the bug**
When starting to navigate between the different pages, when navigating to a previously loaded page the controller methods are not called. So you cannot reset controller values.

**Reproduction code**
[https://github.com/jedidas/GetX-navigation-example-issue](Example)

example:

**To Reproduce**
The application has a timer and automatically navigates between the pages.
You can navigate using the drawer menu to any page.

**Expected behavior**
The controller methods (onInit, onReady, onClose) are called when the view is loaded every time and not only the first time.

**Screenshots**
![image](https://user-images.githubusercontent.com/23466093/106400353-8846cf00-63e3-11eb-80f7-8c7fd4f03191.png)

In navigation, when navigating to a view that has already been rendered the controller methods (onInit, onReady, onClose) are not called again.
![image](https://user-images.githubusercontent.com/23466093/106400262-ec1cc800-63e2-11eb-8a80-819f7192aed0.png)

**Flutter Version:**
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (7 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

**Getx Version:**
get: ^3.24.0

**Describe on which device you found the bug:**
Virtual device Pixel_2_API_28

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by bus710** [comment] 2021-02-08 02:28
Seems like the link of reproduction code is not available. 
Can you share a block of your code - especially in the build method of page side?

**Comment by eduardoflorence** [comment] 2021-02-09 17:55
The expected behavior for onInit, onReady and onClose is to be called only once. You can create a method called `init` and call it in your View's build method

**Comment by jonataslaw** [comment] 2021-02-13 16:57
Okay, it seems to me that you don't really understand how Stacks works.
Flutter, unlike the native android that works with activitys, for example, works with Stacks.
When you push a route, you are just stacking a route up, the route below is still there in the stack.
That way you are not opening a screen again, but just removing the view above it.
Life cycles are called only once, since it is the same controller.
This is expected behavior, so I'm closing this.

**Closed by jonataslaw** 2021-02-13 16:57 UTC
Labels: expected behavior
