### ISSUE TITLE
"Get.toNamed" does not work when pressing the button from the second time on the Modal Bottom Sheet after "Get.back" from the Page

### ISSUE THREAD

**Issue by mrhungnq95** [jonataslaw/getx#898] opened 2020-12-11 18:01 UTC
**Describe the bug**

When I use **"Get.toNamed(Routes.TAKE_CAMERA)"** to open a new page from the Modal Bottom Sheet, then use **"Get.back**" to close that screen, I cannot open that screen again. If using **"Get.toNamed(Routes.TAKE_CAMERA)"** with the parameter  **preventDuplicates = false** or **"Navigator.of(c).pushNamed(Routes.TAKE_CAMERA)"** then everything works

**Reproduction code

**/// Show bottom sheet**
```
 void openBottomSheet() {
    Get.bottomSheet(BottomSheetView(), isDismissible: false);
  }
```

**/// Bottom sheet - content view**
```
class BottomSheetView extends GetView<AController> {
  const BottomSheetView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Obx(() => SizedBox(
          height: 145,
          child: ListView.builder(
            scrollDirection: Axis.horizontal,
            itemBuilder: (context, index) {
              final image = controller.rxData[index];
              return Padding(
                padding: const EdgeInsets.only(right: kHorizontalSpaceSmall),
                child: PickImageView(
                    title: "",
                    canRemoveFileSelected: !image.isNewTakePicture,
                    fileSelected: image.filePath,
                    onRemoveTapped: () {},
                    onPressed: () {
                       Get.toNamed(Routes.TAKE_CAMERA);
                    },
                    type: EPickImageViewType.gallary),
              );
            },
            itemCount: controller.rxData.length,
          ),
        ));
  }
}
```

**/// Take camera page**
```
class TakeCameraView extends GetView<CameraController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColor.black,
      body: FutureBuilder<List<CameraDescription>>(
        future: availableCameras(),
        builder: (context, snapShot) {
          if (snapShot.connectionState == ConnectionState.done) {
            return CameraView(
              cameras: snapShot.data,
              onCaptured: () {
                Get.back();
              },
            );
          }
          return SizedBox();
        },
      ),
    );
  }
}
```

GetX version: **get: ^3.22.2**

Flutter version:
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-VN)
    • Flutter version 1.22.4 at /Volumes/DATA/Software/SDK/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

**Comment by jonataslaw** [comment] 2020-12-11 18:04
Duplicate of https://github.com/jonataslaw/getx/issues/514

**Closed by jonataslaw** 2020-12-11 18:04 UTC

**Comment by mrhungnq95** [comment] 2020-12-11 18:15
> Duplicate of #514

Can you explain to me why not, even though I have closed that screen before.

**Comment by jonataslaw** [comment] 2020-12-11 21:14
https://github.com/jonataslaw/getx/issues/514#issuecomment-682079037

GetX prevent acidental push to screen twice. Use "preventDuplicates:false" to avoid this behaviour
