### ISSUE TITLE
Failed assertion: line 3150 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by jlubeck** [jonataslaw/getx#286] opened 2020-06-24 20:21 UTC
**Describe the bug**
After upgrading Get to 3.0.0beta I'm getting this error when calling `Get.offNamedUntil`

```

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3150 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:3150:12)
#3      NavigatorState.pushNamedAndRemoveUntil (package:flutter/src/widgets/navigator.dart:3303:34)
#4      GetImpl.offNamedUntil (package:get/src/get_main.dart:99:10)
#5      Header.build.<anonymous closure>.<anonymous closure> (package:rpm/ui/header.dart:91:15)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:953:19)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#87695
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(956.0, 40.5)
  finalLocalPosition: Offset(7.8, 1.5)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Flutter Version:**
 Flutter (Channel beta, 1.19.0-4.1.pre

**Get Version:**
3.0.0beta

**Describe on which device you found the bug:**
iPad

**Comment by jonataslaw** [comment] 2020-06-24 20:31
Could you please show the method in which you are calling it?
The code indicates that the build method is being called simultaneously, so I need to know who is calling the build to know where the error is.

**Comment by jlubeck** [comment] 2020-06-24 20:53
Ok, I was able to replicate the issue:

```dart
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Medek RPM',
      initialRoute: '/test2',
      getPages: [
        GetPage(
          name: '/test2',
          page: () => Test2Screen(),
        ),
        GetPage(
          name: '/test2second',
          page: () => Test2SecondScreen(),
        ),
      ],
    );
  }
}

class Test2Screen extends StatefulWidget {
  @override
  _Test2ScreenState createState() => _Test2ScreenState();
}

class _Test2ScreenState extends State<Test2Screen> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    Get.toNamed('/test2second');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          child: FlatButton(
            child: Text('Test'),
            onPressed: () {
              Get.toNamed('/test2second');
            },
          ),
        ),
      ),
    );
  }
}

class Test2SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          child: HeaderButton(
            text: 'Logout',
            onTap: () {
              Get.offNamedUntil('/test2', (Route route) {
                return route.settings.name == '/test2';
              });
            },
          ),
        ),
      ),
    );
  }
}


```

**Comment by jonataslaw** [comment] 2020-06-24 21:09
I tested his example and was able to confirm that it works properly. In this example you placed a route in initState, which is prohibitive by Flutter, since initState is before the build, and you cannot go to another route without the current build being called.
If you have snackbars in initState, use instantInit = false, and you will not face these problems, but with routes, everything is normal, apparently.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Medek RPM',
      initialRoute: '/test2',
      getPages: [
        GetPage(
          name: '/test2',
          page: () => Test2Screen(),
        ),
        GetPage(
          name: '/test2second',
          page: () => Test2SecondScreen(),
        ),
      ],
    );
  }
}

class Test2Screen extends StatefulWidget {
  @override
  _Test2ScreenState createState() => _Test2ScreenState();
}

class _Test2ScreenState extends State<Test2Screen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          child: FlatButton(
            child: Text('Test'),
            onPressed: () {
              Get.toNamed('/test2second');
            },
          ),
        ),
      ),
    );
  }
}

class Test2SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          child: FlatButton(
            child: Text('dsids'),
            onPressed: () {
              Get.offNamedUntil('/test2', (Route route) {
                return route.settings.name == '/test2';
              });
            },
          ),
        ),
      ),
    );
  }
}

```

**Comment by jlubeck** [comment] 2020-06-24 21:29
Yes, I'm aware the problem lies with calling the route on initState, but that worked fine in your previous version of Get. 

The way I'm using it is on the login screen, if the user is already logged in, it goes to the home screen.

**Comment by jonataslaw** [comment] 2020-06-24 21:40
I don't know how this was possible in previous versions, but I think you now have better ways to do this.
Since GetRoute receives a role, you can decide which page to deliver in that role.
You can also use Get_storage to store the user's status, and decide synchronously which route to go to.

**Comment by jlubeck** [comment] 2020-06-24 21:48
Unfortunately I can't change the architecture now. If I can't call a route on initState by design, then feel free to close this issue.

Right now, i solved it by using 

```dart
Future.delayed(Duration(milliseconds: 100), () {
    Get.toNamed('/test2second');
});
```

**Comment by jonataslaw** [comment] 2020-06-24 21:56
This is the approach officially recommended by the Flutter team.

```dart
 WidgetsBinding.instance
        .addPostFrameCallback((_) => Get.toNamed('/test2second'));
```
You do not need to allocate a time, only if it is within a Future method it will automatically run it at the end of the build.
```dart
Future.delayed(Duration.zero, () {
    Get.toNamed('/test2second');
});
```

**Comment by jonataslaw** [comment] 2020-06-24 22:45
As this is expected behavior, derived from Flutter itself, I am closing this. If you face problems, do not hesitate to open another issue.

**Closed by jonataslaw** 2020-06-24 22:45 UTC
