### ISSUE TITLE
How make sure that GetMaterialController has been initialized BEFORE running whatever else code?

### ISSUE THREAD

**Issue by loicgeek** [jonataslaw/getx#364] opened 2020-07-09 23:15 UTC
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
I would like to initialize my auth controller, but before I want to make sure GetMaterialController has been initialized.

**To Reproduce**
1.Install Get package
2.Create AuthCtroller extending GetxController
3. Initialize AuthController before returning GetMaterialApp

**Expected behavior**
output "GetMaterialController has been initialized" before "AuthController has been initialized"

**Flutter Version:**
1.17.5

**Get Version:**
3.2.0

**Describe on which device you found the bug:**
Samsung Galaxy J3

**Minimal reproduce code**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:myapp/auth/auth.controller.dart';


void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final AuthController authController =
      Get.put<AuthController>(AuthController());
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Todo App with Get Package',
      defaultTransition: Transition.rightToLeft,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        appBarTheme: AppBarTheme(
          elevation: 0,
        ),
      ),
      initialRoute: "/splashscreen",
      getPages: AppRoutes.routes,
    );
  }
}
 ```

**Comment by Nipodemos** [comment] 2020-07-10 00:10
When it is said "minimal reproduce code" it means a code that anyone can copy and paste e have the error that you are having.
But the way you posted we can't test.

jonatas problably will see the error by just looking at the code, but it would be nice to be able to test

**Comment by jonataslaw** [comment] 2020-07-10 01:56
Hi, controllers start up as soon as they are used for the first time, regardless of where they are.
I read the related issue, and her problem is another. You are forcing a push before GetMaterialApp is started.

Setting up the project with firebase takes time, and unfortunately I don't have that time now, but with no guarantee of working, I would recommend you to override this method in onReady instead of onInit to make sure that the push will only be called after the GetMaterialApp is initialized.

https://github.com/loicgeek/todo_getx/blob/master/lib/auth/auth.controller.dart#L21

**Comment by ghprod** [comment] 2020-07-10 02:55
maybe put this code on `main()` ?

```dart
main() {
  ...

   Get.put<AuthController>(AuthController());
  ...
}

```

**Comment by jonataslaw** [comment] 2020-07-21 14:31
Please provide a reproduction case for this issue, otherwise it may be closed.

**Comment by joanofdart** [comment] 2020-07-21 18:44
Arent Bindings supposed to be run before anything else? I'm a bit confused because I also have the same issue 🤔 
I want to run a check before getmaterialapp but initialBinding is not working either.

**Comment by jonataslaw** [comment] 2020-07-27 08:47
Without a reproduction case, it became possible to continue with this issue.
Closing.

**Closed by jonataslaw** 2020-07-27 08:47 UTC
Labels: Waiting for customer response

**Comment by hirakhax** [comment] 2021-12-27 18:51
My controllers are not getting created. I am not able to understand what is happening

`void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await GetStorage.init();

  Get.put(AuthController());
  Get.put(ReposController());
  Get.put(BottomNavigationController());
  Get.put(VideosController());

  runApp(const App());
}`

Log:
`[GETX] Instance "AuthController" has been created
[GETX] Instance "AuthController" has been initialized
[GETX] Instance "ReposController" has been created
[GETX] Instance "ReposController" has been initialized
E/flutter ( 3119): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: "VideosController" not found. You need to call "Get.put(VideosController())" or "Get.lazyPut(()=>VideosController())"
E/flutter ( 3119): #0      GetInstance.find
package:get/…/src/get_instance.dart:305
E/flutter ( 3119): #1      Inst.find
package:get/…/src/extension_instance.dart:69
E/flutter ( 3119): #2      new HomePage
package:tokbee/…/pages/home_page.dart:12
E/flutter ( 3119): #3      new BottomNavigationController
package:tokbee/…/controllers/bottom_navigation_controller.dart:11
E/flutter ( 3119): #4      main
package:tokbee/main.dart:17
E/flutter ( 3119): <asynchronous suspension>
E/flutter ( 3119):`
