### ISSUE TITLE
Get.width not give the current width size in flutter web .

### ISSUE THREAD

**Issue by SamerOrfali** [jonataslaw/getx#1231] opened 2021-03-23 23:53 UTC
**Describe the bug**

Get.width not give the current width size in flutter web but MediaQuery.of(context).size.widrg Working

**Expected behavior**

Fix it please we don't want to use context !

**Flutter Version:**

Flutter 2.0.3

**Getx Version:**

get: ^3.26.0

**Describe on which device you found the bug:**

flutter web

**Comment by jonataslaw** [comment] 2021-03-24 11:11
Duplicate of https://github.com/jonataslaw/getx/issues/786#issuecomment-725856139 (look at Eduardo's comment)

**Closed by jonataslaw** 2021-03-24 11:11 UTC
