### ISSUE TITLE
Getx Flutter - Updating item in list is not reactive

### ISSUE THREAD

**Issue by SivaramNalliboyana** [jonataslaw/getx#1148] opened 2021-03-04 09:36 UTC
**I am using getx as my statemanagment for my flutter app. But I am having difficulties by updating the values in a list. So I have a usermodel with a parameter of isFollowing. When I click on a button the isFollowing variable shall change and the color should be updated. But it is not happening. I am using Obx as my widget, as I already injected the state at the beginning. It is all working fine with fetching the data and displaying it on the frontend. But when I wanna change the values in my list, it is not updating. My minimal reproducible example. **

**HomeController**

```dart
class HomeController extends GetxController {
  var userslist = List<User>().obs;

  @override
  void onInit() {
    fetchUsers();
    super.onInit();
  }

  void fetchUsers() async {
    var users= await ApiService().getapidata('${usersurl}feed');
    if (users!= null) {
      userslist.value= users;
    }
  }
}
```

**Model**
```dart
class User {
  User({
    this.id,
    this.user_name,
    this.profile_picture,
    this.isFollowing,
  });

  int id;
  String user_name;
  String profile_picture;
  bool isFollowing;


  factory User.fromJson(Map<String, dynamic> json) => User(
        id: json["id"],
        user_name: json["user_name"],
        profile_picture: json["profile_picture"],
        isFollowing: json["is_following"],
      );
```
**HomePage**
```dart
class HomeScreen extends StatelessWidget {
  final HomeController homeController = Get.put(HomeController());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        physics: ScrollPhysics(),
        child: Obx(
          () => ListView.builder(
            shrinkWrap: true,
            physics: NeverScrollableScrollPhysics(),
            itemCount: homeController.usersList.length,
            itemBuilder: (context, index) {
              return UserWidget(homeController.usersList[index], index);
            },
          ),
        ),
      ),
    );
  }
}
```
**UserWidget**
```dart
class UserWidget extends StatelessWidget {
  final User user;
  final int index;
  UserWidget (this.user, this.index);
  @override
  Widget build(BuildContext context) {
    return InkWell(
        onTap : ()=> user.isFollowing = true // When I click on this the container it  shall be updated to yellow
        child: Obx( () => Container(
        decoration: const BoxDecoration(color: user.isFollowing ? Colors.yellow : Colors.black ), // Here is the update I wanna make
      ))
    );
  }
}
```

**Comment by mjablecnik** [comment] 2021-03-04 10:55
Your User objects in the List must be Rx<User> objects for reactive changes.
Try change you code some like this:
```
  void fetchUsers() async {
    var users= await ApiService().getapidata('${usersurl}feed');
    if (users!= null) {
      userslist.value= users.map((item) => item.obs)
    }
  }
```

**Comment by jonataslaw** [comment] 2021-03-04 16:25
duplicate of https://github.com/jonataslaw/getx/issues/615

**Closed by jonataslaw** 2021-03-04 16:25 UTC

**Comment by SivaramNalliboyana** [comment] 2021-03-04 20:47
Hi Jonatas, when I refer to the duplicate  question , I cant still implement it. As it is saying, Improper use of getx or obx has been detected. Could you provide an example with the code I have given please.

**Comment by jonataslaw** [comment] 2021-03-04 21:38
`var userslist = List<Rx<User>>().obs; // you need a list of reactive model. The correct is use literal: <Rx<User>>[]
`
Update the inner variable:

```
   return InkWell(
        onTap : ()=> user.update(()=> user.isFollowing = true); // When I click on this the container it  shall be updated to yellow
        child: Obx( () => Container(
        decoration: const BoxDecoration(color: user.isFollowing ? Colors.yellow : Colors.black ), // Here is the update I wanna make
      ))
```

**Comment by SivaramNalliboyana** [comment] 2021-03-04 22:02
Thank you sooo much, finally it is working . I was stuck with this problem since 2 days

**Comment by kamike** [comment] 2021-03-08 10:34
list.value    list.assignAll
