### ISSUE TITLE
Debounce not working properly

### ISSUE THREAD

**Issue by JCKodel** [jonataslaw/getx#549] opened 2020-09-01 21:39 UTC
**Describe the bug**
Debouncer is not working properly.
I have a `TextEditingController` with an listener to write changes to disk:

```dart
@override
void initState() {
  super.initState();
  _displayNameTextEditingController = TextEditingController(text: FirebaseAuth.instance.currentUser.displayName);
  _displayNameTextEditingController.addListener(_onDisplayNameChanged);
}

void _onDisplayNameChanged() {
  final userController = Get.find<UserController>();

  print("Text has changed");

  if (userController.currentUser.value.displayName == _displayNameTextEditingController.value.text) {
    print("But it is equal to the model value, so ignoring it...");
    return;
  }

  userController.updateUser((u) => u.displayName = _displayNameTextEditingController.value.text);
}
```

On `updateUser`, I save it to the disk and update the firebase user (a remote call):

```dart
Future<void> updateUser(void Function(User) updater) async {
  currentUser.update(updater);

  debounce(currentUser, (value) async {
    final fbUser = fba.FirebaseAuth.instance.currentUser;

    await userStore.save(currentUser.value, currentUser.value.id);
    await fbUser.updateProfile(displayName: currentUser.value.displayName, photoURL: currentUser.value.photoURL);
  });
}
```

The `userStore.save` has a log starting with 🟧 (meaning: the data was actually written to disk).

This is my log after 1 keystroke:
```
I/flutter (13017): Text has changed
I/flutter (13017): But it is equal to the model value, so ignoring it...
I/flutter (13017): Text has changed
```

Focus triggers the TextEditingController (but the first one is ignored because the text itself didn't change).
Then, a save is triggered (but the bounce just freezes, no data is actually written to the disk).

Now, clearing the log and pressing another key:
```
I/flutter (13017): Text has changed
I/flutter (13017): Text has changed
I/flutter (13017): But it is equal to the model value, so ignoring it...
I/flutter (13017): 🟧 user::4FuJiTZREfYhNHylSCX8rShpIei1
I/flutter (13017): 🟧 user::4FuJiTZREfYhNHylSCX8rShpIei1
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
```

The code that was supposed to bounce is now executed twice.
Pressing another key:

```
I/flutter (13017): Text has changed
I/flutter (13017): 🟧 user::4FuJiTZREfYhNHylSCX8rShpIei1
I/flutter (13017): 🟧 user::4FuJiTZREfYhNHylSCX8rShpIei1
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
I/flutter (13017): 🟧 user::4FuJiTZREfYhNHylSCX8rShpIei1
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
I/flutter (13017): 🟧 user::4FuJiTZREfYhNHylSCX8rShpIei1
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
I/BiChannelGoogleApi(13017): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7167582
```

Now the code run 4 times O.o

**Expected behavior**
The 🟧 log should appear once in the log for each keystroke (given they take more than 800ms)

**Flutter Version:**
1.20.2

**Getx Version:**
3.7.0

**Describe on which device you found the bug:**
Android emulator

**Comment by jonataslaw** [comment] 2020-09-01 22:16
Workers must be on `onInit`, `constructor of Controller`, or `initState`.
It doesn't matter if the data will arrive later, the moment it is declared, they will observe that variable until it is available.
Quickly looking at your reproduction code, the updateUser function is called whenever a key is pressed.
In this way, a new Worker is created.
Your problem can be solved simply by changing this code:

```dart
debounce(currentUser, (value) async {
    final fbUser = fba.FirebaseAuth.instance.currentUser;

    await userStore.save(currentUser.value, currentUser.value.id);
    await fbUser.updateProfile(displayName: currentUser.value.displayName, photoURL: currentUser.value.photoURL);
  });
```

To your `constructor`, in a function called in your `initState`, or if you are using Getx's dependency manager, on `onInit`.

**Comment by jonataslaw** [comment] 2020-09-01 22:17
I'm tagging it with a label, because maybe that information wasn't made clear in the documentation.

**Comment by JCKodel** [comment] 2020-09-02 12:40
> I'm tagging it with a label, because maybe that information wasn't made clear in the documentation.

Where is the documentation about debounce??? O.o

**Comment by stefandevo** [comment] 2020-09-02 13:06
@JCKodel 
Have you checked the docs??? 
https://github.com/jonataslaw/getx/blob/4b61419e30ef353479b41917214389bae8b52222/documentation/en_US/state_management.md#workers

**Comment by jonataslaw** [comment] 2020-09-09 22:27
Added to docs on 3.10
How isn't a issue, I'm closing it.

**Closed by jonataslaw** 2020-09-09 22:27 UTC
Labels: Need to insert in the documentation
