### ISSUE TITLE
the method onClose calls twice 

### ISSUE THREAD

**Issue by alanfg120** [jonataslaw/getx#673] opened 2020-10-01 03:55 UTC
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: A PageController was used after being disposed.
Once you have called dispose() on a PageController, it can no longer be used.
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> 
package:flutter/…/foundation/change_notifier.dart:108
#1      ChangeNotifier._debugAssertNotDisposed 
package:flutter/…/foundation/change_notifier.dart:114
#2      ChangeNotifier.dispose 
package:flutter/…/foundation/change_notifier.dart:181

<img width="408" alt="Captura de Pantalla 2020-09-30 a la(s) 10 15 40 p  m" src="https://user-images.githubusercontent.com/46004998/94763365-adf99400-036f-11eb-9911-6bcbd06e180e.png">

as the controller closes twice the dispose of the PageViewController generates an exception this happened when I updated to flutter 1.20.4

**Comment by jonataslaw** [comment] 2020-10-01 05:53
Duplicate of https://github.com/jonataslaw/getx/issues/671

**Closed by jonataslaw** 2020-10-01 05:53 UTC
