### ISSUE TITLE
Get.snackbar error 'overlayEntries.isEmpty': is not true.

### ISSUE THREAD

**Issue by zzterrozz** [jonataslaw/getx#748] opened 2020-10-28 02:08 UTC
Hi,

The snackbar is displayed on screen but shows an error in console.

**Controller code:** 
```
Future<void> login(String email, String password) async {
    try {
      await _auth.signInWithEmailAndPassword(email: email, password: password);
    } on FirebaseAuthException catch (error) {
      Get.snackbar(
        "Error",
        error.message,
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red.withOpacity(.75),
        colorText: Colors.white,
        icon: Icon(Icons.error, color:Colors.white),
        shouldIconPulse: true,
        barBlur: 20,
      );
    }
  }
```

**Console log:** 
```
[GETX] OPEN SNACKBAR null
[GETX] CLOSE SNACKBAR null

════════ Exception caught by animation library ═══════════════════════════════════
'package:get/get_navigation/src/snackbar/snack_route.dart': Failed assertion: line 263 pos 18: 'overlayEntries.isEmpty': is not true.
════════════════════════════════════════════════════════════════════

```

**Comment by eduardoflorence** [comment] 2020-10-28 12:44
I tried out your code with flutter 1.22.2 and Getx 3.15.0. It worked correctly without exceptions.

**Comment by zzterrozz** [comment] 2020-10-28 14:48
hi @eduardoflorence 

Thank you for your message.

I assumed the code alone is correct as it is from the getx documentation but I can't locate where this `overlayEntries.isEmpty` error is coming from.
The navigation & pages (binding, controller & views) have been generated with get_cli.

The controller code is in a Getxservice : 
```
class AuthController extends GetxService {
Future<void> login(String email, String password) async {
    try {
      await _auth.signInWithEmailAndPassword(email: email, password: password);
    } on FirebaseAuthException catch (error) {
      Get.snackbar(
        "Error",
        error.message,
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red.withOpacity(.75),
        colorText: Colors.white,
        icon: Icon(Icons.error, color:Colors.white),
        shouldIconPulse: true,
        barBlur: 20,
      );
    }
  }
}
```

The controller is consumed in `GetView<LoginController>` being called with `final AuthController authController = Get.find();`

**Comment by zzterrozz** [comment] 2020-10-29 01:12
Logs with `Get.overlayContext`

```
D/FirebaseAuth(26609): Notifying id token listeners about a sign-out event.
D/FirebaseAuth(26609): Notifying auth state listeners about a sign-out event.
[GETX] OPEN SNACKBAR null
I/flutter (26609): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (26609): │ #0   App.build.<anonymous closure> (package:app/main.dart:50:18)
I/flutter (26609): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (26609): │ 💡 From /home -- To --> /home // removed : 
I/flutter (26609): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (26609): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (26609): │ #0   AuthController.signOut (package:app/modules/z_global_controllers_services/auth_controller.dart:249:14)
I/flutter (26609): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (26609): │ 💡 Overlay-[LabeledGlobalKey<OverlayState>#a7a9f](dirty, state: OverlayState#c3929(entries: [OverlayEntry#0cb0d(opaque: true; maintainState: false), OverlayEntry#0e27b(opaque: false; maintainState: true), OverlayEntry#7d605(opaque: false; maintainState: false)]))
I/flutter (26609): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[GETX] CLOSE SNACKBAR null
I/flutter (26609): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (26609): │ #0   App.build.<anonymous closure> (package:app/main.dart:50:18)
I/flutter (26609): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (26609): │ 💡 From  -- To --> /home // removed : 
I/flutter (26609): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

════════ Exception caught by animation library ═════════════════════════════════════════════════════
'package:get/get_navigation/src/snackbar/snack_route.dart': Failed assertion: line 263 pos 18: 'overlayEntries.isEmpty': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by eduardoflorence** [comment] 2020-10-29 21:24
I made a minimum code using your GetxService and calling AuthController in the view and the problem doesn't happen to me.
Feel free to change my code so that it looks more like yours and post it here if you can reproduce the problem.
Update your Flutter and GetX and run `flutter clean` on your terminal

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(
    initialRoute: '/login',
    initialBinding: InitialBinding(),
    getPages: [
      GetPage(
        name: '/login',
        page: () => LoginPage(),
        binding: LoginBinding(),
      ),
      GetPage(
        name: '/home',
        page: () => HomePage(),
      ),
    ],
  ));
}

class InitialBinding implements Bindings {
  @override
  void dependencies() {
    Get.put(AuthController());
  }
}

class AuthController extends GetxService {
  Future<void> login(String email, String password) async {
    try {
      // await _auth.signInWithEmailAndPassword(email: email, password: password);
      throw Exception('username/password invalid');
    } /*on (FirebaseAuthException*/ catch (error) {
      Get.snackbar(
        "Error",
        error.message,
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red.withOpacity(.75),
        colorText: Colors.white,
        icon: Icon(Icons.error, color: Colors.white),
        shouldIconPulse: true,
        barBlur: 20,
      );
    }
  }
}

class LoginBinding extends Bindings {
  @override
  void dependencies() {
    Get.put(LoginController());
  }
}

class LoginController extends GetxController {
  final message = 'teste'.obs;

  // this line should be here
  // final AuthController authController = Get.find();
}

class LoginPage extends GetView<LoginController> {
  
  final AuthController authController = Get.find();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('LOGIN')),
      body: Center(
        child: RaisedButton(
          onPressed: () async => await authController.login('foo@foo.com','123'),
          child: Text('Login'),
        ),
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('HOME')),
      body: Container(),
    );
  }
}

```

**Comment by zzterrozz** [comment] 2020-10-29 23:37
@eduardoflorence 

Thank you for your help.

After a `flutter upgrade`, `flutter clean` , I am facing the same issue with your code 

```
[GETX] "AuthController" has been initialized
[GETX] "GetMaterialController" has been initialized
[GETX] GOING TO ROUTE /login
[GETX] "LoginController" has been initialized
[GETX] OPEN SNACKBAR null
[GETX] CLOSE SNACKBAR null

════════ Exception caught by animation library ═════════════════════════════════════════════════════
'package:get/get_navigation/src/snackbar/snack_route.dart': Failed assertion: line 263 pos 18: 'overlayEntries.isEmpty': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Flutter doctor -v : 
```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.105, on Mac OS X 10.15.7 19H2 darwin-x64, locale fr-CH)
    • Flutter version 1.24.0-4.0.pre.105 at /Users/username/Development/flutter
    • Framework revision b86fa13235 (2 days ago), 2020-10-27 17:57:03 -0500
    • Engine revision 64e6599910
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • iPhone (mobile)    • ios            • iOS 13.7
    • Web Server (web) • web-server                • web-javascript • Flutter Tools
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

In my `pubspec.yaml` I am using `https://pub.dev/packages/flutter_native_splash`

I wonder if the problem may come from there ?

**Comment by eduardoflorence** [comment] 2020-10-29 23:43
Are you using version 3.15.0 of GetX?

**Comment by zzterrozz** [comment] 2020-10-29 23:44
Yes I am using 3.15.0

I am trying a project from scratch with your code & with `flutter_native_splash` only
Keep you posted when I run it

**Comment by zzterrozz** [comment] 2020-10-29 23:52
@eduardoflorence good news, or not!

With a from scratch project generated with `get_cli`  installing only `https://pub.dev/packages/flutter_native_splash` & using your code in` main.dart`, I am able to reproduce the issue 


```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  image: assets/images/splash.png
  color: "42a5f5"
  android: false
```

`flutter pub pub run flutter_native_splash:create`

`flutter run`

```
[GETX] "AuthController" has been initialized
[GETX] "GetMaterialController" has been initialized
[GETX] GOING TO ROUTE /login
[GETX] "LoginController" has been initialized
[GETX] OPEN SNACKBAR null
[GETX] CLOSE SNACKBAR null

════════ Exception caught by animation library ═════════════════════════════════════════════════════
'package:get/get_navigation/src/snackbar/snack_route.dart': Failed assertion: line 263 pos 18: 'overlayEntries.isEmpty': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zzterrozz** [comment] 2020-10-30 00:04
I talked to fast, unfortunately I have the same error without the splashscreen. 
I need to run some more tests to see what can cause this issue.

**Comment by eduardoflorence** [comment] 2020-10-30 00:08
I'm doing a test with Get CLI

**Comment by eduardoflorence** [comment] 2020-10-30 00:19
I did the test with Get CLI, generated a new project and pasted my code into main.dart. It worked without errors.

![image](https://user-images.githubusercontent.com/9120528/97645656-514fce80-1a2c-11eb-9ab3-825b8c2633f8.png)

**Comment by zzterrozz** [comment] 2020-10-30 00:40
get_cli create project + iPhone physical device : error
get_cli create project + iPhone 12 emulator : error
AndroidStudio new flutter project + iPhone physical device : error
AndroidStudio new flutter project + iPhone 12 emulator : error

**Comment by zzterrozz** [comment] 2020-10-30 00:42
On your logs, I see that `snackbar` is also `null`
Is this normal ? Considering that `Dialogs` and `Bottomsheets` have respectively ids allocated

**Comment by jonataslaw** [comment] 2020-10-30 01:16
Your installation is corrupted, and yes, snackbar is null in any situation, this is normal, since they have no route track. The "null" message will be removed in future updates, but this is expected behavior.
Remove your Flutter installation, and install again, from what I saw, your native file, specifically the OverlayRoute file is corrupted.

**Comment by zzterrozz** [comment] 2020-10-30 02:52
@eduardoflorence @jonataslaw 
Thank you for your help & the hard work on getx!


```
Invalide cache / restart
flutter channel stable
flutter upgrade
flutter clean
```
`+ delete all previous build ` made the error disappeared !

Thanks again

**Comment by jonataslaw** [comment] 2020-10-30 04:01
Glad you solved it. Well, as it is not related to getx, I am closing this.

**Closed by jonataslaw** 2020-10-30 04:01 UTC

**Comment by IsmailAlamKhan** [comment] 2020-11-25 20:16
> 
> 
> Your installation is corrupted, and yes, snackbar is null in any situation, this is normal, since they have no route track. The "null" message will be removed in future updates, but this is expected behavior.
> Remove your Flutter installation, and install again, from what I saw, your native file, specifically the OverlayRoute file is corrupted.

I am also getting this this error but reinstalling flutter did nothing

**Comment by eduardoflorence** [comment] 2020-11-25 20:24
@IsmailAlamKhan, please open a new issue and provide a code that we can reproduce your problem.
