### ISSUE TITLE
one controller with multiple widget

### ISSUE THREAD

**Issue by niypoo** [jonataslaw/getx#425] opened 2020-07-26 19:41 UTC
**Describe the bug**
I'm trying use one controller with multiple widget in list view but when make action on one widget that apples on all widget 

**Expected behavior**
when tap on a widget only that widget that have id show this action

**Flutter Version:**
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (4 weeks ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

**Minimal reproduce code**
View.dart
```
 GetBuilder<XController>(
      id: '${item.id}',
      init: XController(),
      builder: (controller) =>GestureDetector(child: AnimatedController(
        key: ValueKey('${item.id}'),
        duration:Duration(milliseconds: 300),
        height: controller.isAnimation? 0 : 40,
        child:Text('List Tile)
        onTap: controller. doAnimation(item.id)
       ),);
);
```

Controller.dart
```

class XController extends GetxController {
  bool isAnimation = false
  void doAnimation(id){
    isAnimation = true;
    update([$id]);
  }
}

```

**Comment by Nipodemos** [comment] 2020-07-26 22:18
GetBuilder is a simple state manager, and it updates all values of a controller always.
If you want more control over what is being updated, you can use the reactive state management, the one where all var in controller has a `.obs` in the end and you updated with `var.value = 'newValue'`

**Comment by jonataslaw** [comment] 2020-07-26 23:15
You are using the wrong feature.
ID is used to update separate widgets from the same controller.
You are wanting to have a Controller for each widget.

Use:

```dart
 GetBuilder<XController>(
      id: '${item.id}',
      init: XController(),
      global: false, // ADD THIS
      builder: (controller) =>GestureDetector(child: AnimatedController(
        key: ValueKey('${item.id}'),
        duration:Duration(milliseconds: 300),
        height: controller.isAnimation? 0 : 40,
        child:Text('List Tile)
        onTap: controller. doAnimation(item.id)
       ),);
);
```

**Comment by jonataslaw** [comment] 2020-07-27 17:38
As this is not a bug description, just the incorrect use of library tools, I am closing this.

**Closed by jonataslaw** 2020-07-27 17:38 UTC
