### ISSUE TITLE
Bind pages in BottomNavigationBar

### ISSUE THREAD

**Issue by qbait** [jonataslaw/getx#680] opened 2020-10-05 18:11 UTC
I decided to refactor this code to use Get
```dart
class HomePage extends StatefulWidget {
  final int selectedIndex;

  HomePage(this.selectedIndex);

  @override
  _HomePageState createState() => _HomePageState(selectedIndex);
}

class _HomePageState extends State<HomePage> {
  GlobalKey<ScaffoldState> scaffoldKey = new GlobalKey<ScaffoldState>();
  int _selectedIndex = 0;

  _HomePageState(this._selectedIndex);

  List<Widget> _widgetOptions = <Widget>[
    BrowsePage(),
    HistoryPage(),
    SettingsPage(),
  ];

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: _widgetOptions.elementAt(_selectedIndex),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.search),
            label: 'Diagnose',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.history),
            label: 'History',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'Settings',
          ),
        ],
        currentIndex: _selectedIndex,
        selectedItemColor: Colors.pink,
        onTap: _onItemTapped,
      ),
    );
  }
}
```

So I'm having my view:
```dart
class HomePage extends GetView<HomeController> {
  HomePage(int index) {
    controller.changePage(index);
  }

  @override
  Widget build(BuildContext context) {
    return Obx(
      () => Scaffold(
        body: controller.currentPage,
        bottomNavigationBar: BottomNavigationBar(
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.search),
              label: 'Diagnose',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.history),
              label: 'History',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.settings),
              label: 'Settings',
            ),
          ],
          currentIndex: controller.currentIndex(),
          selectedItemColor: Colors.pink,
          onTap: controller.changePage,
        ),
      ),
    );
  }
}
```

My controller:
```dart
class HomeController extends GetxController {

  static HomeController get to => Get.find();

  final currentIndex = 0.obs;

  final pages = <Widget>[
    BrowsePage(),
    HistoryPage(),
    SettingsPage(),
  ];

  Widget get currentPage => pages[currentIndex()];

  changePage(int index) {
    currentIndex.value = index;
  }
}
```

My pages with Bindings:
```dart
    GetPage(
      name: Routes.BROWSE,
      page: () => HomePage(0),
      binding: HomeBinding(),
    ),
    GetPage(
      name: Routes.HISTORY,
      page: () => HomePage(1),
      binding: HomeBinding(),
    ),
    GetPage(
      name: Routes.SETTINGS,
      page: () => HomePage(2),
      binding: HomeBinding(),
    ),
```
```dart
class HomeBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => HomeController());
  }
}
```

Unfortunately, it doesn't work when I'm trying to open `History` or `Settings` using e.g. `Get.offAllNamed(Routes.HISTORY),`

**Comment by eduardoflorence** [comment] 2020-10-05 20:51
I didn't understand where you want to put `Get.offAllNamed`, as the navigation works only with the code above.

I reconstructed your example above and put a button on the Browse page just to test that `Get.offAllNamed` also works
Environment:
Flutter 1.22.0 • channel stable
Dart 2.10.0
get: ^ 3.12.1

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(
    debugShowCheckedModeBanner: false,
    initialRoute: '/browse',
    defaultTransition: Transition.fade,
    getPages: [
      GetPage(
        name: '/browse',
        page: () => HomePage(0),
        binding: HomeBinding(),
      ),
      GetPage(
        name: '/history',
        page: () => HomePage(1),
        binding: HomeBinding(),
      ),
      GetPage(
        name: '/settings',
        page: () => HomePage(2),
        binding: HomeBinding(),
      ),
    ],
  ));
}

class HomeBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => HomeController());
  }
}

class HomeController extends GetxController {
  static HomeController get to => Get.find();

  final currentIndex = 0.obs;

  final pages = <Widget>[
    BrowsePage(),
    HistoryPage(),
    SettingsPage(),
  ];

  Widget get currentPage => pages[currentIndex()];

  changePage(int index) {
    currentIndex.value = index;
  }
}

class HomePage extends GetView<HomeController> {
  HomePage(int index) {
    controller.changePage(index);
  }

  @override
  Widget build(BuildContext context) {
    return Obx(
      () => Scaffold(
        body: controller.currentPage,
        bottomNavigationBar: BottomNavigationBar(
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.search),
              label: 'Diagnose',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.history),
              label: 'History',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.settings),
              label: 'Settings',
            ),
          ],
          currentIndex: controller.currentIndex.value,
          selectedItemColor: Colors.pink,
          onTap: controller.changePage,
        ),
      ),
    );
  }
}

class BrowsePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Browse'),),
      body: Center(
        child: Container(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Browse'),
              RaisedButton(
                color: Colors.blue,
                onPressed: ()=> Get.offAllNamed('/history'),
                splashColor: Colors.blueGrey,
                child: Text('Go to History',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class HistoryPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('History'),),
      body: Center(
        child: Container(
          child: Text('History'),
        ),
      ),
    );
  }
}

class SettingsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Settings'),),
      body: Center(
        child: Container(
          child: Text('Settings'),
        ),
      ),
    );
  }
}
```

**Comment by qbait** [comment] 2020-10-05 22:25
Thank you for taking the time @eduardoflorence. I've edited your sample to reproduce the problem.

Steps to reproduce:
1. Click `Go to Another Page`
2. Click `Go to History`
3. Try to choose `Settings` -> It will go to `Diagnose` for some reason

`import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(
    debugShowCheckedModeBanner: false,
    initialRoute: '/browse',
    defaultTransition: Transition.fade,
    getPages: [
      GetPage(
        name: '/browse',
        page: () => HomePage(0),
        binding: HomeBinding(),
      ),
      GetPage(
        name: '/history',
        page: () => HomePage(1),
        binding: HomeBinding(),
      ),
      GetPage(
        name: '/settings',
        page: () => HomePage(2),
        binding: HomeBinding(),
      ),
      GetPage(
        name: '/another',
        page: () => AnotherPage(),
      ),
    ],
  ));
}

class HomeBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => HomeController());
  }
}

class HomeController extends GetxController {
  static HomeController get to => Get.find();

  final currentIndex = 0.obs;

  final pages = <Widget>[
    BrowsePage(),
    HistoryPage(),
    SettingsPage(),
  ];

  Widget get currentPage => pages[currentIndex()];

  changePage(int index) {
    currentIndex.value = index;
  }
}

class HomePage extends GetView<HomeController> {
  HomePage(int index) {
    controller.changePage(index);
  }

  @override
  Widget build(BuildContext context) {
    return Obx(
      () => Scaffold(
        body: controller.currentPage,
        bottomNavigationBar: BottomNavigationBar(
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.search),
              label: 'Diagnose',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.history),
              label: 'History',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.settings),
              label: 'Settings',
            ),
          ],
          currentIndex: controller.currentIndex.value,
          selectedItemColor: Colors.pink,
          onTap: controller.changePage,
        ),
      ),
    );
  }
}

class BrowsePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Browse'),
      ),
      body: Center(
        child: Container(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Browse'),
              RaisedButton(
                color: Colors.blue,
                onPressed: () => Get.toNamed('/another'),
                splashColor: Colors.blueGrey,
                child: Text(
                  'Go to Another Page',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class HistoryPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('History'),
      ),
      body: Center(
        child: Container(
          child: Text('History'),
        ),
      ),
    );
  }
}

class SettingsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Settings'),
      ),
      body: Center(
        child: Container(
          child: Text('Settings'),
        ),
      ),
    );
  }
}

class AnotherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Settings'),
      ),
      body: Center(
        child: Container(
          child: RaisedButton(
            color: Colors.blue,
            onPressed: () => Get.offAllNamed('/history'),
            splashColor: Colors.blueGrey,
            child: Text(
              'Go to History',
              style: TextStyle(
                color: Colors.white,
                fontSize: 16,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
`

**Comment by eduardoflorence** [comment] 2020-10-05 23:16
The Problem is here:
`Get.offAllNamed ('/ history')`
When you remove all routes, the dependency manager removes the HomeController from memory (see GetX logs). Since HomeController is loaded with lazyPut, causing currentIndex to return to zero after showing HistoryPage.

1) You can do this:
`Get.offNamedUntil ('/ history', (Route route) => route.settings.name == '/ browse')`
So the HomeController does not leave the memory, because the initial "/ browse" route will not be removed

2) Or you can do this (best):
```dart
class HomeBinding extends Bindings {
   @override
   void dependencies () {
     //Get.lazyPut (() => HomeController ());
     Get.put (() => HomeController (), permanent: true);
   }
}
```

**Comment by ghenry** [comment] 2020-10-05 23:21
You can also use GetxService to keep things in memory.--
Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 330 44 50 000
D +44 (0) 330 44 55 007
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ghenry@suretec.co.uk

Open Source. Open Solutions(tm).

http://www.suretecsystems.com/

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie, Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html

**Comment by qbait** [comment] 2020-10-06 10:54
Fair enough, but what about specific controllers in that case?
Let's say I would like to have `HomeController` keeping only the logic for opening the selected option and dedicated controllers for Browse, History, and Settings?

I've tried something like:
```
    GetPage(
      name: Routes.BROWSE,
      page: () => HomePage(2),
      binding: HomeBinding(),
    ),
    GetPage(
      page: () => BrowsePage(),
      binding: BrowseBinding(),
    ),
```

But, I've got

> If no route is provided using home, routes, onGenerateRoute, or onUnknownRoute, a non-null callback for the builder property must be provided, and the other navigator-related properties, navigatorKey, initialRoute, and navigatorObservers, must have their initial values (null, null, and the empty list, respectively).
> 'package:flutter/src/widgets/app.dart':
> Failed assertion: line 227 pos 10: '(home != null ||
>           routes.isNotEmpty ||
>           onGenerateRoute != null ||
>           onUnknownRoute != null)
>          ||
>          (builder != null &&
>           navigatorKey == null &&
>           initialRoute == null &&
>           navigatorObservers.isEmpty)'
> The relevant error-causing widget was: 
>   GetMaterialApp file:///Users/jakub/StudioProjects/pickle/lib/main.dart:13:12

**Comment by eduardoflorence** [comment] 2020-10-06 18:12
This cannot, as the name property is mandatory:
```dart
GetPage(
  page: () => BrowsePage(),
  binding: BrowseBinding(),
),
```

You can do this for the initial binding, and you can have dedicated controllers for each other page:
```dart
  runApp(GetMaterialApp(
    debugShowCheckedModeBanner: false,
    initialRoute: '/browse',
    initialBinding: HomeBinding(),   // <-- insert this
    defaultTransition: Transition.fade,
    getPages: [
      GetPage(...)
    ],
    ...
```

**Comment by Nipodemos** [comment] 2020-10-10 19:29
> Fair enough, but what about specific controllers in that case?
> Let's say I would like to have `HomeController` keeping only the logic for opening the selected option and dedicated controllers for Browse, History, and Settings?

I didn't quite understand what you want here.
Could you provide the code that you tried to make it work?

**Comment by lzdtech** [comment] 2020-10-23 17:59
How to initialize data for each page under BottomNavigationBarItem

**Comment by jonataslaw** [comment] 2020-10-23 19:13
Okay, this is turning into a mess.
Initially, issues are not for doubts or use cases. I definitely would like you not to use this space for code validations, as there are already enough channels for that (Discord, Telegram, Slack, etc.).
Second, I still haven't been able to see which bug is intended to be demonstrated, just use-case validations, where Eduardo successfully scored the points where there were problems with the code.
Please inform if the problem has been solved, or clearly point out the expected behavior, and the behavior of Getx, mentioning where in the code you think there is a bug, or I will close this issue.

@lzdtech please, look for platform channels for questions.

**Comment by jonataslaw** [comment] 2020-10-25 20:35
As there was no answer, I believe that the problem has already been solved, and I am closing this.

**Closed by jonataslaw** 2020-10-25 20:35 UTC
Labels: Waiting for customer response

**Comment by qbait** [comment] 2020-10-26 15:25
Yes, it's solved. Thank you

**Comment by cyrilcolinet** [comment] 2021-04-01 15:40
> Yes, it's solved. Thank you

Hi qbait,
I've incontred the same issue (if we call this as an issue), but if u find a workarround or maybe the way to to that, can you please tell me here how to do that?

Thanks by advance.
Have a nice day.

**Comment by phankietit** [comment] 2022-11-10 06:33
You can add the binding property for each tab & call when the tab is tapped
`entries.value.binding?.dependencies();`
