### ISSUE TITLE
I updated the get version from 3.6.2 to the latest version, my app kind of stuck in the initial login screen.

### ISSUE THREAD

**Issue by mohanhari** [jonataslaw/getx#801] opened 2020-11-17 06:10 UTC
When I updated the get version from 3.6.2 to the latest version, my app kind of stuck in the initial login screen. After that nothing seems to be working. even the navigation to other pages are not working. This is issue is only happening when we run the build after running 'flutter clean'. If we build the app with the existing older version build present the app is working fine. It's not even showing any errors also. If I use the get version of 3.6.2 it's working fine. Do you have any idea why this is happening? 

Since it's not showing any errors I don't have a reproduction code or where it's happening

my flutter version is  1.20.4

**Comment by CrisNegoianu** [comment] 2020-11-18 06:42
I can confirm that there is an issue in the library after version 1.15 and it's still there in the latest release 1.17.1.
To help out I debugged this a little bit.
I believe it has to do with the fact that the "builder" parameter is no longer being passed from the **put** method in "extension_instance.dart" on line 82 to the GetInstance().put method.

The fix is to change from **Get.put(null, builder: YourController())** to **Get.put(YourController())**.
The builder parameter seems to have been deprecated.
Should we stop using the builder parameter?
What is the reason for this move?

**Comment by jonataslaw** [comment] 2020-11-18 11:51
> When I updated the get version from 3.6.2 to the latest version, my app kind of stuck in the initial login screen. After that nothing seems to be working. even the navigation to other pages are not working. This is issue is only happening when we run the build after running 'flutter clean'. If we build the app with the existing older version build present the app is working fine. It's not even showing any errors also. If I use the get version of 3.6.2 it's working fine. Do you have any idea why this is happening?
> 
> Since it's not showing any errors I don't have a reproduction code or where it's happening
> 
> my flutter version is 1.20.4

The latest version works well, if your app crashes, you:
1- You are using legacy code. When something is marked as deprecated, don't insist on using it.
2- Bad practices. If you do things that can be considered bad practice, like inserting logic into builders, or something like that, you will face problems.
3- If it is not debuggable, the problem is in your app. Review your lines of code to find out what you did wrong, we can't help you without a reproduction code.

**Comment by jonataslaw** [comment] 2020-11-18 11:54
> I can confirm that there is an issue in the library after version 1.15 and it's still there in the latest release 1.17.1.
> To help out I debugged this a little bit.
> I believe it has to do with the fact that the "builder" parameter is no longer being passed from the **put** method in "extension_instance.dart" on line 82 to the GetInstance().put method.
> 
> The fix is to change from **Get.put(null, builder: YourController())** to **Get.put(YourController())**.
> The builder parameter seems to have been deprecated.
> Should we stop using the builder parameter?
> What is the reason for this move?

builder function on Get.put was deprecated and should not be used.
Use Get.put(Instance()) to put Instance on memory on immediate or Get.lazyPut(()=> Instance()) to lazy instance

**Comment by jonataslaw** [comment] 2020-11-18 12:05
Well, it looks like you're also using a very old version.
With each Flutter update, we also update our source to maintain compatibility, so it’s good to keep the version of Flutter and Get always up to date.
As this is a problem with your code, and there is no case of reproduction, it will not be possible to help you. But looking at changeLog to see what has changed since your update so far, can help you know where you are missing something.
As this is not a reproducible problem and it is a problem in your code, I am ending this. If you need personal help with this, the community channels always have people online who can help you in your specific case.
If you have a reproduction case, feel free to reopen the issue.
Note: if you are navigating to the same screen, you probably forgot to call `preventDuplicates: false` in your route, this is a very common problem.

**Closed by jonataslaw** 2020-11-18 12:05 UTC
