### ISSUE TITLE
Please enable null-safety... 

### ISSUE THREAD

**Issue by i-newta** [jonataslaw/getx#1131] opened 2021-03-01 01:57 UTC
we cannot use getX Directly in master channel with null-safety... 

flutter run --no-sound-null-safety 
this is the only one possible  way to use Getx with null safety for NOW

so Please enable null-safety...

**Comment by eduardoflorence** [comment] 2021-03-01 02:23
Duplicate of #858

**Closed by eduardoflorence** 2021-03-01 02:23 UTC
Labels: duplicate
