### ISSUE TITLE
GetxController not removed from memory when I leave screen

### ISSUE THREAD

**Issue by maheshsuthar93** [jonataslaw/getx#1709] opened 2021-07-30 06:02 UTC
**Describe the bug**
I have created two screen one is listing and send one is detail screen, so when I go from listing to details and come back to listing then controller not removed from memory and when I go second time to detail page then old value shows.

example:

```dart

class DetailScreen extends StatelessWidget {
  final DetailController _ctr =
      Get.put(DetailController(), permanent: false);

  @override
  Widget build(BuildContext context) {
   return new Container();
  }
}

class DetailController extends GetxController {

 RxDouble totalPrice = 0.0.obs;

  @override
  void onInit() {
    debugPrint("onInit");
    // TODO: implement onInit
    totalPrice.value=100;
    super.onInit();
  }

  @override
  void onClose() {

    super.onClose();
    debugPrint("onclose called");
  }

}

```

**Expected behavior**
Controller should re-initialise or remove old values

**Flutter Version:**
1.0.0+1

**Getx Version:**
^4.2.4

**Describe on which device you found the bug:**
ex: Flutter web chrome

**Comment by jonataslaw** [comment] 2021-07-31 14:55
If you are using navigation without named routes, use Get.to(()=> instead of Get.to.
Try to place the controller inside the builder.

Update to latest version.

Since I couldn't reproduce the problem, I'm closing this. If you think it's a bug, open another issue with a reproduce code

**Closed by jonataslaw** 2021-07-31 14:55 UTC

**Comment by jonataslaw** [comment] 2021-08-04 18:12
> same issue for me.
> 
> **Getx Version**: 4.2.0
> 
> * **Get.back()** removes the controller and onClose() is fired
> * **Get.toNamed(Routes.ROUTE_NAME, arguments: ['someArg'])** does not remove the controller or trigger onClose()
> 
> @jasonlaw maybe we open this again...

This is the expected behavior. Read the docs
