### ISSUE TITLE
GetxController doesn't dispose fields.

### ISSUE THREAD

**Issue by jintak0401** [jonataslaw/getx#1037] opened 2021-01-25 14:40 UTC
**Describe the bug**
GetxController doesn't dispose fields when it closes.

**Reproduction code**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      initialRoute: '/first',
      getPages: [
        GetPage(name: '/first', page: ()=>FirstScreen()),
        GetPage(name: '/second', page: ()=>SecondScreen()),
      ],
    );
  }
}

class FirstScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen (with Get)', style: TextStyle(fontWeight: FontWeight.bold)),
      ),
      body: SafeArea(
        child: Center(
          child: ElevatedButton(
            onPressed: () {
              Get.toNamed('second');
            },
            child: Text('Go To Second Screen (with Get)', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 24)),
          ),
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {

  final Controller _controller = Get.put(Controller());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second Screen (with Get)', style: TextStyle(fontWeight: FontWeight.bold)),
      ),
      body: SafeArea(
        child: Center(child: Text('Second Screen')),
      ),
    );
  }
}

class Controller extends GetxController with SingleGetTickerProviderMixin {
  RxList _scrollControllers;
  RxList _animationControllers;
  RxList _focusNodes;

  @override
  void onInit() {
    super.onInit();
    _scrollControllers = List.generate(10000, (_) => ScrollController()).obs;
    _animationControllers = List.generate(10000, (_) => AnimationController(vsync: this, duration: Duration(microseconds: 300))).obs;
    _focusNodes = List.generate(10000, (_) => FocusNode()).obs;
  }

  @override
  void onClose() {
    // According to State management docs, it says these lines don't need.
    // But I added it because I thought it might be because of this. (but it doesn't work) 
    // _scrollControllers.forEach((element) {element.dispose();});
    // _animationControllers.forEach((element) {element.dispose();});
    // _focusNodes.forEach((element) {element.dispose();});
    super.onClose();
  }

  List get scrollControllers => _scrollControllers;
  List get animationControllers => _animationControllers;
  List get focusNodes => _focusNodes;
}

```

**To Reproduce**
1. Go to Second Screen from First Screen . Then GetxController creates 10,000 `ScrollController`, `AnimationController`, and `FocusNode`.
2. Go back to First Screen from Second Screen. 

**Expected behavior**
At step 2, GetxController should disposes objects of `_scrollController`, `_animationController`, and `_focusNodes`.  But it doesn't dispose these. Rather, the memory usage increased slightly. 

**Screenshots**
![memory usage](https://user-images.githubusercontent.com/32933980/105719526-b94b7d80-5f65-11eb-85b0-24d81a9c50e9.PNG)

**Flutter Version:**
```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (7 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

**Getx Version:**
3.24.0

**Describe on which device you found the bug:**
ex: Pixel 2 XL API 30 - Android.

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by eduardoflorence** [comment] 2021-01-25 15:07
What you are doing is instantiating 10000 times a class. GetxController needs to be started with Get.put and obtained with Get.find. For your case, the best option would be to use Get.create, as it creates a new instance of the controller each time it is used.
The memory increase you demonstrated will only be reduced by Dart's own Garbage Collected, which will delete instances when they are no longer used

**Comment by jintak0401** [comment] 2021-01-26 07:04
> What you are doing is instantiating 10000 times a class. GetxController needs to be started with Get.put and obtained with Get.find. For your case, the best option would be to use Get.create, as it creates a new instance of the controller each time it is used.
> The memory increase you demonstrated will only be reduced by Dart's own Garbage Collected, which will delete instances when they are no longer used

Thank you for comment. Do you mean that in this case, getx does its mission well, but Dart's own Garbage Collection doesn't work?

**Comment by MisterioRee** [comment] 2021-05-24 11:30
@jintak0401  It doesn't look beautiful but it works very well 

Delete the controller in WillPopScope

 ```
WillPopScope(
      onWillPop: () async {
        Get.delete<ControllerName>();
        return true;
      }
 child: Scaffold( ....
  )
)
```

**Comment by mohadel92** [comment] 2021-06-03 13:58
i used Get.put before in main

and i am facing same problem
GetX rarely disposes any controller

**Comment by adnankhan74444** [comment] 2021-06-27 16:31
same problem facing.

**Comment by jonataslaw** [comment] 2021-07-31 16:52
`GetPage(name: '/second', page: ()=>SecondScreen()),`

/// Where is the slash?
`Get.toNamed('second');`

/// It need be on Builder. Use GetView and Bindings to better organization
 final Controller _controller = Get.put(Controller());

This issue is always caused by the dev's lack of attention, but in the last update you might face a red screen when trying to do something like this.

For this reason your Routes **must be a CONST**.

As this is not a bug report, but inappropriate use of the lib, I am closing this.

**Closed by jonataslaw** 2021-07-31 16:52 UTC
