### ISSUE TITLE
Improper use of a GetX has been detected

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/getx#399] opened 2020-07-18 23:27 UTC
**Describe the bug**
``` dart
Obx(
                  () => Wrap(
                    crossAxisAlignment: WrapCrossAlignment.start,
                    spacing: responsiveWidth(15),
                    runSpacing: responsiveHeight(12),
                    children: <Widget>[
                      AddTargetButton(),
                      if (_.isBusy)
                        Padding(
                          padding: EdgeInsetsResponsive.all(40),
                          child: CircularProgressIndicator(),
                        )
                      else
                        for (var target in _.allUserSavingsTargets)
                          SavingsTargetCard(
                            target: target,
                          ),
                    ],
                  ),
                ),
```
The code above produces an `improper use of a GetX has been detected` error, meanwhile `allUserSavingsTargets` is an `RxList`.

**Expected behavior**
The Wrap reacts to changes to `allUserSavingsTargets`.

**Flutter Version:**
1.17.3

**Get Version:**
3.3.0

**Comment by Prn-Ice** [comment] 2020-07-18 23:36
Changing to `_.allUserSavingsTargets.value` fixes this, feel free to close if this is correct,

**Comment by ialameh** [comment] 2020-07-19 01:29
I had a code that broke just few hours ago, same error, trying to trace it

 Obx(
                    () => GenericFlatButton(
                      text: "Submit",
                      padding: EdgeInsets.symmetric(horizontal: 16),
                      onPressed: () {
                        if (_fbKey.currentState.saveAndValidate()) {
                          Map<String, dynamic> response =
                              _fbKey.currentState.value;
                          double amountFrom =
                              double.parse(response['inputValue']);
                          int frequencyFrom = int.parse(response['frequency']);
                          int frequencyTo = _
                              .dataSnapshot[_incomeDetails.type].value
                              .info(IncomeDetails.FREQUENCY);
                          String result =
                              ((amountFrom * frequencyFrom) / frequencyTo)
                                  .toStringAsFixed(2);
                          _.textEditingControllers[textEditingController].text =
                              result;
                          Navigator.of(context).pop();
                        }
                      },
                    ),
                  ),

( _.textEditingControllers is not observable)

**Comment by jonataslaw** [comment] 2020-07-19 02:40
> Changing to `_.allUserSavingsTargets.value` fixes this, feel free to close if this is correct,

You were accessing the list, which has no value. An Obx only opens a stream (just like BLoC) but allows you to access the value directly through the .value

**Comment by jonataslaw** [comment] 2020-07-19 02:53
> Changing to `_.allUserSavingsTargets.value` fixes this, feel free to close if this is correct,

When looping, you are not accessing values from the list, but just accessing the iterator, so no values are attached to Obx.
It may be interesting to use this approach, but if you have a large number of items, it can create overhead.
I would use a ListView.builder, because in that case it would allow a lazy loading, if the number of items was large, so that I would not need to access the ".value" just to attach the listener to the nearest Obx, but you can use it what are you doing, hasn't problem

**Comment by jonataslaw** [comment] 2020-07-19 02:56
> ```
> I had a code that broke just few hours ago, same error, trying to trace it
> 
>  Obx(
>                     () => GenericFlatButton(
>                       text: "Submit",
>                       padding: EdgeInsets.symmetric(horizontal: 16),
>                       onPressed: () {
>                         if (_fbKey.currentState.saveAndValidate()) {
>                           Map<String, dynamic> response =
>                               _fbKey.currentState.value;
>                           double amountFrom =
>                               double.parse(response['inputValue']);
>                           int frequencyFrom = int.parse(response['frequency']);
>                           int frequencyTo = _
>                               .dataSnapshot[_incomeDetails.type].value
>                               .info(IncomeDetails.FREQUENCY);
>                           String result =
>                               ((amountFrom * frequencyFrom) / frequencyTo)
>                                   .toStringAsFixed(2);
>                           _.textEditingControllers[textEditingController].text =
>                               result;
>                           Navigator.of(context).pop();
>                         }
>                       },
>                     ),
>                   ),
> 
> ( _.textEditingControllers is not observable)
> ```

This is not an error, it is not a bug, it is just GetX asking you to remove an unnecessary Obx / GetX, or attach an observable for it to rebuild.
When that happens, just delete Obx / GetX, if you miss something being upgradeable, simply make it observable, and use Obx only on the specific widget that will be updated, not on your parent, not on the entire widget tree .

**Comment by jonataslaw** [comment] 2020-07-19 03:00
Well, as this has been clarified, I am closing.

**Closed by jonataslaw** 2020-07-19 03:00 UTC

**Comment by melwinlobo18** [comment] 2020-11-20 11:31
```dart
ObxValue(
                  (resizedWidth) {
                    return Positioned(
                      right: _actualWidth - (Get.width + _scrollOffset),
                      top: Get.height / 4,
                      child: LinksCard(
                        isLinkPressed: _isLinkPressed,
                        onClose: () {
                          setState(() {
                            _isLinkPressed = false;
                          });
                        },
                      ),
                    );
                  },
                  (Get.width + Get.height).obs,
                ),
```

I'm getting the same error for the above piece of code. It was working fine in `get: ^3.13.2` but throws the error in the latest version.

I'm using `(Get.width + Get.height).obs` as the widget needs to rebuild when the width or height of the browser changes.

**Comment by eduardoflorence** [comment] 2020-11-20 12:10
@melwinlobo18 , `Get.width / height` are immutable. This is explained in the readme.

> if you need a changeable height / width (like Desktop or browser windows that can be scaled) you will need to use context.
> context.width
> context.height

Remove `ObxValue` and replace `Get.width` and `Get.height` for `context.width` and `context.height`

**Comment by melwinlobo18** [comment] 2020-11-20 13:29
@eduardoflorence Thank you for the suggestion. I'm using `context` now but I still get the following error:

```bash
      [Get] the improper use of a GetX has been detected. 
      You should only use GetX or Obx for the specific widget that will be updated.
      If you are seeing this error, you probably did not insert any observable variables into GetX/Obx 
      or insert them outside the scope that GetX considers suitable for an update 
      (example: GetX => HeavyWidget => variableObservable).
      If you need to update a parent widget and a child widget, wrap each one in an Obx/GetX.
```
