### ISSUE TITLE
Expected a value of type "EntityController" but get one of type "EntityController"

### ISSUE THREAD

**Issue by jefrisingh** [jonataslaw/getx#1595] opened 2021-07-02 14:47 UTC
The error saying that It's expecting Type (i.e EntityController) but got one of same type(i.e, EntityController) , It's really wired for me.

**Reproduction code
I user Initali app bindings with the bellow code
`Get.put(EntityController());`

and I did accessed it with the follow code inside websocket connection, which will receive data for every 5 minutes

```dart
Get.find<EntityController>().updateTrending(json);
```
Here is the error

`Error: Expected a value of type 'EntityController' (in package:sadhuapp/core/controller/entity_controller.dart), but got one of type 'EntityController' (in package:sadhuapp/core/controller/entity_controller.dart)`

**Flutter Version:**
Flutter 2.3.0-24.0.pre 

**Getx Version:**
4.1.4

**Describe on which device you found the bug:**
Chrome

**Comment by jonataslaw** [comment] 2021-07-31 16:36
Sorry, but the error described is not framework related. It's a problem with language-level Types caused by either class duplication or an error in the IDE.
As the error is unrelated and cannot be reproduced, I am closing this

**Closed by jonataslaw** 2021-07-31 16:36 UTC
Labels: Unrelated to GetX

**Comment by jefrisingh** [comment] 2021-12-09 19:28
Finally found the issue, It's because Flutter hot reload, If you close and run angain the error won't appear, Hope this will help someone. :).
