### ISSUE TITLE
Latest navigation 2.0 in example_nav2 does not working

### ISSUE THREAD

**Issue by JustonJ99** [jonataslaw/getx#1620] opened 2021-07-11 16:05 UTC
**Describe the bug**
Cloned getx and testing running example2 navigation will hit 
"Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:239:12
_isOriginEntry(state)
is not true"  @ahmednfwela 

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example2 main code:

```dart
void main() {
  runApp(
    GetMaterialApp.router(
      title: "Application",
      getPages: AppPages.routes,
      routeInformationParser: GetInformationParser(
          // initialRoute: Routes.HOME,
          ),
      routerDelegate: GetDelegate(
        backButtonPopMode: PopMode.History,
        preventDuplicateHandlingMode:
            PreventDuplicateHandlingMode.PopUntilOriginalRoute,
      ),
    ),
  );
}
```

**To Reproduce**
1. Run example2 main.dart as Chrome simulator
2. Click on 'Profile' bottom tab for navigation
3. See error
4. URL will stay on /home

**Expected behavior**
It should navigation to /home/profile without the error

**Screenshots**
![image](https://user-images.githubusercontent.com/37526525/125202082-a4a93a80-e2a4-11eb-94bb-a948c253765d.png)

**Flutter Version:**
Flutter 2.2.3 • channel stable

**Getx Version:**
4.1.4

**Describe on which device you found the bug:**
Chrome (wen-javascript)

**Minimal reproduce code**
The code is test from official Getx sample

**Comment by ahmednfwela** [comment] 2021-07-11 18:05
i think duplicate of https://github.com/jonataslaw/getx/issues/1602

**Closed** 2021-07-12 09:35 UTC
