### ISSUE TITLE
Is getx dead?

### ISSUE THREAD

**Issue by omidFdisk** [jonataslaw/getx#2862] opened 2023-08-06 04:58 UTC
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by jakobleck** [comment] 2023-08-07 12:24
Duplicate of https://github.com/jonataslaw/getx/issues/2834 ?!

**Comment by astheras** [comment] 2023-08-15 16:21
pls do not die, i have started to learn bloc. it's just a disaster for me

**Comment by jonataslaw** [comment] 2023-08-31 01:42
Definitely not!

**Closed by jonataslaw** 2023-08-31 01:42 UTC
