### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#416] opened 2020-07-22 23:55 UTC
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
I would like to use Get translations in conjunction with standard localisations, for example, GlobalMaterialLocalizations, or other external package. 
In my case, after I change the locale with Get.updateLocale, the new locale seems not register into the MaterialApp, hence widget with  **_MaterialLocalizations.of(context).cancelButtonLabel_** will not use the new changed locale.

**To Reproduce**
1. In GetMaterialApp, assign the localizations

```dart
 runApp(
  GetMaterialApp(
    supportedLocales: App.supportedLocales,
    localizationsDelegates: [
      FormBuilderLocalizations.delegate,
      GlobalMaterialLocalizations.delegate,
      GlobalWidgetsLocalizations.delegate,
    ],
```
2. Have a form with button to change the locale with Get.updateLocale, all translation using Get way is properly translated.

3. Have another button to call another form which referring the localization context. eg. `MaterialLocalizations.of(context).cancelButtonLabel`

4. The localization remain with the old language.
 
**Expected behavior**
Locale should be updated on MaterialApp after updateLocale.

**Screenshots**

![updateLocaleIssue](https://user-images.githubusercontent.com/107820/88240434-ac4d8900-ccb9-11ea-9427-68963595d144.gif)

**Flutter Version:**
Enter the version of the Flutter you are using
1.17.5

**Get Version:**
Latest, I am pointing to the master branch.

**Describe on which device you found the bug:**
ex: Moto z2 - Android.
Android emulator

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jonataslaw** [comment] 2020-07-27 20:01
Get.updateLocale will update the "locale" property of your MaterialApp, and that's it.
If you are using another solution together for your internationalization, you should look for how to change Locale in this library.
Keep in mind that the internationalization of GetX is just that, it changes the Locale of the MaterialApp, and searches for the keys in a previously inserted Map, and this has no communication with another external library.

**Comment by jasonlaw** [comment] 2020-07-28 00:00
I don't mean to mix the solution with internationalization, but I have other package that build on top of it, for eg. flutter_form_builder. 

If I put a break point here (as per screenshot) in GetMaterialApp, when calling updateLocale, it will not stop at the break point, hence causing the reported issue. However, changing the themeMode will actually run to this breakpoint. So my workaround is following, and it works:

 void updateLocale(Locale l) {
    Get.updateLocale(l);
    Get.changeThemeMode(Get.getxController.themeMode); // calling this to force recreate the MaterialApp
  }

That is ugly, but if you still think that it is normal for updating locale without recreating the MaterialApp, then I can accept this workaround.

![image](https://user-images.githubusercontent.com/107820/88603304-1776d100-d0a7-11ea-9f6c-60efe47b0090.png)

**Comment by jonataslaw** [comment] 2020-07-31 19:11
It is really strange that the theme update works for this case. The changeLocale update is more aggressive, but because it is a forced "hot restart", using apis that are not disclosed, perhaps that may have changed.
I will see this here later.

**Comment by alexkharech** [comment] 2020-09-02 23:42
It would be great to add a localization generator from json files to get_cli, while generating an abstract class with keys and translation maps, just like in the easy_localization package.

**Comment by alexkharech** [comment] 2020-09-02 23:58
json files
```json
{
  "menu": {
    "logoutBtn": "Log out",
    "items": {
      "settings": "Settings",
      "notifications": "Notifications",
      "wallet": "Wallet"
    }
  }
}
```

generated keys
```dart
abstract class LocaleKeys {
  static const menu_logoutBtn = 'menu.logoutBtn';
  static const menu_items_settings = 'menu.items.settings';
  static const menu_items_notifications = 'menu.items.notifications';
  static const menu_items_wallet = 'menu.items.wallet';
}
```

generated localization maps
```dart
abstract class Locales {
  static const Map<String, dynamic> en_US = {
    "menu": {
      "logoutBtn": "Log out",
      "items": {
        "settings": "Settings",
        "notifications": "Notifications",
        "wallet": "Wallet"
      },
    },
  };

  static const Map<String, dynamic> ru_RU = {
    "menu": {
      "logoutBtn": "Выход",
      "items": {
        "settings": "Настройки",
        "notifications": "Оповещения",
        "wallet": "Кошелёк"
      },
    },
  };
}
```

using
```dart
Text(LocaleKeys.menu_logoutBtn.tr)
```

**Comment by jonataslaw** [comment] 2020-09-03 02:05
I tried to view the problem today, and I was unable to reproduce the problem.
Please provide a valid reproduction code

**Comment by jasonlaw** [comment] 2020-09-03 23:38
Reproduction steps:
1. Use the standard counter example.
2. Change the increment method to update locale, Get.updateLocale( null ).
3. Set a breakpoint in GetMaterialApp (inside rootA_widget.dart)
![image](https://user-images.githubusercontent.com/107820/92183269-74249300-ee80-11ea-9151-b3a9edc7e5ea.png)
4. Run with debug, click the FAB and notice the debugger **will not stop at the break point.**

5. Now change the increment method to update theme mode, Get.changeThemeMode(ThemeMode.system).
6. Keep the break point in step 3
7. Run with debug, click the FAB and notice the debugger **stops at the break point.** 

In my case, i have to call the change thememode after updating locale, in order for  it to recreate the material app, and it is working for me.
~~~dart
void updateLocale(Locale l) {
Get.updateLocale(l);
Get.changeThemeMode(Get.getxController.themeMode); // calling this to force recreate the MaterialApp
}
~~~


Here is the reproduction code:

~~~dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    print("Expect forceAppUpdate() in updateLocale will recreate the MaterialApp, but it is not.");
    // Calling this will not stop the breakpoint inside GetMaterialApp (root_widget.dart)
    Get.updateLocale(null);
    // However, calling this will stop the breakpoint inside GetMaterialApp (root_widget.dart)
    Get.changeThemeMode(ThemeMode.system);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
~~~

**Comment by jonataslaw** [comment] 2020-10-01 20:56
Get.updateLocale will rebuild all widgets child from MaterialApp. It does not use the GetBuilder update, so it will not stop at the breakpoint.

Therefore, it is not possible to reproduce your code, since it is already expected behavior.

Note that in git there is already a version with Get.appUpdate(), you might be better off using that than Get.changeTheme() if you want to update GetMaterialApp via the main GetxController.

**Comment by jasonlaw** [comment] 2020-10-07 03:31
Will test with the new method Get.appUpdate() once it is released. Thanks.

**Comment by jonataslaw** [comment] 2020-10-09 23:39
It was released, but it won't be necessary, updateLocale now rebuilds the app from the main.dart, so I'm closing

**Closed by jonataslaw** 2020-10-09 23:39 UTC
Labels: Waiting for customer response, expected behavior

**Comment by shoxrux9906** [comment] 2022-08-20 21:01
dd
